/**
 * BioMasters TCG - Taxonomy Mapping Utilities
 * 
 * Bridges between numeric taxonomy enums (for performance) and 
 * string localization IDs (for display). This ensures type safety
 * while maintaining the hybrid approach benefits.
 */

import {
  TaxoDomain, TaxoKingdom, TaxoPhylum, TaxoClass, 
  TaxoOrder, TaxoFamily, TaxoGenus, TaxoSpecies
} from './enums';
import { TaxonomyDisplayId } from './text-ids';

/**
 * Maps numeric taxonomy enums to localization string IDs
 * This is the bridge between performance (numeric) and localization (string)
 */
export const TAXONOMY_LOCALIZATION_MAP = {
  domain: {
    [TaxoDomain.ARCHAEA]: TaxonomyDisplayId.TAXO_DOMAIN_ARCHAEA,
    [TaxoDomain.BACTERIA]: TaxonomyDisplayId.TAXO_DOMAIN_BACTERIA,
    [TaxoDomain.EUKARYOTA]: TaxonomyDisplayId.TAXO_DOMAIN_EUKARYOTA,
  },
  kingdom: {
    [TaxoKingdom.ANIMALIA]: TaxonomyDisplayId.TAXO_KINGDOM_ANIMALIA,
    [TaxoKingdom.ARCHAEA]: TaxonomyDisplayId.TAXO_KINGDOM_ARCHAEA,
    [TaxoKingdom.BACTERIA]: TaxonomyDisplayId.TAXO_KINGDOM_BACTERIA,
    [TaxoKingdom.CHROMISTA]: TaxonomyDisplayId.TAXO_KINGDOM_CHROMISTA,
    [TaxoKingdom.FUNGI]: TaxonomyDisplayId.TAXO_KINGDOM_FUNGI,
    [TaxoKingdom.PLANTAE]: TaxonomyDisplayId.TAXO_KINGDOM_PLANTAE,
  },
  phylum: {
    [TaxoPhylum.ANNELIDA]: TaxonomyDisplayId.TAXO_PHYLUM_ANNELIDA,
    [TaxoPhylum.AQUIFICOTA]: TaxonomyDisplayId.TAXO_PHYLUM_AQUIFICOTA,
    [TaxoPhylum.ARTHROPODA]: TaxonomyDisplayId.TAXO_PHYLUM_ARTHROPODA,
    [TaxoPhylum.BACILLOTA]: TaxonomyDisplayId.TAXO_PHYLUM_BACILLOTA,
    [TaxoPhylum.BASIDIOMYCOTA]: TaxonomyDisplayId.TAXO_PHYLUM_BASIDIOMYCOTA,
    [TaxoPhylum.CHORDATA]: TaxonomyDisplayId.TAXO_PHYLUM_CHORDATA,
    [TaxoPhylum.GLOMEROMYCOTA]: TaxonomyDisplayId.TAXO_PHYLUM_GLOMEROMYCOTA,
    [TaxoPhylum.MOLLUSCA]: TaxonomyDisplayId.TAXO_PHYLUM_MOLLUSCA,
    [TaxoPhylum.OCHROPHYTA]: TaxonomyDisplayId.TAXO_PHYLUM_OCHROPHYTA,
    [TaxoPhylum.PSEUDOMONADOTA]: TaxonomyDisplayId.TAXO_PHYLUM_PSEUDOMONADOTA,
    [TaxoPhylum.THERMOPROTEOTA]: TaxonomyDisplayId.TAXO_PHYLUM_THERMOPROTEOTA,
    [TaxoPhylum.TRACHEOPHYTA]: TaxonomyDisplayId.TAXO_PHYLUM_TRACHEOPHYTA,
  },
  class: {
    [TaxoClass.ACIDITHIOBACILLIA]: TaxonomyDisplayId.TAXO_CLASS_ACIDITHIOBACILLIA,
    [TaxoClass.ACTINOPTERYGII]: TaxonomyDisplayId.TAXO_CLASS_ACTINOPTERYGII,
    [TaxoClass.AGARICOMYCETES]: TaxonomyDisplayId.TAXO_CLASS_AGARICOMYCETES,
    [TaxoClass.ALPHAPROTEOBACTERIA]: TaxonomyDisplayId.TAXO_CLASS_ALPHAPROTEOBACTERIA,
    [TaxoClass.AMPHIBIA]: TaxonomyDisplayId.TAXO_CLASS_AMPHIBIA,
    [TaxoClass.AQUIFICAE]: TaxonomyDisplayId.TAXO_CLASS_AQUIFICAE,
    [TaxoClass.ARACHNIDA]: TaxonomyDisplayId.TAXO_CLASS_ARACHNIDA,
    [TaxoClass.AVES]: TaxonomyDisplayId.TAXO_CLASS_AVES,
    [TaxoClass.BACILLARIOPHYCEAE]: TaxonomyDisplayId.TAXO_CLASS_BACILLARIOPHYCEAE,
    [TaxoClass.BACILLI]: TaxonomyDisplayId.TAXO_CLASS_BACILLI,
    [TaxoClass.BETAPROTEOBACTERIA]: TaxonomyDisplayId.TAXO_CLASS_BETAPROTEOBACTERIA,
    [TaxoClass.CHONDRICHTHYES]: TaxonomyDisplayId.TAXO_CLASS_CHONDRICHTHYES,
    [TaxoClass.CLITELLATA]: TaxonomyDisplayId.TAXO_CLASS_CLITELLATA,
    [TaxoClass.COPEPODA]: TaxonomyDisplayId.TAXO_CLASS_COPEPODA,
    [TaxoClass.GASTROPODA]: TaxonomyDisplayId.TAXO_CLASS_GASTROPODA,
    [TaxoClass.GLOMEROMYCETES]: TaxonomyDisplayId.TAXO_CLASS_GLOMEROMYCETES,
    [TaxoClass.INSECTA]: TaxonomyDisplayId.TAXO_CLASS_INSECTA,
    [TaxoClass.LILIOPSIDA]: TaxonomyDisplayId.TAXO_CLASS_LILIOPSIDA,
    [TaxoClass.MAGNOLIOPSIDA]: TaxonomyDisplayId.TAXO_CLASS_MAGNOLIOPSIDA,
    [TaxoClass.MALACOSTRACA]: TaxonomyDisplayId.TAXO_CLASS_MALACOSTRACA,
    [TaxoClass.MAMMALIA]: TaxonomyDisplayId.TAXO_CLASS_MAMMALIA,
    [TaxoClass.PHAEOPHYCEAE]: TaxonomyDisplayId.TAXO_CLASS_PHAEOPHYCEAE,
    [TaxoClass.PINOPSIDA]: TaxonomyDisplayId.TAXO_CLASS_PINOPSIDA,
    [TaxoClass.REPTILIA]: TaxonomyDisplayId.TAXO_CLASS_REPTILIA,
    [TaxoClass.THERMOPROTEI]: TaxonomyDisplayId.TAXO_CLASS_THERMOPROTEI,
  },
  order: {
    [TaxoOrder.ACIDITHIOBACILLALES]: TaxonomyDisplayId.TAXO_ORDER_ACIDITHIOBACILLALES,
    [TaxoOrder.AGARICALES]: TaxonomyDisplayId.TAXO_ORDER_AGARICALES,
    [TaxoOrder.ALISMATALES]: TaxonomyDisplayId.TAXO_ORDER_ALISMATALES,
    [TaxoOrder.ANURA]: TaxonomyDisplayId.TAXO_ORDER_ANURA,
    [TaxoOrder.AQUIFICALES]: TaxonomyDisplayId.TAXO_ORDER_AQUIFICALES,
    [TaxoOrder.ARANEAE]: TaxonomyDisplayId.TAXO_ORDER_ARANEAE,
    [TaxoOrder.ARECALES]: TaxonomyDisplayId.TAXO_ORDER_ARECALES,
    [TaxoOrder.ARTIODACTYLA]: TaxonomyDisplayId.TAXO_ORDER_ARTIODACTYLA,
    [TaxoOrder.ASTERALES]: TaxonomyDisplayId.TAXO_ORDER_ASTERALES,
    [TaxoOrder.BACILLALES]: TaxonomyDisplayId.TAXO_ORDER_BACILLALES,
    [TaxoOrder.BURKHOLDERIALES]: TaxonomyDisplayId.TAXO_ORDER_BURKHOLDERIALES,
    [TaxoOrder.CALANOIDA]: TaxonomyDisplayId.TAXO_ORDER_CALANOIDA,
    [TaxoOrder.CARNIVORA]: TaxonomyDisplayId.TAXO_ORDER_CARNIVORA,
    [TaxoOrder.CARYOPHYLLALES]: TaxonomyDisplayId.TAXO_ORDER_CARYOPHYLLALES,
    [TaxoOrder.CATHARTIFORMES]: TaxonomyDisplayId.TAXO_ORDER_CATHARTIFORMES,
    [TaxoOrder.COLEOPTERA]: TaxonomyDisplayId.TAXO_ORDER_COLEOPTERA,
    [TaxoOrder.CRASSICLITELLATA]: TaxonomyDisplayId.TAXO_ORDER_CRASSICLITELLATA,
    [TaxoOrder.DIPROTODONTIA]: TaxonomyDisplayId.TAXO_ORDER_DIPROTODONTIA,
    [TaxoOrder.ERINACEOMORPHA]: TaxonomyDisplayId.TAXO_ORDER_ERINACEOMORPHA,
    [TaxoOrder.EUPHAUSIACEA]: TaxonomyDisplayId.TAXO_ORDER_EUPHAUSIACEA,
    [TaxoOrder.FABALES]: TaxonomyDisplayId.TAXO_ORDER_FABALES,
    [TaxoOrder.FAGALES]: TaxonomyDisplayId.TAXO_ORDER_FAGALES,
    [TaxoOrder.GLOMERALES]: TaxonomyDisplayId.TAXO_ORDER_GLOMERALES,
    [TaxoOrder.HYMENOPTERA]: TaxonomyDisplayId.TAXO_ORDER_HYMENOPTERA,
    [TaxoOrder.HYPHOMICROBIALES]: TaxonomyDisplayId.TAXO_ORDER_HYPHOMICROBIALES,
    [TaxoOrder.IXODIDA]: TaxonomyDisplayId.TAXO_ORDER_IXODIDA,
    [TaxoOrder.LAGOMORPHA]: TaxonomyDisplayId.TAXO_ORDER_LAGOMORPHA,
    [TaxoOrder.LAMIALES]: TaxonomyDisplayId.TAXO_ORDER_LAMIALES,
    [TaxoOrder.LAMINARIALES]: TaxonomyDisplayId.TAXO_ORDER_LAMINARIALES,
    [TaxoOrder.LAMNIFORMES]: TaxonomyDisplayId.TAXO_ORDER_LAMNIFORMES,
    [TaxoOrder.LEPIDOPTERA]: TaxonomyDisplayId.TAXO_ORDER_LEPIDOPTERA,
    [TaxoOrder.LILIALES]: TaxonomyDisplayId.TAXO_ORDER_LILIALES,
    [TaxoOrder.MALVALES]: TaxonomyDisplayId.TAXO_ORDER_MALVALES,
    [TaxoOrder.NITROSOMONADALES]: TaxonomyDisplayId.TAXO_ORDER_NITROSOMONADALES,
    [TaxoOrder.ORTHOPTERA]: TaxonomyDisplayId.TAXO_ORDER_ORTHOPTERA,
    [TaxoOrder.PERISSODACTYLA]: TaxonomyDisplayId.TAXO_ORDER_PERISSODACTYLA,
    [TaxoOrder.PINALES]: TaxonomyDisplayId.TAXO_ORDER_PINALES,
    [TaxoOrder.POALES]: TaxonomyDisplayId.TAXO_ORDER_POALES,
    [TaxoOrder.PRIMATES]: TaxonomyDisplayId.TAXO_ORDER_PRIMATES,
    [TaxoOrder.PROBOSCIDEA]: TaxonomyDisplayId.TAXO_ORDER_PROBOSCIDEA,
    [TaxoOrder.RODENTIA]: TaxonomyDisplayId.TAXO_ORDER_RODENTIA,
    [TaxoOrder.ROSALES]: TaxonomyDisplayId.TAXO_ORDER_ROSALES,
    [TaxoOrder.SALMONIFORMES]: TaxonomyDisplayId.TAXO_ORDER_SALMONIFORMES,
    [TaxoOrder.SCORPIONES]: TaxonomyDisplayId.TAXO_ORDER_SCORPIONES,
    [TaxoOrder.SQUAMATA]: TaxonomyDisplayId.TAXO_ORDER_SQUAMATA,
    [TaxoOrder.STYLOMMATOPHORA]: TaxonomyDisplayId.TAXO_ORDER_STYLOMMATOPHORA,
    [TaxoOrder.TESTUDINES]: TaxonomyDisplayId.TAXO_ORDER_TESTUDINES,
    [TaxoOrder.THALASSIOSIRALES]: TaxonomyDisplayId.TAXO_ORDER_THALASSIOSIRALES,
    [TaxoOrder.THERMOPROTEALES]: TaxonomyDisplayId.TAXO_ORDER_THERMOPROTEALES,
    [TaxoOrder.VITALES]: TaxonomyDisplayId.TAXO_ORDER_VITALES,
  },
  family: {
    [TaxoFamily.ACIDITHIOBACILLACEAE]: TaxonomyDisplayId.TAXO_FAMILY_ACIDITHIOBACILLACEAE,
    [TaxoFamily.AGARICACEAE]: TaxonomyDisplayId.TAXO_FAMILY_AGARICACEAE,
    [TaxoFamily.APIDAE]: TaxonomyDisplayId.TAXO_FAMILY_APIDAE,
    [TaxoFamily.AQUIFICACEAE]: TaxonomyDisplayId.TAXO_FAMILY_AQUIFICACEAE,
    [TaxoFamily.ARANEIDAE]: TaxonomyDisplayId.TAXO_FAMILY_ARANEIDAE,
    [TaxoFamily.ARECACEAE]: TaxonomyDisplayId.TAXO_FAMILY_ARECACEAE,
    [TaxoFamily.ASTERACEAE]: TaxonomyDisplayId.TAXO_FAMILY_ASTERACEAE,
    [TaxoFamily.BACILLACEAE]: TaxonomyDisplayId.TAXO_FAMILY_BACILLACEAE,
    [TaxoFamily.BOVIDAE]: TaxonomyDisplayId.TAXO_FAMILY_BOVIDAE,
    [TaxoFamily.CACTACEAE]: TaxonomyDisplayId.TAXO_FAMILY_CACTACEAE,
    [TaxoFamily.CALANIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CALANIDAE,
    [TaxoFamily.CAMELIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CAMELIDAE,
    [TaxoFamily.CANIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CANIDAE,
    [TaxoFamily.CASTORIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CASTORIDAE,
    [TaxoFamily.CATHARTIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CATHARTIDAE,
    [TaxoFamily.CERVIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CERVIDAE,
    [TaxoFamily.CHELONIIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CHELONIIDAE,
    [TaxoFamily.COMAMONADACEAE]: TaxonomyDisplayId.TAXO_FAMILY_COMAMONADACEAE,
    [TaxoFamily.CRICETIDAE]: TaxonomyDisplayId.TAXO_FAMILY_CRICETIDAE,
    [TaxoFamily.ELEPHANTIDAE]: TaxonomyDisplayId.TAXO_FAMILY_ELEPHANTIDAE,
    [TaxoFamily.EQUIDAE]: TaxonomyDisplayId.TAXO_FAMILY_EQUIDAE,
    [TaxoFamily.ERINACEIDAE]: TaxonomyDisplayId.TAXO_FAMILY_ERINACEIDAE,
    [TaxoFamily.EUPHAUSIIDAE]: TaxonomyDisplayId.TAXO_FAMILY_EUPHAUSIIDAE,
    [TaxoFamily.FABACEAE]: TaxonomyDisplayId.TAXO_FAMILY_FABACEAE,
    [TaxoFamily.FAGACEAE]: TaxonomyDisplayId.TAXO_FAMILY_FAGACEAE,
    [TaxoFamily.FELIDAE]: TaxonomyDisplayId.TAXO_FAMILY_FELIDAE,
    [TaxoFamily.FORMICIDAE]: TaxonomyDisplayId.TAXO_FAMILY_FORMICIDAE,
    [TaxoFamily.GIRAFFIDAE]: TaxonomyDisplayId.TAXO_FAMILY_GIRAFFIDAE,
    [TaxoFamily.GLOMERACEAE]: TaxonomyDisplayId.TAXO_FAMILY_GLOMERACEAE,
    [TaxoFamily.GRYLLIDAE]: TaxonomyDisplayId.TAXO_FAMILY_GRYLLIDAE,
    [TaxoFamily.HADRURIDAE]: TaxonomyDisplayId.TAXO_FAMILY_HADRURIDAE,
    [TaxoFamily.HELICIDAE]: TaxonomyDisplayId.TAXO_FAMILY_HELICIDAE,
    [TaxoFamily.HIPPOPOTAMIDAE]: TaxonomyDisplayId.TAXO_FAMILY_HIPPOPOTAMIDAE,
    [TaxoFamily.HOMINIDAE]: TaxonomyDisplayId.TAXO_FAMILY_HOMINIDAE,
    [TaxoFamily.IXODIDAE]: TaxonomyDisplayId.TAXO_FAMILY_IXODIDAE,
    [TaxoFamily.LACERTIDAE]: TaxonomyDisplayId.TAXO_FAMILY_LACERTIDAE,
    [TaxoFamily.LAMIACEAE]: TaxonomyDisplayId.TAXO_FAMILY_LAMIACEAE,
    [TaxoFamily.LAMINARIACEAE]: TaxonomyDisplayId.TAXO_FAMILY_LAMINARIACEAE,
    [TaxoFamily.LAMNIDAE]: TaxonomyDisplayId.TAXO_FAMILY_LAMNIDAE,
    [TaxoFamily.LEPORIDAE]: TaxonomyDisplayId.TAXO_FAMILY_LEPORIDAE,
    [TaxoFamily.LILIACEAE]: TaxonomyDisplayId.TAXO_FAMILY_LILIACEAE,
    [TaxoFamily.LUMBRICIDAE]: TaxonomyDisplayId.TAXO_FAMILY_LUMBRICIDAE,
    [TaxoFamily.MALVACEAE]: TaxonomyDisplayId.TAXO_FAMILY_MALVACEAE,
    [TaxoFamily.MURIDAE]: TaxonomyDisplayId.TAXO_FAMILY_MURIDAE,
    [TaxoFamily.MYCENACEAE]: TaxonomyDisplayId.TAXO_FAMILY_MYCENACEAE,
    [TaxoFamily.NITROSOMONADACEAE]: TaxonomyDisplayId.TAXO_FAMILY_NITROSOMONADACEAE,
    [TaxoFamily.NYMPHALIDAE]: TaxonomyDisplayId.TAXO_FAMILY_NYMPHALIDAE,
    [TaxoFamily.PHASCOLARCTIDAE]: TaxonomyDisplayId.TAXO_FAMILY_PHASCOLARCTIDAE,
    [TaxoFamily.PINACEAE]: TaxonomyDisplayId.TAXO_FAMILY_PINACEAE,
    [TaxoFamily.POACEAE]: TaxonomyDisplayId.TAXO_FAMILY_POACEAE,
    [TaxoFamily.PROCYONIDAE]: TaxonomyDisplayId.TAXO_FAMILY_PROCYONIDAE,
    [TaxoFamily.PYTHONIDAE]: TaxonomyDisplayId.TAXO_FAMILY_PYTHONIDAE,
    [TaxoFamily.RANIDAE]: TaxonomyDisplayId.TAXO_FAMILY_RANIDAE,
    [TaxoFamily.RHINOCEROTIDAE]: TaxonomyDisplayId.TAXO_FAMILY_RHINOCEROTIDAE,
    [TaxoFamily.RHIZOBIACEAE]: TaxonomyDisplayId.TAXO_FAMILY_RHIZOBIACEAE,
    [TaxoFamily.ROSACEAE]: TaxonomyDisplayId.TAXO_FAMILY_ROSACEAE,
    [TaxoFamily.SALMONIDAE]: TaxonomyDisplayId.TAXO_FAMILY_SALMONIDAE,
    [TaxoFamily.SCARABAEIDAE]: TaxonomyDisplayId.TAXO_FAMILY_SCARABAEIDAE,
    [TaxoFamily.SCIURIDAE]: TaxonomyDisplayId.TAXO_FAMILY_SCIURIDAE,
    [TaxoFamily.SUIDAE]: TaxonomyDisplayId.TAXO_FAMILY_SUIDAE,
    [TaxoFamily.THALASSIOSIRACEAE]: TaxonomyDisplayId.TAXO_FAMILY_THALASSIOSIRACEAE,
    [TaxoFamily.THERMOFILACEAE]: TaxonomyDisplayId.TAXO_FAMILY_THERMOFILACEAE,
    [TaxoFamily.URSIDAE]: TaxonomyDisplayId.TAXO_FAMILY_URSIDAE,
    [TaxoFamily.VITACEAE]: TaxonomyDisplayId.TAXO_FAMILY_VITACEAE,
    [TaxoFamily.ZOSTERACEAE]: TaxonomyDisplayId.TAXO_FAMILY_ZOSTERACEAE,
  },
  genus: {
    [TaxoGenus.ACHETA]: TaxonomyDisplayId.TAXO_GENUS_ACHETA,
    [TaxoGenus.ACIDITHIOBACILLUS]: TaxonomyDisplayId.TAXO_GENUS_ACIDITHIOBACILLUS,
    [TaxoGenus.AGARICUS]: TaxonomyDisplayId.TAXO_GENUS_AGARICUS,
    [TaxoGenus.AILUROPODA]: TaxonomyDisplayId.TAXO_GENUS_AILUROPODA,
    [TaxoGenus.APIS]: TaxonomyDisplayId.TAXO_GENUS_APIS,
    [TaxoGenus.AQUIFEX]: TaxonomyDisplayId.TAXO_GENUS_AQUIFEX,
    [TaxoGenus.ARANEUS]: TaxonomyDisplayId.TAXO_GENUS_ARANEUS,
    [TaxoGenus.BACILLUS]: TaxonomyDisplayId.TAXO_GENUS_BACILLUS,
    [TaxoGenus.BELLIS]: TaxonomyDisplayId.TAXO_GENUS_BELLIS,
    [TaxoGenus.BISON]: TaxonomyDisplayId.TAXO_GENUS_BISON,
    [TaxoGenus.BOS]: TaxonomyDisplayId.TAXO_GENUS_BOS,
    [TaxoGenus.BUBALUS]: TaxonomyDisplayId.TAXO_GENUS_BUBALUS,
    [TaxoGenus.CALANUS]: TaxonomyDisplayId.TAXO_GENUS_CALANUS,
    [TaxoGenus.CAMELUS]: TaxonomyDisplayId.TAXO_GENUS_CAMELUS,
    [TaxoGenus.CANIS]: TaxonomyDisplayId.TAXO_GENUS_CANIS,
    [TaxoGenus.CAPRA]: TaxonomyDisplayId.TAXO_GENUS_CAPRA,
    [TaxoGenus.CARCHARODON]: TaxonomyDisplayId.TAXO_GENUS_CARCHARODON,
    [TaxoGenus.CASTOR]: TaxonomyDisplayId.TAXO_GENUS_CASTOR,
    [TaxoGenus.CATHARTES]: TaxonomyDisplayId.TAXO_GENUS_CATHARTES,
    [TaxoGenus.CERATOTHERIUM]: TaxonomyDisplayId.TAXO_GENUS_CERATOTHERIUM,
    [TaxoGenus.CHELONIA]: TaxonomyDisplayId.TAXO_GENUS_CHELONIA,
    [TaxoGenus.COCOS]: TaxonomyDisplayId.TAXO_GENUS_COCOS,
    [TaxoGenus.DANAUS]: TaxonomyDisplayId.TAXO_GENUS_DANAUS,
    [TaxoGenus.EQUUS]: TaxonomyDisplayId.TAXO_GENUS_EQUUS,
    [TaxoGenus.ERINACEUS]: TaxonomyDisplayId.TAXO_GENUS_ERINACEUS,
    [TaxoGenus.EUPHAUSIA]: TaxonomyDisplayId.TAXO_GENUS_EUPHAUSIA,
    [TaxoGenus.FELIS]: TaxonomyDisplayId.TAXO_GENUS_FELIS,
    [TaxoGenus.FORMICA]: TaxonomyDisplayId.TAXO_GENUS_FORMICA,
    [TaxoGenus.FRAGARIA]: TaxonomyDisplayId.TAXO_GENUS_FRAGARIA,
    [TaxoGenus.GIRAFFA]: TaxonomyDisplayId.TAXO_GENUS_GIRAFFA,
    [TaxoGenus.GLOMUS]: TaxonomyDisplayId.TAXO_GENUS_GLOMUS,
    [TaxoGenus.GORILLA]: TaxonomyDisplayId.TAXO_GENUS_GORILLA,
    [TaxoGenus.HADRURUS]: TaxonomyDisplayId.TAXO_GENUS_HADRURUS,
    [TaxoGenus.HELIANTHUS]: TaxonomyDisplayId.TAXO_GENUS_HELIANTHUS,
    [TaxoGenus.HELIX]: TaxonomyDisplayId.TAXO_GENUS_HELIX,
    [TaxoGenus.HIBISCUS]: TaxonomyDisplayId.TAXO_GENUS_HIBISCUS,
    [TaxoGenus.HIPPOPOTAMUS]: TaxonomyDisplayId.TAXO_GENUS_HIPPOPOTAMUS,
    [TaxoGenus.IXODES]: TaxonomyDisplayId.TAXO_GENUS_IXODES,
    [TaxoGenus.LACERTA]: TaxonomyDisplayId.TAXO_GENUS_LACERTA,
    [TaxoGenus.LAMA]: TaxonomyDisplayId.TAXO_GENUS_LAMA,
    [TaxoGenus.LOLIUM]: TaxonomyDisplayId.TAXO_GENUS_LOLIUM,
    [TaxoGenus.LOXODONTA]: TaxonomyDisplayId.TAXO_GENUS_LOXODONTA,
    [TaxoGenus.LUMBRICUS]: TaxonomyDisplayId.TAXO_GENUS_LUMBRICUS,
    [TaxoGenus.MACROCYSTIS]: TaxonomyDisplayId.TAXO_GENUS_MACROCYSTIS,
    [TaxoGenus.MALUS]: TaxonomyDisplayId.TAXO_GENUS_MALUS,
    [TaxoGenus.MAMMUTHUS]: TaxonomyDisplayId.TAXO_GENUS_MAMMUTHUS,
    [TaxoGenus.MENTHA]: TaxonomyDisplayId.TAXO_GENUS_MENTHA,
    [TaxoGenus.MESOCRICETUS]: TaxonomyDisplayId.TAXO_GENUS_MESOCRICETUS,
    [TaxoGenus.MUS]: TaxonomyDisplayId.TAXO_GENUS_MUS,
    [TaxoGenus.MYCENA]: TaxonomyDisplayId.TAXO_GENUS_MYCENA,
    [TaxoGenus.NITROSOMONAS]: TaxonomyDisplayId.TAXO_GENUS_NITROSOMONAS,
    [TaxoGenus.ODOCOILEUS]: TaxonomyDisplayId.TAXO_GENUS_ODOCOILEUS,
    [TaxoGenus.ONCORHYNCHUS]: TaxonomyDisplayId.TAXO_GENUS_ONCORHYNCHUS,
    [TaxoGenus.OPUNTIA]: TaxonomyDisplayId.TAXO_GENUS_OPUNTIA,
    [TaxoGenus.ORYCTOLAGUS]: TaxonomyDisplayId.TAXO_GENUS_ORYCTOLAGUS,
    [TaxoGenus.ORYZA]: TaxonomyDisplayId.TAXO_GENUS_ORYZA,
    [TaxoGenus.OVIS]: TaxonomyDisplayId.TAXO_GENUS_OVIS,
    [TaxoGenus.PAN]: TaxonomyDisplayId.TAXO_GENUS_PAN,
    [TaxoGenus.PANTHERA]: TaxonomyDisplayId.TAXO_GENUS_PANTHERA,
    [TaxoGenus.PHALARIS]: TaxonomyDisplayId.TAXO_GENUS_PHALARIS,
    [TaxoGenus.PHASCOLARCTOS]: TaxonomyDisplayId.TAXO_GENUS_PHASCOLARCTOS,
    [TaxoGenus.PINUS]: TaxonomyDisplayId.TAXO_GENUS_PINUS,
    [TaxoGenus.PONGO]: TaxonomyDisplayId.TAXO_GENUS_PONGO,
    [TaxoGenus.PROCYON]: TaxonomyDisplayId.TAXO_GENUS_PROCYON,
    [TaxoGenus.PRUNUS]: TaxonomyDisplayId.TAXO_GENUS_PRUNUS,
    [TaxoGenus.PYROCOCCUS]: TaxonomyDisplayId.TAXO_GENUS_PYROCOCCUS,
    [TaxoGenus.PYTHON]: TaxonomyDisplayId.TAXO_GENUS_PYTHON,
    [TaxoGenus.QUERCUS]: TaxonomyDisplayId.TAXO_GENUS_QUERCUS,
    [TaxoGenus.RANA]: TaxonomyDisplayId.TAXO_GENUS_RANA,
    [TaxoGenus.RHIZOBIUM]: TaxonomyDisplayId.TAXO_GENUS_RHIZOBIUM,
    [TaxoGenus.ROSA]: TaxonomyDisplayId.TAXO_GENUS_ROSA,
    [TaxoGenus.SCARABAEUS]: TaxonomyDisplayId.TAXO_GENUS_SCARABAEUS,
    [TaxoGenus.SUS]: TaxonomyDisplayId.TAXO_GENUS_SUS,
    [TaxoGenus.TAMIAS]: TaxonomyDisplayId.TAXO_GENUS_TAMIAS,
    [TaxoGenus.THALASSIOSIRA]: TaxonomyDisplayId.TAXO_GENUS_THALASSIOSIRA,
    [TaxoGenus.THIOBACILLUS]: TaxonomyDisplayId.TAXO_GENUS_THIOBACILLUS,
    [TaxoGenus.TRIFOLIUM]: TaxonomyDisplayId.TAXO_GENUS_TRIFOLIUM,
    [TaxoGenus.TULIPA]: TaxonomyDisplayId.TAXO_GENUS_TULIPA,
    [TaxoGenus.URSUS]: TaxonomyDisplayId.TAXO_GENUS_URSUS,
    [TaxoGenus.VITIS]: TaxonomyDisplayId.TAXO_GENUS_VITIS,
    [TaxoGenus.VULPES]: TaxonomyDisplayId.TAXO_GENUS_VULPES,
    [TaxoGenus.ZEA]: TaxonomyDisplayId.TAXO_GENUS_ZEA,
    [TaxoGenus.ZOSTERA]: TaxonomyDisplayId.TAXO_GENUS_ZOSTERA,
  },
  species: {
    [TaxoSpecies.AEGAGRUS]: TaxonomyDisplayId.TAXO_SPECIES_AEGAGRUS,
    [TaxoSpecies.AEOLICUS]: TaxonomyDisplayId.TAXO_SPECIES_AEOLICUS,
    [TaxoSpecies.AFRICANA]: TaxonomyDisplayId.TAXO_SPECIES_AFRICANA,
    [TaxoSpecies.AMERICANUS]: TaxonomyDisplayId.TAXO_SPECIES_AMERICANUS,
    [TaxoSpecies.AMPHIBIUS]: TaxonomyDisplayId.TAXO_SPECIES_AMPHIBIUS,
    [TaxoSpecies.ANANASSA]: TaxonomyDisplayId.TAXO_SPECIES_ANANASSA,
    [TaxoSpecies.ANNUUS]: TaxonomyDisplayId.TAXO_SPECIES_ANNUUS,
    [TaxoSpecies.ARIZONENSIS]: TaxonomyDisplayId.TAXO_SPECIES_ARIZONENSIS,
    [TaxoSpecies.ARUNDINACEA]: TaxonomyDisplayId.TAXO_SPECIES_ARUNDINACEA,
    [TaxoSpecies.AURA]: TaxonomyDisplayId.TAXO_SPECIES_AURA,
    [TaxoSpecies.AURATUS]: TaxonomyDisplayId.TAXO_SPECIES_AURATUS,
    [TaxoSpecies.BERINGEI]: TaxonomyDisplayId.TAXO_SPECIES_BERINGEI,
    [TaxoSpecies.BISON]: TaxonomyDisplayId.TAXO_SPECIES_BISON,
    [TaxoSpecies.BISPORUS]: TaxonomyDisplayId.TAXO_SPECIES_BISPORUS,
    [TaxoSpecies.BUBALIS]: TaxonomyDisplayId.TAXO_SPECIES_BUBALIS,
    [TaxoSpecies.CABALLUS]: TaxonomyDisplayId.TAXO_SPECIES_CABALLUS,
    [TaxoSpecies.CAMELOPARDALIS]: TaxonomyDisplayId.TAXO_SPECIES_CAMELOPARDALIS,
    [TaxoSpecies.CANADENSIS]: TaxonomyDisplayId.TAXO_SPECIES_CANADENSIS,
    [TaxoSpecies.CARCHARIAS]: TaxonomyDisplayId.TAXO_SPECIES_CARCHARIAS,
    [TaxoSpecies.CATUS]: TaxonomyDisplayId.TAXO_SPECIES_CATUS,
    [TaxoSpecies.CINEREUS]: TaxonomyDisplayId.TAXO_SPECIES_CINEREUS,
    [TaxoSpecies.CUNICULUS]: TaxonomyDisplayId.TAXO_SPECIES_CUNICULUS,
    [TaxoSpecies.DENITRIFICANS]: TaxonomyDisplayId.TAXO_SPECIES_DENITRIFICANS,
    [TaxoSpecies.DESERTI]: TaxonomyDisplayId.TAXO_SPECIES_DESERTI,
    [TaxoSpecies.DIADEMATUS]: TaxonomyDisplayId.TAXO_SPECIES_DIADEMATUS,
    [TaxoSpecies.DOMESTICUS]: TaxonomyDisplayId.TAXO_SPECIES_DOMESTICUS,
    [TaxoSpecies.DROMEDARIUS]: TaxonomyDisplayId.TAXO_SPECIES_DROMEDARIUS,
    [TaxoSpecies.EUROPAEA]: TaxonomyDisplayId.TAXO_SPECIES_EUROPAEA,
    [TaxoSpecies.EUROPAEUS]: TaxonomyDisplayId.TAXO_SPECIES_EUROPAEUS,
    [TaxoSpecies.FERROOXIDANS]: TaxonomyDisplayId.TAXO_SPECIES_FERROOXIDANS,
    [TaxoSpecies.FICUS_INDICA]: TaxonomyDisplayId.TAXO_SPECIES_FICUS_INDICA,
    [TaxoSpecies.FINMARCHICUS]: TaxonomyDisplayId.TAXO_SPECIES_FINMARCHICUS,
    [TaxoSpecies.FURIOSUS]: TaxonomyDisplayId.TAXO_SPECIES_FURIOSUS,
    [TaxoSpecies.GALERICULATA]: TaxonomyDisplayId.TAXO_SPECIES_GALERICULATA,
    [TaxoSpecies.GESNERIANA]: TaxonomyDisplayId.TAXO_SPECIES_GESNERIANA,
    [TaxoSpecies.GLAMA]: TaxonomyDisplayId.TAXO_SPECIES_GLAMA,
    [TaxoSpecies.INTRARADICES]: TaxonomyDisplayId.TAXO_SPECIES_INTRARADICES,
    [TaxoSpecies.LATICOLLIS]: TaxonomyDisplayId.TAXO_SPECIES_LATICOLLIS,
    [TaxoSpecies.LEGUMINOSARUM]: TaxonomyDisplayId.TAXO_SPECIES_LEGUMINOSARUM,
    [TaxoSpecies.LEO]: TaxonomyDisplayId.TAXO_SPECIES_LEO,
    [TaxoSpecies.LOTOR]: TaxonomyDisplayId.TAXO_SPECIES_LOTOR,
    [TaxoSpecies.LUPUS]: TaxonomyDisplayId.TAXO_SPECIES_LUPUS,
    [TaxoSpecies.MARINA]: TaxonomyDisplayId.TAXO_SPECIES_MARINA,
    [TaxoSpecies.MAYS]: TaxonomyDisplayId.TAXO_SPECIES_MAYS,
    [TaxoSpecies.MELANOLEUCA]: TaxonomyDisplayId.TAXO_SPECIES_MELANOLEUCA,
    [TaxoSpecies.MELLIFERA]: TaxonomyDisplayId.TAXO_SPECIES_MELLIFERA,
    [TaxoSpecies.MUSCULUS]: TaxonomyDisplayId.TAXO_SPECIES_MUSCULUS,
    [TaxoSpecies.MYDAS]: TaxonomyDisplayId.TAXO_SPECIES_MYDAS,
    [TaxoSpecies.NERKA]: TaxonomyDisplayId.TAXO_SPECIES_NERKA,
    [TaxoSpecies.NUCIFERA]: TaxonomyDisplayId.TAXO_SPECIES_NUCIFERA,
    [TaxoSpecies.PACIFICA]: TaxonomyDisplayId.TAXO_SPECIES_PACIFICA,
    [TaxoSpecies.PARDUS]: TaxonomyDisplayId.TAXO_SPECIES_PARDUS,
    [TaxoSpecies.PERENNE]: TaxonomyDisplayId.TAXO_SPECIES_PERENNE,
    [TaxoSpecies.PERENNIS]: TaxonomyDisplayId.TAXO_SPECIES_PERENNIS,
    [TaxoSpecies.PLEXIPPUS]: TaxonomyDisplayId.TAXO_SPECIES_PLEXIPPUS,
    [TaxoSpecies.POMATIA]: TaxonomyDisplayId.TAXO_SPECIES_POMATIA,
    [TaxoSpecies.PRIMIGENIUS]: TaxonomyDisplayId.TAXO_SPECIES_PRIMIGENIUS,
    [TaxoSpecies.PSEUDONANA]: TaxonomyDisplayId.TAXO_SPECIES_PSEUDONANA,
    [TaxoSpecies.PUMILA]: TaxonomyDisplayId.TAXO_SPECIES_PUMILA,
    [TaxoSpecies.PYGMAEUS]: TaxonomyDisplayId.TAXO_SPECIES_PYGMAEUS,
    [TaxoSpecies.PYRIFERA]: TaxonomyDisplayId.TAXO_SPECIES_PYRIFERA,
    [TaxoSpecies.QUAGGA]: TaxonomyDisplayId.TAXO_SPECIES_QUAGGA,
    [TaxoSpecies.REGIUS]: TaxonomyDisplayId.TAXO_SPECIES_REGIUS,
    [TaxoSpecies.REPENS]: TaxonomyDisplayId.TAXO_SPECIES_REPENS,
    [TaxoSpecies.ROBUR]: TaxonomyDisplayId.TAXO_SPECIES_ROBUR,
    [TaxoSpecies.ROSA_SINENSIS]: TaxonomyDisplayId.TAXO_SPECIES_ROSA_SINENSIS,
    [TaxoSpecies.RUBIGINOSA]: TaxonomyDisplayId.TAXO_SPECIES_RUBIGINOSA,
    [TaxoSpecies.RUFA]: TaxonomyDisplayId.TAXO_SPECIES_RUFA,
    [TaxoSpecies.SACER]: TaxonomyDisplayId.TAXO_SPECIES_SACER,
    [TaxoSpecies.SATIVA]: TaxonomyDisplayId.TAXO_SPECIES_SATIVA,
    [TaxoSpecies.SCAPULARIS]: TaxonomyDisplayId.TAXO_SPECIES_SCAPULARIS,
    [TaxoSpecies.SCROFA]: TaxonomyDisplayId.TAXO_SPECIES_SCROFA,
    [TaxoSpecies.SERRULATA]: TaxonomyDisplayId.TAXO_SPECIES_SERRULATA,
    [TaxoSpecies.SIMUM]: TaxonomyDisplayId.TAXO_SPECIES_SIMUM,
    [TaxoSpecies.SPICATA]: TaxonomyDisplayId.TAXO_SPECIES_SPICATA,
    [TaxoSpecies.STRIATUS]: TaxonomyDisplayId.TAXO_SPECIES_STRIATUS,
    [TaxoSpecies.SUBTILIS]: TaxonomyDisplayId.TAXO_SPECIES_SUBTILIS,
    [TaxoSpecies.SYLVESTRIS]: TaxonomyDisplayId.TAXO_SPECIES_SYLVESTRIS,
    [TaxoSpecies.TAURUS]: TaxonomyDisplayId.TAXO_SPECIES_TAURUS,
    [TaxoSpecies.TEMPORARIA]: TaxonomyDisplayId.TAXO_SPECIES_TEMPORARIA,
    [TaxoSpecies.TERRESTRIS]: TaxonomyDisplayId.TAXO_SPECIES_TERRESTRIS,
    [TaxoSpecies.TIGRIS]: TaxonomyDisplayId.TAXO_SPECIES_TIGRIS,
    [TaxoSpecies.TROGLODYTES]: TaxonomyDisplayId.TAXO_SPECIES_TROGLODYTES,
    [TaxoSpecies.VINIFERA]: TaxonomyDisplayId.TAXO_SPECIES_VINIFERA,
    [TaxoSpecies.VIRGINIANUS]: TaxonomyDisplayId.TAXO_SPECIES_VIRGINIANUS,
    [TaxoSpecies.VULPES]: TaxonomyDisplayId.TAXO_SPECIES_VULPES,
  }
} as const;

/**
 * Utility functions for taxonomy mapping
 * These provide type-safe access to localization IDs from numeric enums
 */
export class TaxonomyMapper {
  static getDomainDisplayId(domain: TaxoDomain): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.domain as any)[domain] || `TAXO_DOMAIN_${domain}` as TaxonomyDisplayId;
  }

  static getKingdomDisplayId(kingdom: TaxoKingdom): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.kingdom as any)[kingdom] || `TAXO_KINGDOM_${kingdom}` as TaxonomyDisplayId;
  }

  static getPhylumDisplayId(phylum: TaxoPhylum): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.phylum as any)[phylum] || `TAXO_PHYLUM_${phylum}` as TaxonomyDisplayId;
  }

  static getClassDisplayId(taxoClass: TaxoClass): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.class as any)[taxoClass] || `TAXO_CLASS_${taxoClass}` as TaxonomyDisplayId;
  }

  static getOrderDisplayId(order: TaxoOrder): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.order as any)[order] || `TAXO_ORDER_${order}` as TaxonomyDisplayId;
  }

  static getFamilyDisplayId(family: TaxoFamily): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.family as any)[family] || `TAXO_FAMILY_${family}` as TaxonomyDisplayId;
  }

  static getGenusDisplayId(genus: TaxoGenus): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.genus as any)[genus] || `TAXO_GENUS_${genus}` as TaxonomyDisplayId;
  }
  
  static getSpeciesDisplayId(species: TaxoSpecies): TaxonomyDisplayId {
    return (TAXONOMY_LOCALIZATION_MAP.species as any)[species] || `TAXO_SPECIES_${species}` as TaxonomyDisplayId;
  }
}
