/**
 * BioMasters TCG - Text ID Enums
 *
 * This file contains all text identifiers used for localization.
 * These IDs are used to reference text content in localization files.
 *
 * IMPORTANT: These are the single source of truth for all localizable text.
 * When adding new content, add the ID here first, then add translations.
 */

// ============================================================================
// LANGUAGE AND LOCALIZATION ENUMS
// ============================================================================

/**
 * Supported languages for localization
 */
export enum SupportedLanguage {
  ENGLISH = 'en',
  SPANISH = 'es'
}

/**
 * Language display information
 */
export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

/**
 * Language configuration mapping
 */
export const LANGUAGE_CONFIG: Record<SupportedLanguage, LanguageInfo> = {
  [SupportedLanguage.ENGLISH]: {
    code: SupportedLanguage.ENGLISH,
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸'
  },
  [SupportedLanguage.SPANISH]: {
    code: SupportedLanguage.SPANISH,
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸'
  }
};

// ============================================================================
// CARD TEXT IDS
// ============================================================================

/**
 * Card Name IDs - Used for card display names
 */
export enum CardNameId {
  // Producers (Trophic Level 1)
  CARD_OAK_TREE = 'CARD_OAK_TREE',
  CARD_GIANT_KELP = 'CARD_GIANT_KELP',
  CARD_REED_CANARY_GRASS = 'CARD_REED_CANARY_GRASS',
  CARD_PHYTOPLANKTON = 'CARD_PHYTOPLANKTON',

  // Chemoautotrophs (Trophic Level 1)
  CARD_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA = 'CARD_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA',
  CARD_IRON_SPRING_BACTERIA = 'CARD_IRON_SPRING_BACTERIA',
  CARD_VOLCANIC_HYDROGEN_BACTERIA = 'CARD_VOLCANIC_HYDROGEN_BACTERIA',
  CARD_NITRIFYING_SOIL_BACTERIA = 'CARD_NITRIFYING_SOIL_BACTERIA',
  CARD_SEDIMENT_CHEMOSYNTHETIC_BACTERIA = 'CARD_SEDIMENT_CHEMOSYNTHETIC_BACTERIA',

  // Primary Consumers (Trophic Level 2)
  CARD_EUROPEAN_RABBIT = 'CARD_EUROPEAN_RABBIT',
  CARD_SOCKEYE_SALMON = 'CARD_SOCKEYE_SALMON',
  CARD_PACIFIC_KRILL = 'CARD_PACIFIC_KRILL',
  CARD_ZOOPLANKTON = 'CARD_ZOOPLANKTON',
  CARD_EUROPEAN_HONEY_BEE = 'CARD_EUROPEAN_HONEY_BEE',

  // Secondary/Tertiary Consumers (Trophic Level 3-4)
  CARD_AMERICAN_BLACK_BEAR = 'CARD_AMERICAN_BLACK_BEAR',
  CARD_GREAT_WHITE_SHARK = 'CARD_GREAT_WHITE_SHARK',

  // Decomposers (Trophic Level -1)
  CARD_MYCENA_MUSHROOM = 'CARD_MYCENA_MUSHROOM',
  CARD_TURKEY_VULTURE = 'CARD_TURKEY_VULTURE',
  CARD_SOIL_BACTERIA = 'CARD_SOIL_BACTERIA',
  CARD_DECOMPOSER_MUSHROOM = 'CARD_DECOMPOSER_MUSHROOM',

  // Detritivores (Trophic Level -2)
  CARD_COMMON_EARTHWORM = 'CARD_COMMON_EARTHWORM',
  CARD_DUNG_BEETLE = 'CARD_DUNG_BEETLE',

  // Parasites
  CARD_DEER_TICK = 'CARD_DEER_TICK',

  // Mutualists
  CARD_MYCORRHIZAL_FUNGI = 'CARD_MYCORRHIZAL_FUNGI',
  CARD_NITROGEN_FIXING_BACTERIA = 'CARD_NITROGEN_FIXING_BACTERIA',

  // Additional Producers (Trees and Plants)
  CARD_APPLE_TREE = 'CARD_APPLE_TREE',
  CARD_ENGLISH_OAK = 'CARD_ENGLISH_OAK',
  CARD_SCOTS_PINE = 'CARD_SCOTS_PINE',
  CARD_COCONUT_PALM = 'CARD_COCONUT_PALM',
  CARD_CHERRY_BLOSSOM = 'CARD_CHERRY_BLOSSOM',
  CARD_BUSH_CHERRY = 'CARD_BUSH_CHERRY',
  CARD_PRICKLY_PEAR_CACTUS = 'CARD_PRICKLY_PEAR_CACTUS',
  CARD_COMMON_GRAPE_VINE = 'CARD_COMMON_GRAPE_VINE',
  CARD_PERENNIAL_RYEGRASS = 'CARD_PERENNIAL_RYEGRASS',
  CARD_COMMON_DAISY = 'CARD_COMMON_DAISY',
  CARD_SPEARMINT = 'CARD_SPEARMINT',
  CARD_HIBISCUS = 'CARD_HIBISCUS',
  CARD_SWEET_BRIAR = 'CARD_SWEET_BRIAR',
  CARD_GARDEN_STRAWBERRY = 'CARD_GARDEN_STRAWBERRY',
  CARD_COMMON_SUNFLOWER = 'CARD_COMMON_SUNFLOWER',
  CARD_GARDEN_TULIP = 'CARD_GARDEN_TULIP',
  CARD_WHITE_CLOVER = 'CARD_WHITE_CLOVER',
  CARD_EELGRASS = 'CARD_EELGRASS',
  CARD_CORN_MAIZE = 'CARD_CORN_MAIZE',
  CARD_RICE = 'CARD_RICE',

  // Additional Primary Consumers (Herbivores)
  CARD_NORTH_AMERICAN_BEAVER = 'CARD_NORTH_AMERICAN_BEAVER',
  CARD_AMERICAN_BISON = 'CARD_AMERICAN_BISON',
  CARD_WHITE_TAILED_DEER = 'CARD_WHITE_TAILED_DEER',
  CARD_EASTERN_CHIPMUNK = 'CARD_EASTERN_CHIPMUNK',
  CARD_DOMESTIC_CATTLE = 'CARD_DOMESTIC_CATTLE',
  CARD_DOMESTIC_GOAT = 'CARD_DOMESTIC_GOAT',
  CARD_GOLDEN_HAMSTER = 'CARD_GOLDEN_HAMSTER',
  CARD_EUROPEAN_HEDGEHOG = 'CARD_EUROPEAN_HEDGEHOG',
  CARD_DOMESTIC_HORSE = 'CARD_DOMESTIC_HORSE',
  CARD_KOALA = 'CARD_KOALA',
  CARD_LLAMA = 'CARD_LLAMA',
  CARD_HOUSE_MOUSE = 'CARD_HOUSE_MOUSE',
  CARD_OX = 'CARD_OX',
  CARD_GIANT_PANDA = 'CARD_GIANT_PANDA',
  CARD_DOMESTIC_PIG = 'CARD_DOMESTIC_PIG',
  CARD_COMMON_RACCOON = 'CARD_COMMON_RACCOON',
  CARD_BIGHORN_SHEEP = 'CARD_BIGHORN_SHEEP',
  CARD_WHITE_RHINOCEROS = 'CARD_WHITE_RHINOCEROS',
  CARD_ASIAN_WATER_BUFFALO = 'CARD_ASIAN_WATER_BUFFALO',
  CARD_PLAINS_ZEBRA = 'CARD_PLAINS_ZEBRA',
  CARD_GIRAFFE = 'CARD_GIRAFFE',
  CARD_AFRICAN_BUSH_ELEPHANT = 'CARD_AFRICAN_BUSH_ELEPHANT',
  CARD_DROMEDARY_CAMEL = 'CARD_DROMEDARY_CAMEL',
  CARD_WOOLLY_MAMMOTH = 'CARD_WOOLLY_MAMMOTH',

  // Additional Secondary/Tertiary Consumers (Carnivores and Omnivores)
  CARD_WILD_BOAR = 'CARD_WILD_BOAR',
  CARD_DOMESTIC_CAT = 'CARD_DOMESTIC_CAT',
  CARD_DOMESTIC_DOG = 'CARD_DOMESTIC_DOG',
  CARD_RED_FOX = 'CARD_RED_FOX',
  CARD_LEOPARD = 'CARD_LEOPARD',
  CARD_AFRICAN_LION = 'CARD_AFRICAN_LION',
  CARD_MOUNTAIN_GORILLA = 'CARD_MOUNTAIN_GORILLA',
  CARD_COMMON_CHIMPANZEE = 'CARD_COMMON_CHIMPANZEE',
  CARD_BORNEAN_ORANGUTAN = 'CARD_BORNEAN_ORANGUTAN',
  CARD_TIGER = 'CARD_TIGER',
  CARD_GRAY_WOLF = 'CARD_GRAY_WOLF',
  CARD_COMMON_HIPPOPOTAMUS = 'CARD_COMMON_HIPPOPOTAMUS',

  // Additional Invertebrates and Small Animals
  CARD_RED_WOOD_ANT = 'CARD_RED_WOOD_ANT',
  CARD_MONARCH_BUTTERFLY = 'CARD_MONARCH_BUTTERFLY',
  CARD_MONARCH_CATERPILLAR = 'CARD_MONARCH_CATERPILLAR',
  CARD_BUTTERFLY_EGG = 'CARD_BUTTERFLY_EGG',
  CARD_HOUSE_CRICKET = 'CARD_HOUSE_CRICKET',
  CARD_SACRED_DUNG_BEETLE = 'CARD_SACRED_DUNG_BEETLE',
  CARD_DESERT_HAIRY_SCORPION = 'CARD_DESERT_HAIRY_SCORPION',
  CARD_ROMAN_SNAIL = 'CARD_ROMAN_SNAIL',
  CARD_GARDEN_SPIDER = 'CARD_GARDEN_SPIDER',

  // Additional Decomposers
  CARD_COMMON_DECOMPOSER = 'CARD_COMMON_DECOMPOSER',

  // Reptiles and Amphibians
  CARD_DESERT_LIZARD = 'CARD_DESERT_LIZARD',
  CARD_BALL_PYTHON = 'CARD_BALL_PYTHON',
  CARD_COMMON_FROG = 'CARD_COMMON_FROG',
  CARD_GREEN_SEA_TURTLE = 'CARD_GREEN_SEA_TURTLE'
}

/**
 * Scientific Name IDs - Used for scientific names (universal but may need alphabet conversion)
 */
export enum ScientificNameId {
  // Producers
  SCIENTIFIC_QUERCUS_ROBUR = 'SCIENTIFIC_QUERCUS_ROBUR',
  SCIENTIFIC_MACROCYSTIS_PYRIFERA = 'SCIENTIFIC_MACROCYSTIS_PYRIFERA',
  SCIENTIFIC_PHALARIS_ARUNDINACEA = 'SCIENTIFIC_PHALARIS_ARUNDINACEA',
  SCIENTIFIC_PHYTOPLANKTON_MIXED = 'SCIENTIFIC_PHYTOPLANKTON_MIXED',

  // Chemoautotrophs
  SCIENTIFIC_THERMOTOGA_MARITIMA = 'SCIENTIFIC_THERMOTOGA_MARITIMA',
  SCIENTIFIC_ACIDITHIOBACILLUS_FERROOXIDANS = 'SCIENTIFIC_ACIDITHIOBACILLUS_FERROOXIDANS',
  SCIENTIFIC_PYROCOCCUS_FURIOSUS = 'SCIENTIFIC_PYROCOCCUS_FURIOSUS',
  SCIENTIFIC_NITROSOMONAS_EUROPAEA = 'SCIENTIFIC_NITROSOMONAS_EUROPAEA',
  SCIENTIFIC_BEGGIATOA_ALBA = 'SCIENTIFIC_BEGGIATOA_ALBA',

  // Primary Consumers
  SCIENTIFIC_ORYCTOLAGUS_CUNICULUS = 'SCIENTIFIC_ORYCTOLAGUS_CUNICULUS',
  SCIENTIFIC_ONCORHYNCHUS_NERKA = 'SCIENTIFIC_ONCORHYNCHUS_NERKA',
  SCIENTIFIC_EUPHAUSIA_PACIFICA = 'SCIENTIFIC_EUPHAUSIA_PACIFICA',
  SCIENTIFIC_ZOOPLANKTON_MIXED = 'SCIENTIFIC_ZOOPLANKTON_MIXED',
  SCIENTIFIC_APIS_MELLIFERA = 'SCIENTIFIC_APIS_MELLIFERA',

  // Secondary/Tertiary Consumers
  SCIENTIFIC_URSUS_AMERICANUS = 'SCIENTIFIC_URSUS_AMERICANUS',
  SCIENTIFIC_CARCHARODON_CARCHARIAS = 'SCIENTIFIC_CARCHARODON_CARCHARIAS',

  // Decomposers
  SCIENTIFIC_MYCENA_GALERICULATA = 'SCIENTIFIC_MYCENA_GALERICULATA',
  SCIENTIFIC_CATHARTES_AURA = 'SCIENTIFIC_CATHARTES_AURA',
  SCIENTIFIC_BACILLUS_SUBTILIS = 'SCIENTIFIC_BACILLUS_SUBTILIS',
  SCIENTIFIC_AGARICUS_BISPORUS = 'SCIENTIFIC_AGARICUS_BISPORUS',

  // Detritivores
  SCIENTIFIC_LUMBRICUS_TERRESTRIS = 'SCIENTIFIC_LUMBRICUS_TERRESTRIS',
  SCIENTIFIC_SCARABAEUS_LATICOLLIS = 'SCIENTIFIC_SCARABAEUS_LATICOLLIS',

  // Parasites
  SCIENTIFIC_IXODES_SCAPULARIS = 'SCIENTIFIC_IXODES_SCAPULARIS',

  // Mutualists
  SCIENTIFIC_GLOMUS_INTRARADICES = 'SCIENTIFIC_GLOMUS_INTRARADICES',
  SCIENTIFIC_RHIZOBIUM_LEGUMINOSARUM = 'SCIENTIFIC_RHIZOBIUM_LEGUMINOSARUM',

  // Additional Producers (Trees and Plants)
  SCIENTIFIC_MALUS_PUMILA = 'SCIENTIFIC_MALUS_PUMILA',
  SCIENTIFIC_QUERCUS_ROBUR_ENGLISH = 'SCIENTIFIC_QUERCUS_ROBUR_ENGLISH',
  SCIENTIFIC_PINUS_SYLVESTRIS = 'SCIENTIFIC_PINUS_SYLVESTRIS',
  SCIENTIFIC_COCOS_NUCIFERA = 'SCIENTIFIC_COCOS_NUCIFERA',
  SCIENTIFIC_PRUNUS_SERRULATA = 'SCIENTIFIC_PRUNUS_SERRULATA',
  SCIENTIFIC_PRUNUS_PUMILA = 'SCIENTIFIC_PRUNUS_PUMILA',
  SCIENTIFIC_OPUNTIA_FICUS_INDICA = 'SCIENTIFIC_OPUNTIA_FICUS_INDICA',
  SCIENTIFIC_VITIS_VINIFERA = 'SCIENTIFIC_VITIS_VINIFERA',
  SCIENTIFIC_LOLIUM_PERENNE = 'SCIENTIFIC_LOLIUM_PERENNE',
  SCIENTIFIC_BELLIS_PERENNIS = 'SCIENTIFIC_BELLIS_PERENNIS',
  SCIENTIFIC_MENTHA_SPICATA = 'SCIENTIFIC_MENTHA_SPICATA',
  SCIENTIFIC_HIBISCUS_ROSA_SINENSIS = 'SCIENTIFIC_HIBISCUS_ROSA_SINENSIS',
  SCIENTIFIC_ROSA_RUBIGINOSA = 'SCIENTIFIC_ROSA_RUBIGINOSA',
  SCIENTIFIC_FRAGARIA_ANANASSA = 'SCIENTIFIC_FRAGARIA_ANANASSA',
  SCIENTIFIC_HELIANTHUS_ANNUUS = 'SCIENTIFIC_HELIANTHUS_ANNUUS',
  SCIENTIFIC_TULIPA_GESNERIANA = 'SCIENTIFIC_TULIPA_GESNERIANA',
  SCIENTIFIC_TRIFOLIUM_REPENS = 'SCIENTIFIC_TRIFOLIUM_REPENS',
  SCIENTIFIC_ZOSTERA_MARINA = 'SCIENTIFIC_ZOSTERA_MARINA',
  SCIENTIFIC_ZEA_MAYS = 'SCIENTIFIC_ZEA_MAYS',
  SCIENTIFIC_ORYZA_SATIVA = 'SCIENTIFIC_ORYZA_SATIVA',

  // Additional Primary Consumers (Herbivores)
  SCIENTIFIC_CASTOR_CANADENSIS = 'SCIENTIFIC_CASTOR_CANADENSIS',
  SCIENTIFIC_BISON_BISON = 'SCIENTIFIC_BISON_BISON',
  SCIENTIFIC_ODOCOILEUS_VIRGINIANUS = 'SCIENTIFIC_ODOCOILEUS_VIRGINIANUS',
  SCIENTIFIC_TAMIAS_STRIATUS = 'SCIENTIFIC_TAMIAS_STRIATUS',
  SCIENTIFIC_BOS_TAURUS = 'SCIENTIFIC_BOS_TAURUS',
  SCIENTIFIC_CAPRA_AEGAGRUS_HIRCUS = 'SCIENTIFIC_CAPRA_AEGAGRUS_HIRCUS',
  SCIENTIFIC_MESOCRICETUS_AURATUS = 'SCIENTIFIC_MESOCRICETUS_AURATUS',
  SCIENTIFIC_ERINACEUS_EUROPAEUS = 'SCIENTIFIC_ERINACEUS_EUROPAEUS',
  SCIENTIFIC_EQUUS_CABALLUS = 'SCIENTIFIC_EQUUS_CABALLUS',
  SCIENTIFIC_PHASCOLARCTOS_CINEREUS = 'SCIENTIFIC_PHASCOLARCTOS_CINEREUS',
  SCIENTIFIC_LAMA_GLAMA = 'SCIENTIFIC_LAMA_GLAMA',
  SCIENTIFIC_MUS_MUSCULUS = 'SCIENTIFIC_MUS_MUSCULUS',
  SCIENTIFIC_BOS_TAURUS_OX = 'SCIENTIFIC_BOS_TAURUS_OX',
  SCIENTIFIC_AILUROPODA_MELANOLEUCA = 'SCIENTIFIC_AILUROPODA_MELANOLEUCA',
  SCIENTIFIC_SUS_SCROFA_DOMESTICUS = 'SCIENTIFIC_SUS_SCROFA_DOMESTICUS',
  SCIENTIFIC_PROCYON_LOTOR = 'SCIENTIFIC_PROCYON_LOTOR',
  SCIENTIFIC_OVIS_CANADENSIS = 'SCIENTIFIC_OVIS_CANADENSIS',
  SCIENTIFIC_CERATOTHERIUM_SIMUM = 'SCIENTIFIC_CERATOTHERIUM_SIMUM',
  SCIENTIFIC_BUBALUS_BUBALIS = 'SCIENTIFIC_BUBALUS_BUBALIS',
  SCIENTIFIC_EQUUS_QUAGGA = 'SCIENTIFIC_EQUUS_QUAGGA',
  SCIENTIFIC_GIRAFFA_CAMELOPARDALIS = 'SCIENTIFIC_GIRAFFA_CAMELOPARDALIS',
  SCIENTIFIC_LOXODONTA_AFRICANA = 'SCIENTIFIC_LOXODONTA_AFRICANA',
  SCIENTIFIC_CAMELUS_DROMEDARIUS = 'SCIENTIFIC_CAMELUS_DROMEDARIUS',
  SCIENTIFIC_MAMMUTHUS_PRIMIGENIUS = 'SCIENTIFIC_MAMMUTHUS_PRIMIGENIUS',

  // Additional Secondary/Tertiary Consumers (Carnivores and Omnivores)
  SCIENTIFIC_SUS_SCROFA = 'SCIENTIFIC_SUS_SCROFA',
  SCIENTIFIC_FELIS_CATUS = 'SCIENTIFIC_FELIS_CATUS',
  SCIENTIFIC_CANIS_LUPUS_FAMILIARIS = 'SCIENTIFIC_CANIS_LUPUS_FAMILIARIS',
  SCIENTIFIC_VULPES_VULPES = 'SCIENTIFIC_VULPES_VULPES',
  SCIENTIFIC_PANTHERA_PARDUS = 'SCIENTIFIC_PANTHERA_PARDUS',
  SCIENTIFIC_PANTHERA_LEO = 'SCIENTIFIC_PANTHERA_LEO',
  SCIENTIFIC_GORILLA_BERINGEI_BERINGEI = 'SCIENTIFIC_GORILLA_BERINGEI_BERINGEI',
  SCIENTIFIC_PAN_TROGLODYTES = 'SCIENTIFIC_PAN_TROGLODYTES',
  SCIENTIFIC_PONGO_PYGMAEUS = 'SCIENTIFIC_PONGO_PYGMAEUS',
  SCIENTIFIC_PANTHERA_TIGRIS = 'SCIENTIFIC_PANTHERA_TIGRIS',
  SCIENTIFIC_CANIS_LUPUS = 'SCIENTIFIC_CANIS_LUPUS',
  SCIENTIFIC_HIPPOPOTAMUS_AMPHIBIUS = 'SCIENTIFIC_HIPPOPOTAMUS_AMPHIBIUS',

  // Additional Invertebrates and Small Animals
  SCIENTIFIC_FORMICA_RUFA = 'SCIENTIFIC_FORMICA_RUFA',
  SCIENTIFIC_DANAUS_PLEXIPPUS_ADULT = 'SCIENTIFIC_DANAUS_PLEXIPPUS_ADULT',
  SCIENTIFIC_DANAUS_PLEXIPPUS_LARVA = 'SCIENTIFIC_DANAUS_PLEXIPPUS_LARVA',
  SCIENTIFIC_DANAUS_PLEXIPPUS_OVUM = 'SCIENTIFIC_DANAUS_PLEXIPPUS_OVUM',
  SCIENTIFIC_ACHETA_DOMESTICUS = 'SCIENTIFIC_ACHETA_DOMESTICUS',
  SCIENTIFIC_SCARABAEUS_SACER = 'SCIENTIFIC_SCARABAEUS_SACER',
  SCIENTIFIC_HADRURUS_ARIZONENSIS = 'SCIENTIFIC_HADRURUS_ARIZONENSIS',
  SCIENTIFIC_HELIX_POMATIA = 'SCIENTIFIC_HELIX_POMATIA',
  SCIENTIFIC_ARANEUS_DIADEMATUS = 'SCIENTIFIC_ARANEUS_DIADEMATUS',

  // Additional Decomposers
  SCIENTIFIC_AGARICUS_BISPORUS_DECOMPOSER = 'SCIENTIFIC_AGARICUS_BISPORUS_DECOMPOSER',

  // Reptiles and Amphibians
  SCIENTIFIC_LACERTA_DESERTI = 'SCIENTIFIC_LACERTA_DESERTI',
  SCIENTIFIC_PYTHON_REGIUS = 'SCIENTIFIC_PYTHON_REGIUS',
  SCIENTIFIC_RANA_TEMPORARIA = 'SCIENTIFIC_RANA_TEMPORARIA',
  SCIENTIFIC_CHELONIA_MYDAS = 'SCIENTIFIC_CHELONIA_MYDAS'
}

/**
 * Card Description IDs - Used for card flavor text and descriptions
 */
export enum CardDescriptionId {
  // Producers
  DESC_OAK_TREE = 'DESC_OAK_TREE',
  DESC_GIANT_KELP = 'DESC_GIANT_KELP',
  DESC_REED_CANARY_GRASS = 'DESC_REED_CANARY_GRASS',
  DESC_PHYTOPLANKTON = 'DESC_PHYTOPLANKTON',

  // Chemoautotrophs
  DESC_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA = 'DESC_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA',
  DESC_IRON_SPRING_BACTERIA = 'DESC_IRON_SPRING_BACTERIA',
  DESC_VOLCANIC_HYDROGEN_BACTERIA = 'DESC_VOLCANIC_HYDROGEN_BACTERIA',
  DESC_NITRIFYING_SOIL_BACTERIA = 'DESC_NITRIFYING_SOIL_BACTERIA',
  DESC_SEDIMENT_CHEMOSYNTHETIC_BACTERIA = 'DESC_SEDIMENT_CHEMOSYNTHETIC_BACTERIA',

  // Primary Consumers
  DESC_EUROPEAN_RABBIT = 'DESC_EUROPEAN_RABBIT',
  DESC_SOCKEYE_SALMON = 'DESC_SOCKEYE_SALMON',
  DESC_PACIFIC_KRILL = 'DESC_PACIFIC_KRILL',
  DESC_ZOOPLANKTON = 'DESC_ZOOPLANKTON',
  DESC_EUROPEAN_HONEY_BEE = 'DESC_EUROPEAN_HONEY_BEE',

  // Secondary/Tertiary Consumers
  DESC_AMERICAN_BLACK_BEAR = 'DESC_AMERICAN_BLACK_BEAR',
  DESC_GREAT_WHITE_SHARK = 'DESC_GREAT_WHITE_SHARK',

  // Decomposers
  DESC_MYCENA_MUSHROOM = 'DESC_MYCENA_MUSHROOM',
  DESC_TURKEY_VULTURE = 'DESC_TURKEY_VULTURE',
  DESC_SOIL_BACTERIA = 'DESC_SOIL_BACTERIA',
  DESC_DECOMPOSER_MUSHROOM = 'DESC_DECOMPOSER_MUSHROOM',

  // Detritivores
  DESC_COMMON_EARTHWORM = 'DESC_COMMON_EARTHWORM',
  DESC_DUNG_BEETLE = 'DESC_DUNG_BEETLE',

  // Parasites
  DESC_DEER_TICK = 'DESC_DEER_TICK',

  // Mutualists
  DESC_MYCORRHIZAL_FUNGI = 'DESC_MYCORRHIZAL_FUNGI',
  DESC_NITROGEN_FIXING_BACTERIA = 'DESC_NITROGEN_FIXING_BACTERIA',

  // Additional Producers (Trees and Plants)
  DESC_APPLE_TREE = 'DESC_APPLE_TREE',
  DESC_ENGLISH_OAK = 'DESC_ENGLISH_OAK',
  DESC_SCOTS_PINE = 'DESC_SCOTS_PINE',
  DESC_COCONUT_PALM = 'DESC_COCONUT_PALM',
  DESC_CHERRY_BLOSSOM = 'DESC_CHERRY_BLOSSOM',
  DESC_BUSH_CHERRY = 'DESC_BUSH_CHERRY',
  DESC_PRICKLY_PEAR_CACTUS = 'DESC_PRICKLY_PEAR_CACTUS',
  DESC_COMMON_GRAPE_VINE = 'DESC_COMMON_GRAPE_VINE',
  DESC_PERENNIAL_RYEGRASS = 'DESC_PERENNIAL_RYEGRASS',
  DESC_COMMON_DAISY = 'DESC_COMMON_DAISY',
  DESC_SPEARMINT = 'DESC_SPEARMINT',
  DESC_HIBISCUS = 'DESC_HIBISCUS',
  DESC_SWEET_BRIAR = 'DESC_SWEET_BRIAR',
  DESC_GARDEN_STRAWBERRY = 'DESC_GARDEN_STRAWBERRY',
  DESC_COMMON_SUNFLOWER = 'DESC_COMMON_SUNFLOWER',
  DESC_GARDEN_TULIP = 'DESC_GARDEN_TULIP',
  DESC_WHITE_CLOVER = 'DESC_WHITE_CLOVER',
  DESC_EELGRASS = 'DESC_EELGRASS',
  DESC_CORN_MAIZE = 'DESC_CORN_MAIZE',
  DESC_RICE = 'DESC_RICE',

  // Additional Primary Consumers (Herbivores)
  DESC_NORTH_AMERICAN_BEAVER = 'DESC_NORTH_AMERICAN_BEAVER',
  DESC_AMERICAN_BISON = 'DESC_AMERICAN_BISON',
  DESC_WHITE_TAILED_DEER = 'DESC_WHITE_TAILED_DEER',
  DESC_EASTERN_CHIPMUNK = 'DESC_EASTERN_CHIPMUNK',
  DESC_DOMESTIC_CATTLE = 'DESC_DOMESTIC_CATTLE',
  DESC_DOMESTIC_GOAT = 'DESC_DOMESTIC_GOAT',
  DESC_GOLDEN_HAMSTER = 'DESC_GOLDEN_HAMSTER',
  DESC_EUROPEAN_HEDGEHOG = 'DESC_EUROPEAN_HEDGEHOG',
  DESC_DOMESTIC_HORSE = 'DESC_DOMESTIC_HORSE',
  DESC_KOALA = 'DESC_KOALA',
  DESC_LLAMA = 'DESC_LLAMA',
  DESC_HOUSE_MOUSE = 'DESC_HOUSE_MOUSE',
  DESC_OX = 'DESC_OX',
  DESC_GIANT_PANDA = 'DESC_GIANT_PANDA',
  DESC_DOMESTIC_PIG = 'DESC_DOMESTIC_PIG',
  DESC_COMMON_RACCOON = 'DESC_COMMON_RACCOON',
  DESC_BIGHORN_SHEEP = 'DESC_BIGHORN_SHEEP',
  DESC_WHITE_RHINOCEROS = 'DESC_WHITE_RHINOCEROS',
  DESC_ASIAN_WATER_BUFFALO = 'DESC_ASIAN_WATER_BUFFALO',
  DESC_PLAINS_ZEBRA = 'DESC_PLAINS_ZEBRA',
  DESC_GIRAFFE = 'DESC_GIRAFFE',
  DESC_AFRICAN_BUSH_ELEPHANT = 'DESC_AFRICAN_BUSH_ELEPHANT',
  DESC_DROMEDARY_CAMEL = 'DESC_DROMEDARY_CAMEL',
  DESC_WOOLLY_MAMMOTH = 'DESC_WOOLLY_MAMMOTH',

  // Additional Secondary/Tertiary Consumers (Carnivores and Omnivores)
  DESC_WILD_BOAR = 'DESC_WILD_BOAR',
  DESC_DOMESTIC_CAT = 'DESC_DOMESTIC_CAT',
  DESC_DOMESTIC_DOG = 'DESC_DOMESTIC_DOG',
  DESC_RED_FOX = 'DESC_RED_FOX',
  DESC_LEOPARD = 'DESC_LEOPARD',
  DESC_AFRICAN_LION = 'DESC_AFRICAN_LION',
  DESC_MOUNTAIN_GORILLA = 'DESC_MOUNTAIN_GORILLA',
  DESC_COMMON_CHIMPANZEE = 'DESC_COMMON_CHIMPANZEE',
  DESC_BORNEAN_ORANGUTAN = 'DESC_BORNEAN_ORANGUTAN',
  DESC_TIGER = 'DESC_TIGER',
  DESC_GRAY_WOLF = 'DESC_GRAY_WOLF',
  DESC_COMMON_HIPPOPOTAMUS = 'DESC_COMMON_HIPPOPOTAMUS',

  // Additional Invertebrates and Small Animals
  DESC_RED_WOOD_ANT = 'DESC_RED_WOOD_ANT',
  DESC_MONARCH_BUTTERFLY = 'DESC_MONARCH_BUTTERFLY',
  DESC_MONARCH_CATERPILLAR = 'DESC_MONARCH_CATERPILLAR',
  DESC_BUTTERFLY_EGG = 'DESC_BUTTERFLY_EGG',
  DESC_HOUSE_CRICKET = 'DESC_HOUSE_CRICKET',
  DESC_SACRED_DUNG_BEETLE = 'DESC_SACRED_DUNG_BEETLE',
  DESC_DESERT_HAIRY_SCORPION = 'DESC_DESERT_HAIRY_SCORPION',
  DESC_ROMAN_SNAIL = 'DESC_ROMAN_SNAIL',
  DESC_GARDEN_SPIDER = 'DESC_GARDEN_SPIDER',

  // Additional Decomposers
  DESC_COMMON_DECOMPOSER = 'DESC_COMMON_DECOMPOSER',

  // Reptiles and Amphibians
  DESC_DESERT_LIZARD = 'DESC_DESERT_LIZARD',
  DESC_BALL_PYTHON = 'DESC_BALL_PYTHON',
  DESC_COMMON_FROG = 'DESC_COMMON_FROG',
  DESC_GREEN_SEA_TURTLE = 'DESC_GREEN_SEA_TURTLE'
}

// ============================================================================
// ABILITY TEXT IDS
// ============================================================================

/**
 * Ability Name IDs - Used for ability names
 */
export enum AbilityNameId {
  ABILITY_WATERSHED_PREDATOR = 'ABILITY_WATERSHED_PREDATOR',
  ABILITY_APEX_PREDATOR = 'ABILITY_APEX_PREDATOR',
  ABILITY_SCAVENGE = 'ABILITY_SCAVENGE',
  ABILITY_PARASITIC_DRAIN = 'ABILITY_PARASITIC_DRAIN',
  ABILITY_RECYCLER = 'ABILITY_RECYCLER',
  ABILITY_PHOTOSYNTHESIS = 'ABILITY_PHOTOSYNTHESIS',
  ABILITY_PACK_HUNTER = 'ABILITY_PACK_HUNTER',
  ABILITY_FILTER_FEEDER = 'ABILITY_FILTER_FEEDER',
  ABILITY_METAMORPHOSIS = 'ABILITY_METAMORPHOSIS',
  ABILITY_DECOMPOSER = 'ABILITY_DECOMPOSER',
  ABILITY_VENOMOUS = 'ABILITY_VENOMOUS',
  ABILITY_FRUGIVORE = 'ABILITY_FRUGIVORE',
  ABILITY_INSECTIVORE = 'ABILITY_INSECTIVORE',
  ABILITY_HYPERCARNIVORE = 'ABILITY_HYPERCARNIVORE',
  ABILITY_MIGRATORY = 'ABILITY_MIGRATORY',
  ABILITY_CHEMICAL_OPPORTUNIST = 'ABILITY_CHEMICAL_OPPORTUNIST',
  ABILITY_DETRITAL_PROCESSOR = 'ABILITY_DETRITAL_PROCESSOR'
}

/**
 * Ability Description IDs - Used for ability descriptions and rules text
 */
export enum AbilityDescriptionId {
  DESC_WATERSHED_PREDATOR = 'DESC_WATERSHED_PREDATOR',
  DESC_APEX_PREDATOR = 'DESC_APEX_PREDATOR',
  DESC_SCAVENGE = 'DESC_SCAVENGE',
  DESC_PARASITIC_DRAIN = 'DESC_PARASITIC_DRAIN',
  DESC_RECYCLER = 'DESC_RECYCLER',
  DESC_PHOTOSYNTHESIS = 'DESC_PHOTOSYNTHESIS',
  DESC_PACK_HUNTER = 'DESC_PACK_HUNTER',
  DESC_FILTER_FEEDER = 'DESC_FILTER_FEEDER',
  DESC_METAMORPHOSIS = 'DESC_METAMORPHOSIS',
  DESC_DECOMPOSER = 'DESC_DECOMPOSER',
  DESC_VENOMOUS = 'DESC_VENOMOUS',
  DESC_FRUGIVORE = 'DESC_FRUGIVORE',
  DESC_INSECTIVORE = 'DESC_INSECTIVORE',
  DESC_HYPERCARNIVORE = 'DESC_HYPERCARNIVORE',
  DESC_MIGRATORY = 'DESC_MIGRATORY',
  DESC_CHEMICAL_OPPORTUNIST = 'DESC_CHEMICAL_OPPORTUNIST',
  DESC_DETRITAL_PROCESSOR = 'DESC_DETRITAL_PROCESSOR'
}

// ============================================================================
// KEYWORD TEXT IDS
// ============================================================================

/**
 * Keyword Name IDs - Used for keyword names
 */
export enum KeywordNameId {
  // Domain Keywords
  KEYWORD_TERRESTRIAL = 'KEYWORD_TERRESTRIAL',
  KEYWORD_AQUATIC = 'KEYWORD_AQUATIC',
  KEYWORD_AMPHIBIOUS = 'KEYWORD_AMPHIBIOUS',
  KEYWORD_FRESHWATER = 'KEYWORD_FRESHWATER',
  KEYWORD_MARINE = 'KEYWORD_MARINE',
  KEYWORD_EURYHALINE = 'KEYWORD_EURYHALINE',

  // Habitat Keywords
  KEYWORD_FOREST = 'KEYWORD_FOREST',
  KEYWORD_RIVER = 'KEYWORD_RIVER',
  KEYWORD_OCEAN = 'KEYWORD_OCEAN',
  KEYWORD_DESERT = 'KEYWORD_DESERT',
  KEYWORD_GRASSLAND = 'KEYWORD_GRASSLAND',
  KEYWORD_WETLAND = 'KEYWORD_WETLAND',
  KEYWORD_MOUNTAIN = 'KEYWORD_MOUNTAIN',
  KEYWORD_ARCTIC = 'KEYWORD_ARCTIC',
  KEYWORD_TROPICAL = 'KEYWORD_TROPICAL',
  KEYWORD_TEMPERATE = 'KEYWORD_TEMPERATE',

  // Taxonomic Keywords
  KEYWORD_FISH = 'KEYWORD_FISH',
  KEYWORD_MAMMAL = 'KEYWORD_MAMMAL',
  KEYWORD_BIRD = 'KEYWORD_BIRD',
  KEYWORD_REPTILE = 'KEYWORD_REPTILE',
  KEYWORD_AMPHIBIAN = 'KEYWORD_AMPHIBIAN',
  KEYWORD_INSECT = 'KEYWORD_INSECT',
  KEYWORD_ARACHNID = 'KEYWORD_ARACHNID',
  KEYWORD_CRUSTACEAN = 'KEYWORD_CRUSTACEAN',
  KEYWORD_MOLLUSK = 'KEYWORD_MOLLUSK',
  KEYWORD_PLANT = 'KEYWORD_PLANT',
  KEYWORD_FUNGI = 'KEYWORD_FUNGI',
  KEYWORD_BACTERIA = 'KEYWORD_BACTERIA',
  KEYWORD_PROTIST = 'KEYWORD_PROTIST',
  KEYWORD_ARTHROPOD = 'KEYWORD_ARTHROPOD',

  // Behavioral Keywords
  KEYWORD_PACK_HUNTER = 'KEYWORD_PACK_HUNTER',
  KEYWORD_SOLITARY = 'KEYWORD_SOLITARY',
  KEYWORD_SOCIAL = 'KEYWORD_SOCIAL',
  KEYWORD_MIGRATORY = 'KEYWORD_MIGRATORY',
  KEYWORD_TERRITORIAL = 'KEYWORD_TERRITORIAL',
  KEYWORD_NOCTURNAL = 'KEYWORD_NOCTURNAL',
  KEYWORD_DIURNAL = 'KEYWORD_DIURNAL',
  KEYWORD_CREPUSCULAR = 'KEYWORD_CREPUSCULAR',

  // Special Abilities
  KEYWORD_VENOMOUS = 'KEYWORD_VENOMOUS',
  KEYWORD_POISONOUS = 'KEYWORD_POISONOUS',
  KEYWORD_SCAVENGE = 'KEYWORD_SCAVENGE',
  KEYWORD_HYPERCARNIVORE = 'KEYWORD_HYPERCARNIVORE',
  KEYWORD_WATERSHED_PREDATOR = 'KEYWORD_WATERSHED_PREDATOR',
  KEYWORD_PARASITIC_DRAIN = 'KEYWORD_PARASITIC_DRAIN',
  KEYWORD_RECYCLER = 'KEYWORD_RECYCLER',
  KEYWORD_APEX_PREDATOR = 'KEYWORD_APEX_PREDATOR',

  // Size Categories
  KEYWORD_MICROSCOPIC = 'KEYWORD_MICROSCOPIC',
  KEYWORD_TINY = 'KEYWORD_TINY',
  KEYWORD_SMALL = 'KEYWORD_SMALL',
  KEYWORD_MEDIUM = 'KEYWORD_MEDIUM',
  KEYWORD_LARGE = 'KEYWORD_LARGE',
  KEYWORD_HUGE = 'KEYWORD_HUGE',
  KEYWORD_GIGANTIC = 'KEYWORD_GIGANTIC'
}

// ============================================================================
// UI TEXT IDS
// ============================================================================

/**
 * UI Text IDs - Used for user interface elements
 */
export enum UITextId {
  // Game Actions
  UI_PLACE_CARD = 'UI_PLACE_CARD',
  UI_ACTIVATE_ABILITY = 'UI_ACTIVATE_ABILITY',
  UI_PASS_TURN = 'UI_PASS_TURN',
  UI_END_TURN = 'UI_END_TURN',

  // Game Phases
  UI_READY_PHASE = 'UI_READY_PHASE',
  UI_DRAW_PHASE = 'UI_DRAW_PHASE',
  UI_ACTION_PHASE = 'UI_ACTION_PHASE',

  // Game States
  UI_GAME_OVER = 'UI_GAME_OVER',
  UI_YOU_WIN = 'UI_YOU_WIN',
  UI_YOU_LOSE = 'UI_YOU_LOSE',
  UI_DRAW_GAME = 'UI_DRAW_GAME',

  // Error Messages
  UI_INVALID_ACTION = 'UI_INVALID_ACTION',
  UI_NOT_ENOUGH_ENERGY = 'UI_NOT_ENOUGH_ENERGY',
  UI_INVALID_TARGET = 'UI_INVALID_TARGET',
  UI_CARD_EXHAUSTED = 'UI_CARD_EXHAUSTED',
  UI_NO_VALID_TARGETS = 'UI_NO_VALID_TARGETS',
  UI_POSITION_OCCUPIED = 'UI_POSITION_OCCUPIED',
  UI_INVALID_PLACEMENT = 'UI_INVALID_PLACEMENT',

  // Game Terms
  UI_READY = 'UI_READY',
  UI_EXHAUSTED = 'UI_EXHAUSTED',
  UI_DETRITUS_ZONE = 'UI_DETRITUS_ZONE',
  UI_SCORE_PILE = 'UI_SCORE_PILE',
  UI_HAND = 'UI_HAND',
  UI_DECK = 'UI_DECK',
  UI_TROPHIC_LEVEL = 'UI_TROPHIC_LEVEL',
  UI_VICTORY_POINTS = 'UI_VICTORY_POINTS',
  UI_ENERGY = 'UI_ENERGY',
  UI_ENERGY_COST = 'UI_ENERGY_COST',
  UI_HOME_CARD = 'UI_HOME_CARD',
  UI_PRODUCTION_LOOP = 'UI_PRODUCTION_LOOP',
  UI_DECOMPOSITION_LOOP = 'UI_DECOMPOSITION_LOOP',

  // Authentication
  UI_CREATE_ACCOUNT = 'UI_CREATE_ACCOUNT',
  UI_WELCOME_BACK = 'UI_WELCOME_BACK',
  UI_JOIN_COMMUNITY = 'UI_JOIN_COMMUNITY',
  UI_SIGN_IN_ACCOUNT = 'UI_SIGN_IN_ACCOUNT',
  UI_DISPLAY_NAME = 'UI_DISPLAY_NAME',
  UI_EMAIL = 'UI_EMAIL',
  UI_PASSWORD = 'UI_PASSWORD',
  UI_ENTER_DISPLAY_NAME = 'UI_ENTER_DISPLAY_NAME',
  UI_ENTER_EMAIL = 'UI_ENTER_EMAIL',
  UI_ENTER_PASSWORD = 'UI_ENTER_PASSWORD',
  UI_REMEMBER_ME = 'UI_REMEMBER_ME',
  UI_FORGOT_PASSWORD = 'UI_FORGOT_PASSWORD',
  UI_PLEASE_WAIT = 'UI_PLEASE_WAIT',
  UI_SIGN_UP = 'UI_SIGN_UP',
  UI_SIGN_IN = 'UI_SIGN_IN',
  UI_CONTINUE_WITH_GOOGLE = 'UI_CONTINUE_WITH_GOOGLE',
  UI_CONTINUE_AS_GUEST = 'UI_CONTINUE_AS_GUEST',
  UI_ALREADY_HAVE_ACCOUNT = 'UI_ALREADY_HAVE_ACCOUNT',
  UI_DONT_HAVE_ACCOUNT = 'UI_DONT_HAVE_ACCOUNT',
  UI_CANCEL = 'UI_CANCEL',
  UI_OR = 'UI_OR',

  // Authentication Messages
  UI_FILL_REQUIRED_FIELDS = 'UI_FILL_REQUIRED_FIELDS',
  UI_ENTER_DISPLAY_NAME_MSG = 'UI_ENTER_DISPLAY_NAME_MSG',
  UI_ACCOUNT_CREATED = 'UI_ACCOUNT_CREATED',
  UI_SIGNED_IN_SUCCESS = 'UI_SIGNED_IN_SUCCESS',
  UI_CONVERTING_GUEST = 'UI_CONVERTING_GUEST',
  UI_CONVERSION_SUCCESS = 'UI_CONVERSION_SUCCESS',
  UI_CONVERSION_FAILED = 'UI_CONVERSION_FAILED',
  UI_ACCOUNT_CREATED_MERGE_FAILED = 'UI_ACCOUNT_CREATED_MERGE_FAILED',
  UI_AUTH_FAILED = 'UI_AUTH_FAILED',
  UI_GOOGLE_SIGNIN_SUCCESS = 'UI_GOOGLE_SIGNIN_SUCCESS',
  UI_GOOGLE_SIGNIN_FAILED = 'UI_GOOGLE_SIGNIN_FAILED',
  UI_GUEST_SIGNIN_SUCCESS = 'UI_GUEST_SIGNIN_SUCCESS',
  UI_GUEST_SIGNIN_FAILED = 'UI_GUEST_SIGNIN_FAILED',

  // Guest Registration
  UI_PROTECT_PROGRESS = 'UI_PROTECT_PROGRESS',
  UI_CREATE_FREE_ACCOUNT = 'UI_CREATE_FREE_ACCOUNT',
  UI_DONT_LOSE_CARDS = 'UI_DONT_LOSE_CARDS',
  UI_SAVE_SPECIES_CREDITS = 'UI_SAVE_SPECIES_CREDITS',
  UI_SECURE_COLLECTION = 'UI_SECURE_COLLECTION',
  UI_PROTECT_SPECIES_CARDS_CREDITS = 'UI_PROTECT_SPECIES_CARDS_CREDITS',

  // Battle UI
  UI_NOTICE = 'UI_NOTICE',
  UI_FORFEIT_MATCH = 'UI_FORFEIT_MATCH',
  UI_CAMPAIGN = 'UI_CAMPAIGN',
  UI_TUTORIAL = 'UI_TUTORIAL',
  UI_CAMPAIGN_LEVELS = 'UI_CAMPAIGN_LEVELS',
  UI_ECOSYSTEM_MASTERY_CAMPAIGN = 'UI_ECOSYSTEM_MASTERY_CAMPAIGN',
  UI_STORY_MODE_DESCRIPTION = 'UI_STORY_MODE_DESCRIPTION',
  UI_LEARN_PHYLO_BASICS = 'UI_LEARN_PHYLO_BASICS',
  UI_SINGLE_PLAYER = 'UI_SINGLE_PLAYER',
  UI_INTERACTIVE = 'UI_INTERACTIVE',
  UI_FORFEIT = 'UI_FORFEIT',
  UI_FORFEIT_CONFIRMATION = 'UI_FORFEIT_CONFIRMATION',
  UI_FORFEIT_SUCCESS = 'UI_FORFEIT_SUCCESS',
  UI_NEED_SPECIES_WARNING = 'UI_NEED_SPECIES_WARNING',
  UI_PROGRESS_DESCRIPTION = 'UI_PROGRESS_DESCRIPTION',
  UI_FOREST_ECOSYSTEM_BASICS = 'UI_FOREST_ECOSYSTEM_BASICS',
  UI_FOREST_DESCRIPTION = 'UI_FOREST_DESCRIPTION',
  UI_OCEAN_DEPTHS_CHALLENGE = 'UI_OCEAN_DEPTHS_CHALLENGE',
  UI_OCEAN_DESCRIPTION = 'UI_OCEAN_DESCRIPTION',
  UI_GRASSLAND_BALANCE = 'UI_GRASSLAND_BALANCE',
  UI_GRASSLAND_DESCRIPTION = 'UI_GRASSLAND_DESCRIPTION',
  UI_FOREST_STARTER_PACK = 'UI_FOREST_STARTER_PACK',
  UI_OCEAN_STARTER_PACK = 'UI_OCEAN_STARTER_PACK',
  UI_ECO_CREDITS = 'UI_ECO_CREDITS',
  UI_LEVEL_NOT_UNLOCKED = 'UI_LEVEL_NOT_UNLOCKED',
  UI_TUTORIAL_COMPLETED = 'UI_TUTORIAL_COMPLETED',

  // Collection UI
  UI_ENTER_DECK_NAME = 'UI_ENTER_DECK_NAME',
  UI_CONSERVATION_STATUS = 'UI_CONSERVATION_STATUS',
  UI_ALL_STATUS = 'UI_ALL_STATUS',
  UI_TROPHIC_ROLE = 'UI_TROPHIC_ROLE',
  UI_ALL_ROLES = 'UI_ALL_ROLES',
  UI_PRODUCER = 'UI_PRODUCER',
  UI_CARD_PROPERTIES = 'UI_CARD_PROPERTIES',
  UI_HABITAT = 'UI_HABITAT',
  UI_ACQUISITION_TYPE = 'UI_ACQUISITION_TYPE',

  // General UI
  UI_CLOSE = 'UI_CLOSE',
  UI_SAVE = 'UI_SAVE',
  UI_CONFIRM = 'UI_CONFIRM',
  UI_DELETE = 'UI_DELETE',
  UI_EDIT = 'UI_EDIT',
  UI_ADD = 'UI_ADD',
  UI_REMOVE = 'UI_REMOVE',
  UI_SEARCH = 'UI_SEARCH',
  UI_FILTER = 'UI_FILTER',
  UI_SORT = 'UI_SORT',
  UI_LOADING = 'UI_LOADING',
  UI_ERROR = 'UI_ERROR',
  UI_SUCCESS = 'UI_SUCCESS',
  UI_WARNING = 'UI_WARNING',
  UI_INFO = 'UI_INFO',
  UI_YES = 'UI_YES',
  UI_NO = 'UI_NO',
  UI_OK = 'UI_OK',
  UI_BACK = 'UI_BACK',
  UI_NEXT = 'UI_NEXT',
  UI_PREVIOUS = 'UI_PREVIOUS',
  UI_FINISH = 'UI_FINISH',
  UI_SKIP = 'UI_SKIP',
  UI_RETRY = 'UI_RETRY',
  UI_REFRESH = 'UI_REFRESH',
  UI_HOME = 'UI_HOME',
  UI_SETTINGS = 'UI_SETTINGS',
  UI_HELP = 'UI_HELP',
  UI_ABOUT = 'UI_ABOUT',
  UI_CONTACT = 'UI_CONTACT',
  UI_PRIVACY = 'UI_PRIVACY',
  UI_TERMS = 'UI_TERMS',
  UI_LANGUAGE = 'UI_LANGUAGE',
  UI_THEME = 'UI_THEME',
  UI_NOTIFICATIONS = 'UI_NOTIFICATIONS',
  UI_ACCOUNT = 'UI_ACCOUNT',
  UI_PROFILE = 'UI_PROFILE',
  UI_LOGOUT = 'UI_LOGOUT',
  UI_LOGIN = 'UI_LOGIN',
  UI_REGISTER = 'UI_REGISTER',

  // End Game UI
  UI_GAME_COMPLETE = 'UI_GAME_COMPLETE',
  UI_CONGRATULATIONS = 'UI_CONGRATULATIONS',
  UI_VICTORY = 'UI_VICTORY',
  UI_DEFEAT = 'UI_DEFEAT',
  UI_DRAW = 'UI_DRAW',
  UI_FINAL_SCORE = 'UI_FINAL_SCORE',
  UI_CARDS_PLAYED = 'UI_CARDS_PLAYED',
  UI_GAME_DURATION = 'UI_GAME_DURATION',
  UI_TOTAL_TURNS = 'UI_TOTAL_TURNS',
  UI_PLAY_AGAIN = 'UI_PLAY_AGAIN',
  UI_RETURN_HOME = 'UI_RETURN_HOME',
  UI_VIEW_COLLECTION = 'UI_VIEW_COLLECTION',
  UI_PLAYER_STATS = 'UI_PLAYER_STATS',
  UI_GAME_STATS = 'UI_GAME_STATS',
  UI_WELL_PLAYED = 'UI_WELL_PLAYED',
  UI_BETTER_LUCK_NEXT_TIME = 'UI_BETTER_LUCK_NEXT_TIME',
  UI_EXCELLENT_GAME = 'UI_EXCELLENT_GAME',
  UI_DECK_COUNT = 'UI_DECK_COUNT',
  UI_HAND_COUNT = 'UI_HAND_COUNT',

  // Connectivity UI
  UI_ONLINE = 'UI_ONLINE',
  UI_OFFLINE = 'UI_OFFLINE',
  UI_CONNECTING = 'UI_CONNECTING',
  UI_SYNCING = 'UI_SYNCING',
  UI_SYNC_COMPLETE = 'UI_SYNC_COMPLETE',
  UI_SYNC_FAILED = 'UI_SYNC_FAILED',
  UI_CONNECTION_LOST = 'UI_CONNECTION_LOST',
  UI_RECONNECTING = 'UI_RECONNECTING',
  UI_GUEST_MODE = 'UI_GUEST_MODE',
  UI_PENDING_ACTIONS = 'UI_PENDING_ACTIONS',
  UI_CLICK_TO_RETRY = 'UI_CLICK_TO_RETRY',

  // Home/Main Menu UI
  UI_BIOMASTERS_TCG = 'UI_BIOMASTERS_TCG',
  UI_INITIALIZING = 'UI_INITIALIZING',
  UI_INITIALIZE_COLLECTION = 'UI_INITIALIZE_COLLECTION',
  UI_INITIALIZE_DESCRIPTION = 'UI_INITIALIZE_DESCRIPTION',
  UI_INITIALIZE_BUTTON = 'UI_INITIALIZE_BUTTON',
  UI_YOUR_COLLECTION = 'UI_YOUR_COLLECTION',
  UI_SPECIES_OWNED = 'UI_SPECIES_OWNED',
  UI_TOTAL_CARDS = 'UI_TOTAL_CARDS',
  UI_PENDING_SYNC = 'UI_PENDING_SYNC',
  UI_GAME_ACTIONS = 'UI_GAME_ACTIONS',
  UI_BUILD_DECK = 'UI_BUILD_DECK',
  UI_START_BATTLE = 'UI_START_BATTLE',
  UI_NEED_SPECIES_BATTLE = 'UI_NEED_SPECIES_BATTLE',
  UI_OPEN_PACKS = 'UI_OPEN_PACKS',
  UI_SETTINGS_SYNC = 'UI_SETTINGS_SYNC',
  UI_MY_PROFILE = 'UI_MY_PROFILE',
  UI_GETTING_STARTED = 'UI_GETTING_STARTED',
  UI_WELCOME_INSTRUCTIONS = 'UI_WELCOME_INSTRUCTIONS',

  // Settings UI
  UI_LANGUAGE_SETTINGS = 'UI_LANGUAGE_SETTINGS',
  UI_THEME_SETTINGS = 'UI_THEME_SETTINGS',
  UI_DARK_MODE = 'UI_DARK_MODE',
  UI_ORGANISM_RENDER_MODE = 'UI_ORGANISM_RENDER_MODE',
  UI_GRID_CELL_STYLE = 'UI_GRID_CELL_STYLE',
  UI_CARD_VISUAL_STYLE = 'UI_CARD_VISUAL_STYLE',
  UI_CREATE_CUSTOM_THEME = 'UI_CREATE_CUSTOM_THEME',
  UI_GAME_SETTINGS = 'UI_GAME_SETTINGS',
  UI_SHOW_PROBABILITY = 'UI_SHOW_PROBABILITY',
  UI_PROBABILITY_DESCRIPTION = 'UI_PROBABILITY_DESCRIPTION',
  UI_EDUCATIONAL_TOOLTIPS = 'UI_EDUCATIONAL_TOOLTIPS',
  UI_TOOLTIPS_DESCRIPTION = 'UI_TOOLTIPS_DESCRIPTION',
  UI_AUTO_SAVE = 'UI_AUTO_SAVE',
  UI_AUTO_SAVE_DESCRIPTION = 'UI_AUTO_SAVE_DESCRIPTION',
  UI_PROFILE_MANAGEMENT = 'UI_PROFILE_MANAGEMENT',
  UI_USERNAME = 'UI_USERNAME',
  UI_THEME_NAME = 'UI_THEME_NAME',
  UI_BASE_THEME = 'UI_BASE_THEME',
  UI_CUSTOMIZE_COLORS = 'UI_CUSTOMIZE_COLORS',
  UI_PREVIEW = 'UI_PREVIEW',
  UI_CREATE_THEME = 'UI_CREATE_THEME',

  // Deck Builder UI
  UI_DECK_BUILDER = 'UI_DECK_BUILDER',
  UI_NEW_DECK = 'UI_NEW_DECK',
  UI_SAVED_DECKS = 'UI_SAVED_DECKS',
  UI_ACTIVE_DECK = 'UI_ACTIVE_DECK',
  UI_NO_SAVED_DECKS = 'UI_NO_SAVED_DECKS',
  UI_CREATE_FIRST_DECK = 'UI_CREATE_FIRST_DECK',
  UI_SET_ACTIVE = 'UI_SET_ACTIVE',
  UI_CREATE_NEW_DECK = 'UI_CREATE_NEW_DECK',
  UI_MAXIMUM_REACHED = 'UI_MAXIMUM_REACHED',
  UI_DUPLICATE = 'UI_DUPLICATE',
  UI_REMOVE_ALL = 'UI_REMOVE_ALL',
  UI_DECK_CARDS = 'UI_DECK_CARDS',
  UI_DECK_NAME_REQUIRED = 'UI_DECK_NAME_REQUIRED',
  UI_DECK_MIN_CARDS = 'UI_DECK_MIN_CARDS',
  UI_DECK_UPDATED = 'UI_DECK_UPDATED',
  UI_DECK_SAVED = 'UI_DECK_SAVED',
  UI_DECK_SAVE_FAILED = 'UI_DECK_SAVE_FAILED',
  UI_CARDS_COUNT = 'UI_CARDS_COUNT',
  UI_CREATED_DATE = 'UI_CREATED_DATE',

  // Tab Navigation
  UI_TAB_HOME = 'UI_TAB_HOME',
  UI_TAB_COLLECTION = 'UI_TAB_COLLECTION',
  UI_TAB_ONLINE = 'UI_TAB_ONLINE',
  UI_TAB_DECK_BUILDER = 'UI_TAB_DECK_BUILDER',
  UI_TAB_SETTINGS = 'UI_TAB_SETTINGS',

  // Pack Opening
  UI_EARN_CREDITS_DESCRIPTION = 'UI_EARN_CREDITS_DESCRIPTION',
  UI_STARTER_PACK = 'UI_STARTER_PACK',
  UI_STARTER_PACK_DESCRIPTION = 'UI_STARTER_PACK_DESCRIPTION',
  UI_BASIC_PACK = 'UI_BASIC_PACK',
  UI_BASIC_PACK_DESCRIPTION = 'UI_BASIC_PACK_DESCRIPTION',
  UI_PREMIUM_PACK = 'UI_PREMIUM_PACK',
  UI_PREMIUM_PACK_DESCRIPTION = 'UI_PREMIUM_PACK_DESCRIPTION',
  UI_LEGENDARY_PACK = 'UI_LEGENDARY_PACK',
  UI_LEGENDARY_PACK_DESCRIPTION = 'UI_LEGENDARY_PACK_DESCRIPTION',
  UI_CONSERVATION_PACK = 'UI_CONSERVATION_PACK',
  UI_CONSERVATION_PACK_DESCRIPTION = 'UI_CONSERVATION_PACK_DESCRIPTION',
  UI_CARDS = 'UI_CARDS',
  UI_CREDITS = 'UI_CREDITS',
  UI_FREE = 'UI_FREE',
  UI_OPENING = 'UI_OPENING',
  UI_OPEN_PACK = 'UI_OPEN_PACK',
  UI_NOT_AVAILABLE = 'UI_NOT_AVAILABLE',
  UI_SIGN_IN_REQUIRED = 'UI_SIGN_IN_REQUIRED',
  UI_SIGN_IN_TO_OPEN_PACKS = 'UI_SIGN_IN_TO_OPEN_PACKS',
  UI_GO_TO_SIGN_IN = 'UI_GO_TO_SIGN_IN',
  UI_COLLECTION_NOT_INITIALIZED = 'UI_COLLECTION_NOT_INITIALIZED',
  UI_COLLECTION_NEEDS_INIT = 'UI_COLLECTION_NEEDS_INIT',
  UI_GUEST_COLLECTION_NEEDS_INIT = 'UI_GUEST_COLLECTION_NEEDS_INIT',
  UI_GO_TO_HOME_TO_INITIALIZE = 'UI_GO_TO_HOME_TO_INITIALIZE',
  UI_PLEASE_SIGN_IN_FIRST = 'UI_PLEASE_SIGN_IN_FIRST',
  UI_PLEASE_INITIALIZE_COLLECTION = 'UI_PLEASE_INITIALIZE_COLLECTION',
  UI_NOT_ENOUGH_CREDITS = 'UI_NOT_ENOUGH_CREDITS',

  // Additional UI Text IDs for new features
  UI_SWITCH_THEMES = 'UI_SWITCH_THEMES',
  UI_CHOOSE_COLOR_SCHEME = 'UI_CHOOSE_COLOR_SCHEME',
  UI_CURRENT_THEME = 'UI_CURRENT_THEME',
  UI_CHOOSE_ORGANISM_DISPLAY = 'UI_CHOOSE_ORGANISM_DISPLAY',
  UI_2D_DOM_RENDERING = 'UI_2D_DOM_RENDERING',
  UI_PNG_SVG_IMAGES = 'UI_PNG_SVG_IMAGES',
  UI_2D_DOM_DESCRIPTION = 'UI_2D_DOM_DESCRIPTION',
  UI_PNG_SVG_DESCRIPTION = 'UI_PNG_SVG_DESCRIPTION',
  UI_CHOOSE_GRID_APPEARANCE = 'UI_CHOOSE_GRID_APPEARANCE',
  UI_CLASSIC = 'UI_CLASSIC',
  UI_HEXAGON = 'UI_HEXAGON',
  UI_ROUNDED = 'UI_ROUNDED',
  UI_NEON = 'UI_NEON',
  UI_ORGANIC = 'UI_ORGANIC',
  UI_CLASSIC_DESCRIPTION = 'UI_CLASSIC_DESCRIPTION',
  UI_HEXAGON_DESCRIPTION = 'UI_HEXAGON_DESCRIPTION',
  UI_ROUNDED_DESCRIPTION = 'UI_ROUNDED_DESCRIPTION',
  UI_NEON_DESCRIPTION = 'UI_NEON_DESCRIPTION',
  UI_ORGANIC_DESCRIPTION = 'UI_ORGANIC_DESCRIPTION',
  UI_CHOOSE_CARD_APPEARANCE = 'UI_CHOOSE_CARD_APPEARANCE',
  UI_COMPACT_INFO_CARD = 'UI_COMPACT_INFO_CARD',
  UI_MINIMALIST_VIEW = 'UI_MINIMALIST_VIEW',
  UI_DATA_FOCUSED_GRID = 'UI_DATA_FOCUSED_GRID',
  UI_CIRCULAR_DESIGN = 'UI_CIRCULAR_DESIGN',
  UI_COMPACT = 'UI_COMPACT',
  UI_DATA_GRID = 'UI_DATA_GRID',
  UI_CIRCULAR = 'UI_CIRCULAR',
  UI_COMPACT_DESCRIPTION = 'UI_COMPACT_DESCRIPTION',
  UI_DATA_GRID_DESCRIPTION = 'UI_DATA_GRID_DESCRIPTION',
  UI_CIRCULAR_DESCRIPTION = 'UI_CIRCULAR_DESCRIPTION',
  UI_HIGH_CONTRAST = 'UI_HIGH_CONTRAST',
  UI_INCREASE_CONTRAST = 'UI_INCREASE_CONTRAST',
  UI_SAVE_PROFILE = 'UI_SAVE_PROFILE',
  UI_SAVE_PROFILE_COMING_SOON = 'UI_SAVE_PROFILE_COMING_SOON',
  UI_PROFILE_EDITING_FUTURE = 'UI_PROFILE_EDITING_FUTURE',
  UI_ACCOUNT_TYPE = 'UI_ACCOUNT_TYPE',
  UI_GUEST_ACCOUNT = 'UI_GUEST_ACCOUNT',
  UI_REGISTERED_ACCOUNT = 'UI_REGISTERED_ACCOUNT',
  UI_NOT_SET = 'UI_NOT_SET',
  UI_DANGER_ZONE = 'UI_DANGER_ZONE',
  UI_DELETE_ACCOUNT = 'UI_DELETE_ACCOUNT',
  UI_DELETE_ACCOUNT_WARNING = 'UI_DELETE_ACCOUNT_WARNING',
  UI_ADMIN_TOOLS = 'UI_ADMIN_TOOLS',
  UI_GRANT_CURRENCY = 'UI_GRANT_CURRENCY',
  UI_GRANT_CURRENCY_DESCRIPTION = 'UI_GRANT_CURRENCY_DESCRIPTION',
  UI_USER_IDENTIFIER = 'UI_USER_IDENTIFIER',
  UI_USER_IDENTIFIER_PLACEHOLDER = 'UI_USER_IDENTIFIER_PLACEHOLDER',
  UI_CURRENCY_TYPE = 'UI_CURRENCY_TYPE',
  UI_GEMS = 'UI_GEMS',
  UI_COINS = 'UI_COINS',
  UI_DUST = 'UI_DUST',
  UI_AMOUNT = 'UI_AMOUNT',
  UI_REASON = 'UI_REASON',
  UI_REASON_PLACEHOLDER = 'UI_REASON_PLACEHOLDER',
  UI_GRANTING = 'UI_GRANTING',
  UI_GRANT_CURRENCY_BUTTON = 'UI_GRANT_CURRENCY_BUTTON',
  UI_GRANT_CARD = 'UI_GRANT_CARD',
  UI_GRANT_CARD_DESCRIPTION = 'UI_GRANT_CARD_DESCRIPTION',
  UI_CARD_ID = 'UI_CARD_ID',
  UI_QUANTITY = 'UI_QUANTITY',
  UI_GRANT_CARD_BUTTON = 'UI_GRANT_CARD_BUTTON',
  UI_CREATE_CUSTOM_THEME_TITLE = 'UI_CREATE_CUSTOM_THEME_TITLE',
  UI_ENTER_THEME_NAME = 'UI_ENTER_THEME_NAME',
  UI_COLOR_CUSTOMIZATION = 'UI_COLOR_CUSTOMIZATION',
  UI_THEME_PREVIEW_SECTION = 'UI_THEME_PREVIEW_SECTION',

  // Collection Page
  UI_LOADING_SPECIES_DATA = 'UI_LOADING_SPECIES_DATA',
  UI_LOADING_TIMEOUT_MESSAGE = 'UI_LOADING_TIMEOUT_MESSAGE',
  UI_LOADING_FAILED = 'UI_LOADING_FAILED',
  UI_LOADING_FAILED_REASONS = 'UI_LOADING_FAILED_REASONS',
  UI_NETWORK_ISSUES = 'UI_NETWORK_ISSUES',
  UI_MISSING_DATA_FILES = 'UI_MISSING_DATA_FILES',
  UI_BROWSER_COMPATIBILITY = 'UI_BROWSER_COMPATIBILITY',
  UI_REFRESH_PAGE = 'UI_REFRESH_PAGE',
  UI_SEARCH_SPECIES = 'UI_SEARCH_SPECIES',
  UI_ALL = 'UI_ALL',
  UI_OWNED = 'UI_OWNED',
  UI_UNOWNED = 'UI_UNOWNED',
  UI_PROPERTIES = 'UI_PROPERTIES',
  UI_LEAST_CONCERN = 'UI_LEAST_CONCERN',
  UI_NEAR_THREATENED = 'UI_NEAR_THREATENED',
  UI_VULNERABLE = 'UI_VULNERABLE',
  UI_ENDANGERED = 'UI_ENDANGERED',
  UI_CRITICALLY_ENDANGERED = 'UI_CRITICALLY_ENDANGERED',
  UI_HERBIVORE = 'UI_HERBIVORE',
  UI_CARNIVORE = 'UI_CARNIVORE',
  UI_OMNIVORE = 'UI_OMNIVORE',
  UI_DECOMPOSER = 'UI_DECOMPOSER',
  UI_SORT_BY = 'UI_SORT_BY',
  UI_NAME = 'UI_NAME',
  UI_POWER = 'UI_POWER',
  UI_HEALTH = 'UI_HEALTH',
  UI_ASCENDING = 'UI_ASCENDING',
  UI_DESCENDING = 'UI_DESCENDING',
  UI_NO_SPECIES_FOUND = 'UI_NO_SPECIES_FOUND',
  UI_ADJUST_SEARCH_FILTER = 'UI_ADJUST_SEARCH_FILTER',

  // Common Messages
  UI_PLEASE_FILL_ALL_FIELDS = 'UI_PLEASE_FILL_ALL_FIELDS',
  UI_AUTHENTICATION_REQUIRED = 'UI_AUTHENTICATION_REQUIRED',
  UI_NETWORK_ERROR = 'UI_NETWORK_ERROR',
  UI_FAILED_TO_CREATE_THEME = 'UI_FAILED_TO_CREATE_THEME',
  UI_PLEASE_ENTER_THEME_NAME = 'UI_PLEASE_ENTER_THEME_NAME',
  UI_CUSTOM_THEME_CREATED = 'UI_CUSTOM_THEME_CREATED',
  UI_SYNC_COMPLETED = 'UI_SYNC_COMPLETED',
  UI_CANNOT_SYNC_OFFLINE = 'UI_CANNOT_SYNC_OFFLINE',
  UI_CURRENCY_GRANTED = 'UI_CURRENCY_GRANTED',
  UI_CARD_GRANTED = 'UI_CARD_GRANTED'
}

// ============================================================================
// TAXONOMY TEXT IDS
// ============================================================================

/**
 * Taxonomy IDs - Used for taxonomic information
 */
export enum TaxonomyId {
  // Oak Tree
  TAXONOMY_OAK_TREE = 'TAXONOMY_OAK_TREE',

  // Giant Kelp
  TAXONOMY_GIANT_KELP = 'TAXONOMY_GIANT_KELP',

  // Reed Canary Grass
  TAXONOMY_REED_CANARY_GRASS = 'TAXONOMY_REED_CANARY_GRASS',

  // European Rabbit
  TAXONOMY_EUROPEAN_RABBIT = 'TAXONOMY_EUROPEAN_RABBIT',

  // Sockeye Salmon
  TAXONOMY_SOCKEYE_SALMON = 'TAXONOMY_SOCKEYE_SALMON',

  // American Black Bear
  TAXONOMY_AMERICAN_BLACK_BEAR = 'TAXONOMY_AMERICAN_BLACK_BEAR',

  // Great White Shark
  TAXONOMY_GREAT_WHITE_SHARK = 'TAXONOMY_GREAT_WHITE_SHARK',

  // Continue for all species...
  TAXONOMY_MYCENA_MUSHROOM = 'TAXONOMY_MYCENA_MUSHROOM',
  TAXONOMY_TURKEY_VULTURE = 'TAXONOMY_TURKEY_VULTURE',
  TAXONOMY_DEER_TICK = 'TAXONOMY_DEER_TICK',
  TAXONOMY_COMMON_EARTHWORM = 'TAXONOMY_COMMON_EARTHWORM',
  TAXONOMY_DUNG_BEETLE = 'TAXONOMY_DUNG_BEETLE',
  TAXONOMY_SOIL_BACTERIA = 'TAXONOMY_SOIL_BACTERIA',
  TAXONOMY_DECOMPOSER_MUSHROOM = 'TAXONOMY_DECOMPOSER_MUSHROOM',
  TAXONOMY_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA = 'TAXONOMY_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA',
  TAXONOMY_IRON_SPRING_BACTERIA = 'TAXONOMY_IRON_SPRING_BACTERIA',
  TAXONOMY_MYCORRHIZAL_FUNGI = 'TAXONOMY_MYCORRHIZAL_FUNGI',
  TAXONOMY_NITROGEN_FIXING_BACTERIA = 'TAXONOMY_NITROGEN_FIXING_BACTERIA',
  TAXONOMY_PACIFIC_KRILL = 'TAXONOMY_PACIFIC_KRILL',
  TAXONOMY_PHYTOPLANKTON = 'TAXONOMY_PHYTOPLANKTON',
  TAXONOMY_ZOOPLANKTON = 'TAXONOMY_ZOOPLANKTON',
  TAXONOMY_EUROPEAN_HONEY_BEE = 'TAXONOMY_EUROPEAN_HONEY_BEE',
  TAXONOMY_VOLCANIC_HYDROGEN_BACTERIA = 'TAXONOMY_VOLCANIC_HYDROGEN_BACTERIA',
  TAXONOMY_NITRIFYING_SOIL_BACTERIA = 'TAXONOMY_NITRIFYING_SOIL_BACTERIA',
  TAXONOMY_SEDIMENT_CHEMOSYNTHETIC_BACTERIA = 'TAXONOMY_SEDIMENT_CHEMOSYNTHETIC_BACTERIA'
}

// ============================================================================
// TAXONOMY DISPLAY TEXT IDS
// ============================================================================

/**
 * Taxonomy Display Name IDs - Used for localized taxonomy names
 * These map to the numeric taxonomy enums for display purposes
 */
export enum TaxonomyDisplayId {
  // Domains
  TAXO_DOMAIN_ARCHAEA = 'TAXO_DOMAIN_ARCHAEA',
  TAXO_DOMAIN_BACTERIA = 'TAXO_DOMAIN_BACTERIA',
  TAXO_DOMAIN_EUKARYOTA = 'TAXO_DOMAIN_EUKARYOTA',

  // Kingdoms
  TAXO_KINGDOM_ANIMALIA = 'TAXO_KINGDOM_ANIMALIA',
  TAXO_KINGDOM_ARCHAEA = 'TAXO_KINGDOM_ARCHAEA',
  TAXO_KINGDOM_BACTERIA = 'TAXO_KINGDOM_BACTERIA',
  TAXO_KINGDOM_CHROMISTA = 'TAXO_KINGDOM_CHROMISTA',
  TAXO_KINGDOM_FUNGI = 'TAXO_KINGDOM_FUNGI',
  TAXO_KINGDOM_PLANTAE = 'TAXO_KINGDOM_PLANTAE',

  // Phylums
  TAXO_PHYLUM_ANNELIDA = 'TAXO_PHYLUM_ANNELIDA',
  TAXO_PHYLUM_AQUIFICOTA = 'TAXO_PHYLUM_AQUIFICOTA',
  TAXO_PHYLUM_ARTHROPODA = 'TAXO_PHYLUM_ARTHROPODA',
  TAXO_PHYLUM_BACILLOTA = 'TAXO_PHYLUM_BACILLOTA',
  TAXO_PHYLUM_BASIDIOMYCOTA = 'TAXO_PHYLUM_BASIDIOMYCOTA',
  TAXO_PHYLUM_CHORDATA = 'TAXO_PHYLUM_CHORDATA',
  TAXO_PHYLUM_GLOMEROMYCOTA = 'TAXO_PHYLUM_GLOMEROMYCOTA',
  TAXO_PHYLUM_MOLLUSCA = 'TAXO_PHYLUM_MOLLUSCA',
  TAXO_PHYLUM_OCHROPHYTA = 'TAXO_PHYLUM_OCHROPHYTA',
  TAXO_PHYLUM_PSEUDOMONADOTA = 'TAXO_PHYLUM_PSEUDOMONADOTA',
  TAXO_PHYLUM_THERMOPROTEOTA = 'TAXO_PHYLUM_THERMOPROTEOTA',
  TAXO_PHYLUM_TRACHEOPHYTA = 'TAXO_PHYLUM_TRACHEOPHYTA',

  // Classes
  TAXO_CLASS_ACIDITHIOBACILLIA = 'TAXO_CLASS_ACIDITHIOBACILLIA',
  TAXO_CLASS_ACTINOPTERYGII = 'TAXO_CLASS_ACTINOPTERYGII',
  TAXO_CLASS_AGARICOMYCETES = 'TAXO_CLASS_AGARICOMYCETES',
  TAXO_CLASS_ALPHAPROTEOBACTERIA = 'TAXO_CLASS_ALPHAPROTEOBACTERIA',
  TAXO_CLASS_AMPHIBIA = 'TAXO_CLASS_AMPHIBIA',
  TAXO_CLASS_AQUIFICAE = 'TAXO_CLASS_AQUIFICAE',
  TAXO_CLASS_ARACHNIDA = 'TAXO_CLASS_ARACHNIDA',
  TAXO_CLASS_AVES = 'TAXO_CLASS_AVES',
  TAXO_CLASS_BACILLARIOPHYCEAE = 'TAXO_CLASS_BACILLARIOPHYCEAE',
  TAXO_CLASS_BACILLI = 'TAXO_CLASS_BACILLI',
  TAXO_CLASS_BETAPROTEOBACTERIA = 'TAXO_CLASS_BETAPROTEOBACTERIA',
  TAXO_CLASS_CHONDRICHTHYES = 'TAXO_CLASS_CHONDRICHTHYES',
  TAXO_CLASS_CLITELLATA = 'TAXO_CLASS_CLITELLATA',
  TAXO_CLASS_COPEPODA = 'TAXO_CLASS_COPEPODA',
  TAXO_CLASS_GASTROPODA = 'TAXO_CLASS_GASTROPODA',
  TAXO_CLASS_GLOMEROMYCETES = 'TAXO_CLASS_GLOMEROMYCETES',
  TAXO_CLASS_INSECTA = 'TAXO_CLASS_INSECTA',
  TAXO_CLASS_LILIOPSIDA = 'TAXO_CLASS_LILIOPSIDA',
  TAXO_CLASS_MAGNOLIOPSIDA = 'TAXO_CLASS_MAGNOLIOPSIDA',
  TAXO_CLASS_MALACOSTRACA = 'TAXO_CLASS_MALACOSTRACA',
  TAXO_CLASS_MAMMALIA = 'TAXO_CLASS_MAMMALIA',
  TAXO_CLASS_PHAEOPHYCEAE = 'TAXO_CLASS_PHAEOPHYCEAE',
  TAXO_CLASS_PINOPSIDA = 'TAXO_CLASS_PINOPSIDA',
  TAXO_CLASS_REPTILIA = 'TAXO_CLASS_REPTILIA',
  TAXO_CLASS_THERMOPROTEI = 'TAXO_CLASS_THERMOPROTEI',

  // Orders
  TAXO_ORDER_ACIDITHIOBACILLALES = 'TAXO_ORDER_ACIDITHIOBACILLALES',
  TAXO_ORDER_AGARICALES = 'TAXO_ORDER_AGARICALES',
  TAXO_ORDER_ALISMATALES = 'TAXO_ORDER_ALISMATALES',
  TAXO_ORDER_ANURA = 'TAXO_ORDER_ANURA',
  TAXO_ORDER_AQUIFICALES = 'TAXO_ORDER_AQUIFICALES',
  TAXO_ORDER_ARANEAE = 'TAXO_ORDER_ARANEAE',
  TAXO_ORDER_ARECALES = 'TAXO_ORDER_ARECALES',
  TAXO_ORDER_ARTIODACTYLA = 'TAXO_ORDER_ARTIODACTYLA',
  TAXO_ORDER_ASTERALES = 'TAXO_ORDER_ASTERALES',
  TAXO_ORDER_BACILLALES = 'TAXO_ORDER_BACILLALES',
  TAXO_ORDER_BURKHOLDERIALES = 'TAXO_ORDER_BURKHOLDERIALES',
  TAXO_ORDER_CALANOIDA = 'TAXO_ORDER_CALANOIDA',
  TAXO_ORDER_CARNIVORA = 'TAXO_ORDER_CARNIVORA',
  TAXO_ORDER_CARYOPHYLLALES = 'TAXO_ORDER_CARYOPHYLLALES',
  TAXO_ORDER_CATHARTIFORMES = 'TAXO_ORDER_CATHARTIFORMES',
  TAXO_ORDER_COLEOPTERA = 'TAXO_ORDER_COLEOPTERA',
  TAXO_ORDER_CRASSICLITELLATA = 'TAXO_ORDER_CRASSICLITELLATA',
  TAXO_ORDER_DIPROTODONTIA = 'TAXO_ORDER_DIPROTODONTIA',
  TAXO_ORDER_ERINACEOMORPHA = 'TAXO_ORDER_ERINACEOMORPHA',
  TAXO_ORDER_EUPHAUSIACEA = 'TAXO_ORDER_EUPHAUSIACEA',
  TAXO_ORDER_FABALES = 'TAXO_ORDER_FABALES',
  TAXO_ORDER_FAGALES = 'TAXO_ORDER_FAGALES',
  TAXO_ORDER_GLOMERALES = 'TAXO_ORDER_GLOMERALES',
  TAXO_ORDER_HYMENOPTERA = 'TAXO_ORDER_HYMENOPTERA',
  TAXO_ORDER_HYPHOMICROBIALES = 'TAXO_ORDER_HYPHOMICROBIALES',
  TAXO_ORDER_IXODIDA = 'TAXO_ORDER_IXODIDA',
  TAXO_ORDER_LAGOMORPHA = 'TAXO_ORDER_LAGOMORPHA',
  TAXO_ORDER_LAMIALES = 'TAXO_ORDER_LAMIALES',
  TAXO_ORDER_LAMINARIALES = 'TAXO_ORDER_LAMINARIALES',
  TAXO_ORDER_LAMNIFORMES = 'TAXO_ORDER_LAMNIFORMES',
  TAXO_ORDER_LEPIDOPTERA = 'TAXO_ORDER_LEPIDOPTERA',
  TAXO_ORDER_LILIALES = 'TAXO_ORDER_LILIALES',
  TAXO_ORDER_MALVALES = 'TAXO_ORDER_MALVALES',
  TAXO_ORDER_NITROSOMONADALES = 'TAXO_ORDER_NITROSOMONADALES',
  TAXO_ORDER_ORTHOPTERA = 'TAXO_ORDER_ORTHOPTERA',
  TAXO_ORDER_PERISSODACTYLA = 'TAXO_ORDER_PERISSODACTYLA',
  TAXO_ORDER_PINALES = 'TAXO_ORDER_PINALES',
  TAXO_ORDER_POALES = 'TAXO_ORDER_POALES',
  TAXO_ORDER_PRIMATES = 'TAXO_ORDER_PRIMATES',
  TAXO_ORDER_PROBOSCIDEA = 'TAXO_ORDER_PROBOSCIDEA',
  TAXO_ORDER_RODENTIA = 'TAXO_ORDER_RODENTIA',
  TAXO_ORDER_ROSALES = 'TAXO_ORDER_ROSALES',
  TAXO_ORDER_SALMONIFORMES = 'TAXO_ORDER_SALMONIFORMES',
  TAXO_ORDER_SCORPIONES = 'TAXO_ORDER_SCORPIONES',
  TAXO_ORDER_SQUAMATA = 'TAXO_ORDER_SQUAMATA',
  TAXO_ORDER_STYLOMMATOPHORA = 'TAXO_ORDER_STYLOMMATOPHORA',
  TAXO_ORDER_TESTUDINES = 'TAXO_ORDER_TESTUDINES',
  TAXO_ORDER_THALASSIOSIRALES = 'TAXO_ORDER_THALASSIOSIRALES',
  TAXO_ORDER_THERMOPROTEALES = 'TAXO_ORDER_THERMOPROTEALES',
  TAXO_ORDER_VITALES = 'TAXO_ORDER_VITALES',

  // Families
  TAXO_FAMILY_ACIDITHIOBACILLACEAE = 'TAXO_FAMILY_ACIDITHIOBACILLACEAE',
  TAXO_FAMILY_AGARICACEAE = 'TAXO_FAMILY_AGARICACEAE',
  TAXO_FAMILY_APIDAE = 'TAXO_FAMILY_APIDAE',
  TAXO_FAMILY_AQUIFICACEAE = 'TAXO_FAMILY_AQUIFICACEAE',
  TAXO_FAMILY_ARANEIDAE = 'TAXO_FAMILY_ARANEIDAE',
  TAXO_FAMILY_ARECACEAE = 'TAXO_FAMILY_ARECACEAE',
  TAXO_FAMILY_ASTERACEAE = 'TAXO_FAMILY_ASTERACEAE',
  TAXO_FAMILY_BACILLACEAE = 'TAXO_FAMILY_BACILLACEAE',
  TAXO_FAMILY_BOVIDAE = 'TAXO_FAMILY_BOVIDAE',
  TAXO_FAMILY_CACTACEAE = 'TAXO_FAMILY_CACTACEAE',
  TAXO_FAMILY_CALANIDAE = 'TAXO_FAMILY_CALANIDAE',
  TAXO_FAMILY_CAMELIDAE = 'TAXO_FAMILY_CAMELIDAE',
  TAXO_FAMILY_CANIDAE = 'TAXO_FAMILY_CANIDAE',
  TAXO_FAMILY_CASTORIDAE = 'TAXO_FAMILY_CASTORIDAE',
  TAXO_FAMILY_CATHARTIDAE = 'TAXO_FAMILY_CATHARTIDAE',
  TAXO_FAMILY_CERVIDAE = 'TAXO_FAMILY_CERVIDAE',
  TAXO_FAMILY_CHELONIIDAE = 'TAXO_FAMILY_CHELONIIDAE',
  TAXO_FAMILY_COMAMONADACEAE = 'TAXO_FAMILY_COMAMONADACEAE',
  TAXO_FAMILY_CRICETIDAE = 'TAXO_FAMILY_CRICETIDAE',
  TAXO_FAMILY_ELEPHANTIDAE = 'TAXO_FAMILY_ELEPHANTIDAE',
  TAXO_FAMILY_EQUIDAE = 'TAXO_FAMILY_EQUIDAE',
  TAXO_FAMILY_ERINACEIDAE = 'TAXO_FAMILY_ERINACEIDAE',
  TAXO_FAMILY_EUPHAUSIIDAE = 'TAXO_FAMILY_EUPHAUSIIDAE',
  TAXO_FAMILY_FABACEAE = 'TAXO_FAMILY_FABACEAE',
  TAXO_FAMILY_FAGACEAE = 'TAXO_FAMILY_FAGACEAE',
  TAXO_FAMILY_FELIDAE = 'TAXO_FAMILY_FELIDAE',
  TAXO_FAMILY_FORMICIDAE = 'TAXO_FAMILY_FORMICIDAE',
  TAXO_FAMILY_GIRAFFIDAE = 'TAXO_FAMILY_GIRAFFIDAE',
  TAXO_FAMILY_GLOMERACEAE = 'TAXO_FAMILY_GLOMERACEAE',
  TAXO_FAMILY_GRYLLIDAE = 'TAXO_FAMILY_GRYLLIDAE',
  TAXO_FAMILY_HADRURIDAE = 'TAXO_FAMILY_HADRURIDAE',
  TAXO_FAMILY_HELICIDAE = 'TAXO_FAMILY_HELICIDAE',
  TAXO_FAMILY_HIPPOPOTAMIDAE = 'TAXO_FAMILY_HIPPOPOTAMIDAE',
  TAXO_FAMILY_HOMINIDAE = 'TAXO_FAMILY_HOMINIDAE',
  TAXO_FAMILY_IXODIDAE = 'TAXO_FAMILY_IXODIDAE',
  TAXO_FAMILY_LACERTIDAE = 'TAXO_FAMILY_LACERTIDAE',
  TAXO_FAMILY_LAMIACEAE = 'TAXO_FAMILY_LAMIACEAE',
  TAXO_FAMILY_LAMINARIACEAE = 'TAXO_FAMILY_LAMINARIACEAE',
  TAXO_FAMILY_LAMNIDAE = 'TAXO_FAMILY_LAMNIDAE',
  TAXO_FAMILY_LEPORIDAE = 'TAXO_FAMILY_LEPORIDAE',
  TAXO_FAMILY_LILIACEAE = 'TAXO_FAMILY_LILIACEAE',
  TAXO_FAMILY_LUMBRICIDAE = 'TAXO_FAMILY_LUMBRICIDAE',
  TAXO_FAMILY_MALVACEAE = 'TAXO_FAMILY_MALVACEAE',
  TAXO_FAMILY_MURIDAE = 'TAXO_FAMILY_MURIDAE',
  TAXO_FAMILY_MYCENACEAE = 'TAXO_FAMILY_MYCENACEAE',
  TAXO_FAMILY_NITROSOMONADACEAE = 'TAXO_FAMILY_NITROSOMONADACEAE',
  TAXO_FAMILY_NYMPHALIDAE = 'TAXO_FAMILY_NYMPHALIDAE',
  TAXO_FAMILY_PHASCOLARCTIDAE = 'TAXO_FAMILY_PHASCOLARCTIDAE',
  TAXO_FAMILY_PINACEAE = 'TAXO_FAMILY_PINACEAE',
  TAXO_FAMILY_POACEAE = 'TAXO_FAMILY_POACEAE',
  TAXO_FAMILY_PROCYONIDAE = 'TAXO_FAMILY_PROCYONIDAE',
  TAXO_FAMILY_PYTHONIDAE = 'TAXO_FAMILY_PYTHONIDAE',
  TAXO_FAMILY_RANIDAE = 'TAXO_FAMILY_RANIDAE',
  TAXO_FAMILY_RHINOCEROTIDAE = 'TAXO_FAMILY_RHINOCEROTIDAE',
  TAXO_FAMILY_RHIZOBIACEAE = 'TAXO_FAMILY_RHIZOBIACEAE',
  TAXO_FAMILY_ROSACEAE = 'TAXO_FAMILY_ROSACEAE',
  TAXO_FAMILY_SALMONIDAE = 'TAXO_FAMILY_SALMONIDAE',
  TAXO_FAMILY_SCARABAEIDAE = 'TAXO_FAMILY_SCARABAEIDAE',
  TAXO_FAMILY_SCIURIDAE = 'TAXO_FAMILY_SCIURIDAE',
  TAXO_FAMILY_SUIDAE = 'TAXO_FAMILY_SUIDAE',
  TAXO_FAMILY_THALASSIOSIRACEAE = 'TAXO_FAMILY_THALASSIOSIRACEAE',
  TAXO_FAMILY_THERMOFILACEAE = 'TAXO_FAMILY_THERMOFILACEAE',
  TAXO_FAMILY_URSIDAE = 'TAXO_FAMILY_URSIDAE',
  TAXO_FAMILY_VITACEAE = 'TAXO_FAMILY_VITACEAE',
  TAXO_FAMILY_ZOSTERACEAE = 'TAXO_FAMILY_ZOSTERACEAE',

  // Genera
  TAXO_GENUS_ACHETA = 'TAXO_GENUS_ACHETA',
  TAXO_GENUS_ACIDITHIOBACILLUS = 'TAXO_GENUS_ACIDITHIOBACILLUS',
  TAXO_GENUS_AGARICUS = 'TAXO_GENUS_AGARICUS',
  TAXO_GENUS_AILUROPODA = 'TAXO_GENUS_AILUROPODA',
  TAXO_GENUS_APIS = 'TAXO_GENUS_APIS',
  TAXO_GENUS_AQUIFEX = 'TAXO_GENUS_AQUIFEX',
  TAXO_GENUS_ARANEUS = 'TAXO_GENUS_ARANEUS',
  TAXO_GENUS_BACILLUS = 'TAXO_GENUS_BACILLUS',
  TAXO_GENUS_BELLIS = 'TAXO_GENUS_BELLIS',
  TAXO_GENUS_BISON = 'TAXO_GENUS_BISON',
  TAXO_GENUS_BOS = 'TAXO_GENUS_BOS',
  TAXO_GENUS_BUBALUS = 'TAXO_GENUS_BUBALUS',
  TAXO_GENUS_CALANUS = 'TAXO_GENUS_CALANUS',
  TAXO_GENUS_CAMELUS = 'TAXO_GENUS_CAMELUS',
  TAXO_GENUS_CANIS = 'TAXO_GENUS_CANIS',
  TAXO_GENUS_CAPRA = 'TAXO_GENUS_CAPRA',
  TAXO_GENUS_CARCHARODON = 'TAXO_GENUS_CARCHARODON',
  TAXO_GENUS_CASTOR = 'TAXO_GENUS_CASTOR',
  TAXO_GENUS_CATHARTES = 'TAXO_GENUS_CATHARTES',
  TAXO_GENUS_CERATOTHERIUM = 'TAXO_GENUS_CERATOTHERIUM',
  TAXO_GENUS_CHELONIA = 'TAXO_GENUS_CHELONIA',
  TAXO_GENUS_COCOS = 'TAXO_GENUS_COCOS',
  TAXO_GENUS_DANAUS = 'TAXO_GENUS_DANAUS',
  TAXO_GENUS_EQUUS = 'TAXO_GENUS_EQUUS',
  TAXO_GENUS_ERINACEUS = 'TAXO_GENUS_ERINACEUS',
  TAXO_GENUS_EUPHAUSIA = 'TAXO_GENUS_EUPHAUSIA',
  TAXO_GENUS_FELIS = 'TAXO_GENUS_FELIS',
  TAXO_GENUS_FORMICA = 'TAXO_GENUS_FORMICA',
  TAXO_GENUS_FRAGARIA = 'TAXO_GENUS_FRAGARIA',
  TAXO_GENUS_GIRAFFA = 'TAXO_GENUS_GIRAFFA',
  TAXO_GENUS_GLOMUS = 'TAXO_GENUS_GLOMUS',
  TAXO_GENUS_GORILLA = 'TAXO_GENUS_GORILLA',
  TAXO_GENUS_HADRURUS = 'TAXO_GENUS_HADRURUS',
  TAXO_GENUS_HELIANTHUS = 'TAXO_GENUS_HELIANTHUS',
  TAXO_GENUS_HELIX = 'TAXO_GENUS_HELIX',
  TAXO_GENUS_HIBISCUS = 'TAXO_GENUS_HIBISCUS',
  TAXO_GENUS_HIPPOPOTAMUS = 'TAXO_GENUS_HIPPOPOTAMUS',
  TAXO_GENUS_IXODES = 'TAXO_GENUS_IXODES',
  TAXO_GENUS_LACERTA = 'TAXO_GENUS_LACERTA',
  TAXO_GENUS_LAMA = 'TAXO_GENUS_LAMA',
  TAXO_GENUS_LOLIUM = 'TAXO_GENUS_LOLIUM',
  TAXO_GENUS_LOXODONTA = 'TAXO_GENUS_LOXODONTA',
  TAXO_GENUS_LUMBRICUS = 'TAXO_GENUS_LUMBRICUS',
  TAXO_GENUS_MACROCYSTIS = 'TAXO_GENUS_MACROCYSTIS',
  TAXO_GENUS_MALUS = 'TAXO_GENUS_MALUS',
  TAXO_GENUS_MAMMUTHUS = 'TAXO_GENUS_MAMMUTHUS',
  TAXO_GENUS_MENTHA = 'TAXO_GENUS_MENTHA',
  TAXO_GENUS_MESOCRICETUS = 'TAXO_GENUS_MESOCRICETUS',
  TAXO_GENUS_MUS = 'TAXO_GENUS_MUS',
  TAXO_GENUS_MYCENA = 'TAXO_GENUS_MYCENA',
  TAXO_GENUS_NITROSOMONAS = 'TAXO_GENUS_NITROSOMONAS',
  TAXO_GENUS_ODOCOILEUS = 'TAXO_GENUS_ODOCOILEUS',
  TAXO_GENUS_ONCORHYNCHUS = 'TAXO_GENUS_ONCORHYNCHUS',
  TAXO_GENUS_OPUNTIA = 'TAXO_GENUS_OPUNTIA',
  TAXO_GENUS_ORYCTOLAGUS = 'TAXO_GENUS_ORYCTOLAGUS',
  TAXO_GENUS_ORYZA = 'TAXO_GENUS_ORYZA',
  TAXO_GENUS_OVIS = 'TAXO_GENUS_OVIS',
  TAXO_GENUS_PAN = 'TAXO_GENUS_PAN',
  TAXO_GENUS_PANTHERA = 'TAXO_GENUS_PANTHERA',
  TAXO_GENUS_PHALARIS = 'TAXO_GENUS_PHALARIS',
  TAXO_GENUS_PHASCOLARCTOS = 'TAXO_GENUS_PHASCOLARCTOS',
  TAXO_GENUS_PINUS = 'TAXO_GENUS_PINUS',
  TAXO_GENUS_PONGO = 'TAXO_GENUS_PONGO',
  TAXO_GENUS_PROCYON = 'TAXO_GENUS_PROCYON',
  TAXO_GENUS_PRUNUS = 'TAXO_GENUS_PRUNUS',
  TAXO_GENUS_PYROCOCCUS = 'TAXO_GENUS_PYROCOCCUS',
  TAXO_GENUS_PYTHON = 'TAXO_GENUS_PYTHON',
  TAXO_GENUS_QUERCUS = 'TAXO_GENUS_QUERCUS',
  TAXO_GENUS_RANA = 'TAXO_GENUS_RANA',
  TAXO_GENUS_RHIZOBIUM = 'TAXO_GENUS_RHIZOBIUM',
  TAXO_GENUS_ROSA = 'TAXO_GENUS_ROSA',
  TAXO_GENUS_SCARABAEUS = 'TAXO_GENUS_SCARABAEUS',
  TAXO_GENUS_SUS = 'TAXO_GENUS_SUS',
  TAXO_GENUS_TAMIAS = 'TAXO_GENUS_TAMIAS',
  TAXO_GENUS_THALASSIOSIRA = 'TAXO_GENUS_THALASSIOSIRA',
  TAXO_GENUS_THIOBACILLUS = 'TAXO_GENUS_THIOBACILLUS',
  TAXO_GENUS_TRIFOLIUM = 'TAXO_GENUS_TRIFOLIUM',
  TAXO_GENUS_TULIPA = 'TAXO_GENUS_TULIPA',
  TAXO_GENUS_URSUS = 'TAXO_GENUS_URSUS',
  TAXO_GENUS_VITIS = 'TAXO_GENUS_VITIS',
  TAXO_GENUS_VULPES = 'TAXO_GENUS_VULPES',
  TAXO_GENUS_ZEA = 'TAXO_GENUS_ZEA',
  TAXO_GENUS_ZOSTERA = 'TAXO_GENUS_ZOSTERA',

  // Species
  TAXO_SPECIES_AEGAGRUS = 'TAXO_SPECIES_AEGAGRUS',
  TAXO_SPECIES_AEOLICUS = 'TAXO_SPECIES_AEOLICUS',
  TAXO_SPECIES_AFRICANA = 'TAXO_SPECIES_AFRICANA',
  TAXO_SPECIES_AMERICANUS = 'TAXO_SPECIES_AMERICANUS',
  TAXO_SPECIES_AMPHIBIUS = 'TAXO_SPECIES_AMPHIBIUS',
  TAXO_SPECIES_ANANASSA = 'TAXO_SPECIES_ANANASSA',
  TAXO_SPECIES_ANNUUS = 'TAXO_SPECIES_ANNUUS',
  TAXO_SPECIES_ARIZONENSIS = 'TAXO_SPECIES_ARIZONENSIS',
  TAXO_SPECIES_ARUNDINACEA = 'TAXO_SPECIES_ARUNDINACEA',
  TAXO_SPECIES_AURA = 'TAXO_SPECIES_AURA',
  TAXO_SPECIES_AURATUS = 'TAXO_SPECIES_AURATUS',
  TAXO_SPECIES_BERINGEI = 'TAXO_SPECIES_BERINGEI',
  TAXO_SPECIES_BISON = 'TAXO_SPECIES_BISON',
  TAXO_SPECIES_BISPORUS = 'TAXO_SPECIES_BISPORUS',
  TAXO_SPECIES_BUBALIS = 'TAXO_SPECIES_BUBALIS',
  TAXO_SPECIES_CABALLUS = 'TAXO_SPECIES_CABALLUS',
  TAXO_SPECIES_CAMELOPARDALIS = 'TAXO_SPECIES_CAMELOPARDALIS',
  TAXO_SPECIES_CANADENSIS = 'TAXO_SPECIES_CANADENSIS',
  TAXO_SPECIES_CARCHARIAS = 'TAXO_SPECIES_CARCHARIAS',
  TAXO_SPECIES_CATUS = 'TAXO_SPECIES_CATUS',
  TAXO_SPECIES_CINEREUS = 'TAXO_SPECIES_CINEREUS',
  TAXO_SPECIES_CUNICULUS = 'TAXO_SPECIES_CUNICULUS',
  TAXO_SPECIES_DENITRIFICANS = 'TAXO_SPECIES_DENITRIFICANS',
  TAXO_SPECIES_DESERTI = 'TAXO_SPECIES_DESERTI',
  TAXO_SPECIES_DIADEMATUS = 'TAXO_SPECIES_DIADEMATUS',
  TAXO_SPECIES_DOMESTICUS = 'TAXO_SPECIES_DOMESTICUS',
  TAXO_SPECIES_DROMEDARIUS = 'TAXO_SPECIES_DROMEDARIUS',
  TAXO_SPECIES_EUROPAEA = 'TAXO_SPECIES_EUROPAEA',
  TAXO_SPECIES_EUROPAEUS = 'TAXO_SPECIES_EUROPAEUS',
  TAXO_SPECIES_FERROOXIDANS = 'TAXO_SPECIES_FERROOXIDANS',
  TAXO_SPECIES_FICUS_INDICA = 'TAXO_SPECIES_FICUS_INDICA',
  TAXO_SPECIES_FINMARCHICUS = 'TAXO_SPECIES_FINMARCHICUS',
  TAXO_SPECIES_FURIOSUS = 'TAXO_SPECIES_FURIOSUS',
  TAXO_SPECIES_GALERICULATA = 'TAXO_SPECIES_GALERICULATA',
  TAXO_SPECIES_GESNERIANA = 'TAXO_SPECIES_GESNERIANA',
  TAXO_SPECIES_GLAMA = 'TAXO_SPECIES_GLAMA',
  TAXO_SPECIES_INTRARADICES = 'TAXO_SPECIES_INTRARADICES',
  TAXO_SPECIES_LATICOLLIS = 'TAXO_SPECIES_LATICOLLIS',
  TAXO_SPECIES_LEGUMINOSARUM = 'TAXO_SPECIES_LEGUMINOSARUM',
  TAXO_SPECIES_LEO = 'TAXO_SPECIES_LEO',
  TAXO_SPECIES_LOTOR = 'TAXO_SPECIES_LOTOR',
  TAXO_SPECIES_LUPUS = 'TAXO_SPECIES_LUPUS',
  TAXO_SPECIES_MARINA = 'TAXO_SPECIES_MARINA',
  TAXO_SPECIES_MAYS = 'TAXO_SPECIES_MAYS',
  TAXO_SPECIES_MELANOLEUCA = 'TAXO_SPECIES_MELANOLEUCA',
  TAXO_SPECIES_MELLIFERA = 'TAXO_SPECIES_MELLIFERA',
  TAXO_SPECIES_MUSCULUS = 'TAXO_SPECIES_MUSCULUS',
  TAXO_SPECIES_MYDAS = 'TAXO_SPECIES_MYDAS',
  TAXO_SPECIES_NERKA = 'TAXO_SPECIES_NERKA',
  TAXO_SPECIES_NUCIFERA = 'TAXO_SPECIES_NUCIFERA',
  TAXO_SPECIES_PACIFICA = 'TAXO_SPECIES_PACIFICA',
  TAXO_SPECIES_PARDUS = 'TAXO_SPECIES_PARDUS',
  TAXO_SPECIES_PERENNE = 'TAXO_SPECIES_PERENNE',
  TAXO_SPECIES_PERENNIS = 'TAXO_SPECIES_PERENNIS',
  TAXO_SPECIES_PLEXIPPUS = 'TAXO_SPECIES_PLEXIPPUS',
  TAXO_SPECIES_POMATIA = 'TAXO_SPECIES_POMATIA',
  TAXO_SPECIES_PRIMIGENIUS = 'TAXO_SPECIES_PRIMIGENIUS',
  TAXO_SPECIES_PSEUDONANA = 'TAXO_SPECIES_PSEUDONANA',
  TAXO_SPECIES_PUMILA = 'TAXO_SPECIES_PUMILA',
  TAXO_SPECIES_PYGMAEUS = 'TAXO_SPECIES_PYGMAEUS',
  TAXO_SPECIES_PYRIFERA = 'TAXO_SPECIES_PYRIFERA',
  TAXO_SPECIES_QUAGGA = 'TAXO_SPECIES_QUAGGA',
  TAXO_SPECIES_REGIUS = 'TAXO_SPECIES_REGIUS',
  TAXO_SPECIES_REPENS = 'TAXO_SPECIES_REPENS',
  TAXO_SPECIES_ROBUR = 'TAXO_SPECIES_ROBUR',
  TAXO_SPECIES_ROSA_SINENSIS = 'TAXO_SPECIES_ROSA_SINENSIS',
  TAXO_SPECIES_RUBIGINOSA = 'TAXO_SPECIES_RUBIGINOSA',
  TAXO_SPECIES_RUFA = 'TAXO_SPECIES_RUFA',
  TAXO_SPECIES_SACER = 'TAXO_SPECIES_SACER',
  TAXO_SPECIES_SATIVA = 'TAXO_SPECIES_SATIVA',
  TAXO_SPECIES_SCAPULARIS = 'TAXO_SPECIES_SCAPULARIS',
  TAXO_SPECIES_SCROFA = 'TAXO_SPECIES_SCROFA',
  TAXO_SPECIES_SERRULATA = 'TAXO_SPECIES_SERRULATA',
  TAXO_SPECIES_SIMUM = 'TAXO_SPECIES_SIMUM',
  TAXO_SPECIES_SPICATA = 'TAXO_SPECIES_SPICATA',
  TAXO_SPECIES_STRIATUS = 'TAXO_SPECIES_STRIATUS',
  TAXO_SPECIES_SUBTILIS = 'TAXO_SPECIES_SUBTILIS',
  TAXO_SPECIES_SYLVESTRIS = 'TAXO_SPECIES_SYLVESTRIS',
  TAXO_SPECIES_TAURUS = 'TAXO_SPECIES_TAURUS',
  TAXO_SPECIES_TEMPORARIA = 'TAXO_SPECIES_TEMPORARIA',
  TAXO_SPECIES_TERRESTRIS = 'TAXO_SPECIES_TERRESTRIS',
  TAXO_SPECIES_TIGRIS = 'TAXO_SPECIES_TIGRIS',
  TAXO_SPECIES_TROGLODYTES = 'TAXO_SPECIES_TROGLODYTES',
  TAXO_SPECIES_VINIFERA = 'TAXO_SPECIES_VINIFERA',
  TAXO_SPECIES_VIRGINIANUS = 'TAXO_SPECIES_VIRGINIANUS',
  TAXO_SPECIES_VULPES = 'TAXO_SPECIES_VULPES',
}