/**
 * BioMasters TCG - Taxonomy Mapping Utilities
 *
 * Bridges between numeric taxonomy enums (for performance) and
 * string localization IDs (for display). This ensures type safety
 * while maintaining the hybrid approach benefits.
 */
import { TaxoDomain, TaxoKingdom, TaxoPhylum, TaxoClass, TaxoOrder, TaxoFamily, TaxoGenus, TaxoSpecies } from './enums';
import { TaxonomyDisplayId } from './text-ids';
/**
 * Maps numeric taxonomy enums to localization string IDs
 * This is the bridge between performance (numeric) and localization (string)
 */
export declare const TAXONOMY_LOCALIZATION_MAP: {
    readonly domain: {
        readonly 1: TaxonomyDisplayId.TAXO_DOMAIN_ARCHAEA;
        readonly 2: TaxonomyDisplayId.TAXO_DOMAIN_BACTERIA;
        readonly 3: TaxonomyDisplayId.TAXO_DOMAIN_EUKARYOTA;
    };
    readonly kingdom: {
        readonly 1: TaxonomyDisplayId.TAXO_KINGDOM_ANIMALIA;
        readonly 2: TaxonomyDisplayId.TAXO_KINGDOM_ARCHAEA;
        readonly 3: TaxonomyDisplayId.TAXO_KINGDOM_BACTERIA;
        readonly 4: TaxonomyDisplayId.TAXO_KINGDOM_CHROMISTA;
        readonly 5: TaxonomyDisplayId.TAXO_KINGDOM_FUNGI;
        readonly 6: TaxonomyDisplayId.TAXO_KINGDOM_PLANTAE;
    };
    readonly phylum: {
        readonly 1: TaxonomyDisplayId.TAXO_PHYLUM_ANNELIDA;
        readonly 2: TaxonomyDisplayId.TAXO_PHYLUM_AQUIFICOTA;
        readonly 3: TaxonomyDisplayId.TAXO_PHYLUM_ARTHROPODA;
        readonly 4: TaxonomyDisplayId.TAXO_PHYLUM_BACILLOTA;
        readonly 5: TaxonomyDisplayId.TAXO_PHYLUM_BASIDIOMYCOTA;
        readonly 6: TaxonomyDisplayId.TAXO_PHYLUM_CHORDATA;
        readonly 7: TaxonomyDisplayId.TAXO_PHYLUM_GLOMEROMYCOTA;
        readonly 8: TaxonomyDisplayId.TAXO_PHYLUM_MOLLUSCA;
        readonly 9: TaxonomyDisplayId.TAXO_PHYLUM_OCHROPHYTA;
        readonly 10: TaxonomyDisplayId.TAXO_PHYLUM_PSEUDOMONADOTA;
        readonly 11: TaxonomyDisplayId.TAXO_PHYLUM_THERMOPROTEOTA;
        readonly 12: TaxonomyDisplayId.TAXO_PHYLUM_TRACHEOPHYTA;
    };
    readonly class: {
        readonly 1: TaxonomyDisplayId.TAXO_CLASS_ACIDITHIOBACILLIA;
        readonly 2: TaxonomyDisplayId.TAXO_CLASS_ACTINOPTERYGII;
        readonly 3: TaxonomyDisplayId.TAXO_CLASS_AGARICOMYCETES;
        readonly 4: TaxonomyDisplayId.TAXO_CLASS_ALPHAPROTEOBACTERIA;
        readonly 5: TaxonomyDisplayId.TAXO_CLASS_AMPHIBIA;
        readonly 6: TaxonomyDisplayId.TAXO_CLASS_AQUIFICAE;
        readonly 7: TaxonomyDisplayId.TAXO_CLASS_ARACHNIDA;
        readonly 8: TaxonomyDisplayId.TAXO_CLASS_AVES;
        readonly 9: TaxonomyDisplayId.TAXO_CLASS_BACILLARIOPHYCEAE;
        readonly 10: TaxonomyDisplayId.TAXO_CLASS_BACILLI;
        readonly 11: TaxonomyDisplayId.TAXO_CLASS_BETAPROTEOBACTERIA;
        readonly 12: TaxonomyDisplayId.TAXO_CLASS_CHONDRICHTHYES;
        readonly 13: TaxonomyDisplayId.TAXO_CLASS_CLITELLATA;
        readonly 14: TaxonomyDisplayId.TAXO_CLASS_COPEPODA;
        readonly 15: TaxonomyDisplayId.TAXO_CLASS_GASTROPODA;
        readonly 16: TaxonomyDisplayId.TAXO_CLASS_GLOMEROMYCETES;
        readonly 17: TaxonomyDisplayId.TAXO_CLASS_INSECTA;
        readonly 18: TaxonomyDisplayId.TAXO_CLASS_LILIOPSIDA;
        readonly 19: TaxonomyDisplayId.TAXO_CLASS_MAGNOLIOPSIDA;
        readonly 20: TaxonomyDisplayId.TAXO_CLASS_MALACOSTRACA;
        readonly 21: TaxonomyDisplayId.TAXO_CLASS_MAMMALIA;
        readonly 22: TaxonomyDisplayId.TAXO_CLASS_PHAEOPHYCEAE;
        readonly 23: TaxonomyDisplayId.TAXO_CLASS_PINOPSIDA;
        readonly 24: TaxonomyDisplayId.TAXO_CLASS_REPTILIA;
        readonly 25: TaxonomyDisplayId.TAXO_CLASS_THERMOPROTEI;
    };
    readonly order: {
        readonly 1: TaxonomyDisplayId.TAXO_ORDER_ACIDITHIOBACILLALES;
        readonly 2: TaxonomyDisplayId.TAXO_ORDER_AGARICALES;
        readonly 3: TaxonomyDisplayId.TAXO_ORDER_ALISMATALES;
        readonly 4: TaxonomyDisplayId.TAXO_ORDER_ANURA;
        readonly 5: TaxonomyDisplayId.TAXO_ORDER_AQUIFICALES;
        readonly 6: TaxonomyDisplayId.TAXO_ORDER_ARANEAE;
        readonly 7: TaxonomyDisplayId.TAXO_ORDER_ARECALES;
        readonly 8: TaxonomyDisplayId.TAXO_ORDER_ARTIODACTYLA;
        readonly 9: TaxonomyDisplayId.TAXO_ORDER_ASTERALES;
        readonly 10: TaxonomyDisplayId.TAXO_ORDER_BACILLALES;
        readonly 11: TaxonomyDisplayId.TAXO_ORDER_BURKHOLDERIALES;
        readonly 12: TaxonomyDisplayId.TAXO_ORDER_CALANOIDA;
        readonly 13: TaxonomyDisplayId.TAXO_ORDER_CARNIVORA;
        readonly 14: TaxonomyDisplayId.TAXO_ORDER_CARYOPHYLLALES;
        readonly 15: TaxonomyDisplayId.TAXO_ORDER_CATHARTIFORMES;
        readonly 16: TaxonomyDisplayId.TAXO_ORDER_COLEOPTERA;
        readonly 17: TaxonomyDisplayId.TAXO_ORDER_CRASSICLITELLATA;
        readonly 18: TaxonomyDisplayId.TAXO_ORDER_DIPROTODONTIA;
        readonly 19: TaxonomyDisplayId.TAXO_ORDER_ERINACEOMORPHA;
        readonly 20: TaxonomyDisplayId.TAXO_ORDER_EUPHAUSIACEA;
        readonly 21: TaxonomyDisplayId.TAXO_ORDER_FABALES;
        readonly 22: TaxonomyDisplayId.TAXO_ORDER_FAGALES;
        readonly 23: TaxonomyDisplayId.TAXO_ORDER_GLOMERALES;
        readonly 24: TaxonomyDisplayId.TAXO_ORDER_HYMENOPTERA;
        readonly 25: TaxonomyDisplayId.TAXO_ORDER_HYPHOMICROBIALES;
        readonly 26: TaxonomyDisplayId.TAXO_ORDER_IXODIDA;
        readonly 27: TaxonomyDisplayId.TAXO_ORDER_LAGOMORPHA;
        readonly 28: TaxonomyDisplayId.TAXO_ORDER_LAMIALES;
        readonly 29: TaxonomyDisplayId.TAXO_ORDER_LAMINARIALES;
        readonly 30: TaxonomyDisplayId.TAXO_ORDER_LAMNIFORMES;
        readonly 31: TaxonomyDisplayId.TAXO_ORDER_LEPIDOPTERA;
        readonly 32: TaxonomyDisplayId.TAXO_ORDER_LILIALES;
        readonly 33: TaxonomyDisplayId.TAXO_ORDER_MALVALES;
        readonly 34: TaxonomyDisplayId.TAXO_ORDER_NITROSOMONADALES;
        readonly 35: TaxonomyDisplayId.TAXO_ORDER_ORTHOPTERA;
        readonly 36: TaxonomyDisplayId.TAXO_ORDER_PERISSODACTYLA;
        readonly 37: TaxonomyDisplayId.TAXO_ORDER_PINALES;
        readonly 38: TaxonomyDisplayId.TAXO_ORDER_POALES;
        readonly 39: TaxonomyDisplayId.TAXO_ORDER_PRIMATES;
        readonly 40: TaxonomyDisplayId.TAXO_ORDER_PROBOSCIDEA;
        readonly 41: TaxonomyDisplayId.TAXO_ORDER_RODENTIA;
        readonly 42: TaxonomyDisplayId.TAXO_ORDER_ROSALES;
        readonly 43: TaxonomyDisplayId.TAXO_ORDER_SALMONIFORMES;
        readonly 44: TaxonomyDisplayId.TAXO_ORDER_SCORPIONES;
        readonly 45: TaxonomyDisplayId.TAXO_ORDER_SQUAMATA;
        readonly 46: TaxonomyDisplayId.TAXO_ORDER_STYLOMMATOPHORA;
        readonly 47: TaxonomyDisplayId.TAXO_ORDER_TESTUDINES;
        readonly 48: TaxonomyDisplayId.TAXO_ORDER_THALASSIOSIRALES;
        readonly 49: TaxonomyDisplayId.TAXO_ORDER_THERMOPROTEALES;
        readonly 50: TaxonomyDisplayId.TAXO_ORDER_VITALES;
    };
    readonly family: {
        readonly 1: TaxonomyDisplayId.TAXO_FAMILY_ACIDITHIOBACILLACEAE;
        readonly 2: TaxonomyDisplayId.TAXO_FAMILY_AGARICACEAE;
        readonly 3: TaxonomyDisplayId.TAXO_FAMILY_APIDAE;
        readonly 4: TaxonomyDisplayId.TAXO_FAMILY_AQUIFICACEAE;
        readonly 5: TaxonomyDisplayId.TAXO_FAMILY_ARANEIDAE;
        readonly 6: TaxonomyDisplayId.TAXO_FAMILY_ARECACEAE;
        readonly 7: TaxonomyDisplayId.TAXO_FAMILY_ASTERACEAE;
        readonly 8: TaxonomyDisplayId.TAXO_FAMILY_BACILLACEAE;
        readonly 9: TaxonomyDisplayId.TAXO_FAMILY_BOVIDAE;
        readonly 10: TaxonomyDisplayId.TAXO_FAMILY_CACTACEAE;
        readonly 11: TaxonomyDisplayId.TAXO_FAMILY_CALANIDAE;
        readonly 12: TaxonomyDisplayId.TAXO_FAMILY_CAMELIDAE;
        readonly 13: TaxonomyDisplayId.TAXO_FAMILY_CANIDAE;
        readonly 14: TaxonomyDisplayId.TAXO_FAMILY_CASTORIDAE;
        readonly 15: TaxonomyDisplayId.TAXO_FAMILY_CATHARTIDAE;
        readonly 16: TaxonomyDisplayId.TAXO_FAMILY_CERVIDAE;
        readonly 17: TaxonomyDisplayId.TAXO_FAMILY_CHELONIIDAE;
        readonly 18: TaxonomyDisplayId.TAXO_FAMILY_COMAMONADACEAE;
        readonly 19: TaxonomyDisplayId.TAXO_FAMILY_CRICETIDAE;
        readonly 20: TaxonomyDisplayId.TAXO_FAMILY_ELEPHANTIDAE;
        readonly 21: TaxonomyDisplayId.TAXO_FAMILY_EQUIDAE;
        readonly 22: TaxonomyDisplayId.TAXO_FAMILY_ERINACEIDAE;
        readonly 23: TaxonomyDisplayId.TAXO_FAMILY_EUPHAUSIIDAE;
        readonly 24: TaxonomyDisplayId.TAXO_FAMILY_FABACEAE;
        readonly 25: TaxonomyDisplayId.TAXO_FAMILY_FAGACEAE;
        readonly 26: TaxonomyDisplayId.TAXO_FAMILY_FELIDAE;
        readonly 27: TaxonomyDisplayId.TAXO_FAMILY_FORMICIDAE;
        readonly 28: TaxonomyDisplayId.TAXO_FAMILY_GIRAFFIDAE;
        readonly 29: TaxonomyDisplayId.TAXO_FAMILY_GLOMERACEAE;
        readonly 30: TaxonomyDisplayId.TAXO_FAMILY_GRYLLIDAE;
        readonly 31: TaxonomyDisplayId.TAXO_FAMILY_HADRURIDAE;
        readonly 32: TaxonomyDisplayId.TAXO_FAMILY_HELICIDAE;
        readonly 33: TaxonomyDisplayId.TAXO_FAMILY_HIPPOPOTAMIDAE;
        readonly 34: TaxonomyDisplayId.TAXO_FAMILY_HOMINIDAE;
        readonly 35: TaxonomyDisplayId.TAXO_FAMILY_IXODIDAE;
        readonly 36: TaxonomyDisplayId.TAXO_FAMILY_LACERTIDAE;
        readonly 37: TaxonomyDisplayId.TAXO_FAMILY_LAMIACEAE;
        readonly 38: TaxonomyDisplayId.TAXO_FAMILY_LAMINARIACEAE;
        readonly 39: TaxonomyDisplayId.TAXO_FAMILY_LAMNIDAE;
        readonly 40: TaxonomyDisplayId.TAXO_FAMILY_LEPORIDAE;
        readonly 41: TaxonomyDisplayId.TAXO_FAMILY_LILIACEAE;
        readonly 42: TaxonomyDisplayId.TAXO_FAMILY_LUMBRICIDAE;
        readonly 43: TaxonomyDisplayId.TAXO_FAMILY_MALVACEAE;
        readonly 44: TaxonomyDisplayId.TAXO_FAMILY_MURIDAE;
        readonly 45: TaxonomyDisplayId.TAXO_FAMILY_MYCENACEAE;
        readonly 46: TaxonomyDisplayId.TAXO_FAMILY_NITROSOMONADACEAE;
        readonly 47: TaxonomyDisplayId.TAXO_FAMILY_NYMPHALIDAE;
        readonly 48: TaxonomyDisplayId.TAXO_FAMILY_PHASCOLARCTIDAE;
        readonly 49: TaxonomyDisplayId.TAXO_FAMILY_PINACEAE;
        readonly 50: TaxonomyDisplayId.TAXO_FAMILY_POACEAE;
        readonly 51: TaxonomyDisplayId.TAXO_FAMILY_PROCYONIDAE;
        readonly 52: TaxonomyDisplayId.TAXO_FAMILY_PYTHONIDAE;
        readonly 53: TaxonomyDisplayId.TAXO_FAMILY_RANIDAE;
        readonly 54: TaxonomyDisplayId.TAXO_FAMILY_RHINOCEROTIDAE;
        readonly 55: TaxonomyDisplayId.TAXO_FAMILY_RHIZOBIACEAE;
        readonly 56: TaxonomyDisplayId.TAXO_FAMILY_ROSACEAE;
        readonly 57: TaxonomyDisplayId.TAXO_FAMILY_SALMONIDAE;
        readonly 58: TaxonomyDisplayId.TAXO_FAMILY_SCARABAEIDAE;
        readonly 59: TaxonomyDisplayId.TAXO_FAMILY_SCIURIDAE;
        readonly 60: TaxonomyDisplayId.TAXO_FAMILY_SUIDAE;
        readonly 61: TaxonomyDisplayId.TAXO_FAMILY_THALASSIOSIRACEAE;
        readonly 62: TaxonomyDisplayId.TAXO_FAMILY_THERMOFILACEAE;
        readonly 63: TaxonomyDisplayId.TAXO_FAMILY_URSIDAE;
        readonly 64: TaxonomyDisplayId.TAXO_FAMILY_VITACEAE;
        readonly 65: TaxonomyDisplayId.TAXO_FAMILY_ZOSTERACEAE;
    };
    readonly genus: {
        readonly 1: TaxonomyDisplayId.TAXO_GENUS_ACHETA;
        readonly 2: TaxonomyDisplayId.TAXO_GENUS_ACIDITHIOBACILLUS;
        readonly 3: TaxonomyDisplayId.TAXO_GENUS_AGARICUS;
        readonly 4: TaxonomyDisplayId.TAXO_GENUS_AILUROPODA;
        readonly 5: TaxonomyDisplayId.TAXO_GENUS_APIS;
        readonly 6: TaxonomyDisplayId.TAXO_GENUS_AQUIFEX;
        readonly 7: TaxonomyDisplayId.TAXO_GENUS_ARANEUS;
        readonly 8: TaxonomyDisplayId.TAXO_GENUS_BACILLUS;
        readonly 9: TaxonomyDisplayId.TAXO_GENUS_BELLIS;
        readonly 10: TaxonomyDisplayId.TAXO_GENUS_BISON;
        readonly 11: TaxonomyDisplayId.TAXO_GENUS_BOS;
        readonly 12: TaxonomyDisplayId.TAXO_GENUS_BUBALUS;
        readonly 13: TaxonomyDisplayId.TAXO_GENUS_CALANUS;
        readonly 14: TaxonomyDisplayId.TAXO_GENUS_CAMELUS;
        readonly 15: TaxonomyDisplayId.TAXO_GENUS_CANIS;
        readonly 16: TaxonomyDisplayId.TAXO_GENUS_CAPRA;
        readonly 17: TaxonomyDisplayId.TAXO_GENUS_CARCHARODON;
        readonly 18: TaxonomyDisplayId.TAXO_GENUS_CASTOR;
        readonly 19: TaxonomyDisplayId.TAXO_GENUS_CATHARTES;
        readonly 20: TaxonomyDisplayId.TAXO_GENUS_CERATOTHERIUM;
        readonly 21: TaxonomyDisplayId.TAXO_GENUS_CHELONIA;
        readonly 22: TaxonomyDisplayId.TAXO_GENUS_COCOS;
        readonly 23: TaxonomyDisplayId.TAXO_GENUS_DANAUS;
        readonly 24: TaxonomyDisplayId.TAXO_GENUS_EQUUS;
        readonly 25: TaxonomyDisplayId.TAXO_GENUS_ERINACEUS;
        readonly 26: TaxonomyDisplayId.TAXO_GENUS_EUPHAUSIA;
        readonly 27: TaxonomyDisplayId.TAXO_GENUS_FELIS;
        readonly 28: TaxonomyDisplayId.TAXO_GENUS_FORMICA;
        readonly 29: TaxonomyDisplayId.TAXO_GENUS_FRAGARIA;
        readonly 30: TaxonomyDisplayId.TAXO_GENUS_GIRAFFA;
        readonly 31: TaxonomyDisplayId.TAXO_GENUS_GLOMUS;
        readonly 32: TaxonomyDisplayId.TAXO_GENUS_GORILLA;
        readonly 33: TaxonomyDisplayId.TAXO_GENUS_HADRURUS;
        readonly 34: TaxonomyDisplayId.TAXO_GENUS_HELIANTHUS;
        readonly 35: TaxonomyDisplayId.TAXO_GENUS_HELIX;
        readonly 36: TaxonomyDisplayId.TAXO_GENUS_HIBISCUS;
        readonly 37: TaxonomyDisplayId.TAXO_GENUS_HIPPOPOTAMUS;
        readonly 38: TaxonomyDisplayId.TAXO_GENUS_IXODES;
        readonly 39: TaxonomyDisplayId.TAXO_GENUS_LACERTA;
        readonly 40: TaxonomyDisplayId.TAXO_GENUS_LAMA;
        readonly 41: TaxonomyDisplayId.TAXO_GENUS_LOLIUM;
        readonly 42: TaxonomyDisplayId.TAXO_GENUS_LOXODONTA;
        readonly 43: TaxonomyDisplayId.TAXO_GENUS_LUMBRICUS;
        readonly 44: TaxonomyDisplayId.TAXO_GENUS_MACROCYSTIS;
        readonly 45: TaxonomyDisplayId.TAXO_GENUS_MALUS;
        readonly 46: TaxonomyDisplayId.TAXO_GENUS_MAMMUTHUS;
        readonly 47: TaxonomyDisplayId.TAXO_GENUS_MENTHA;
        readonly 48: TaxonomyDisplayId.TAXO_GENUS_MESOCRICETUS;
        readonly 49: TaxonomyDisplayId.TAXO_GENUS_MUS;
        readonly 50: TaxonomyDisplayId.TAXO_GENUS_MYCENA;
        readonly 51: TaxonomyDisplayId.TAXO_GENUS_NITROSOMONAS;
        readonly 52: TaxonomyDisplayId.TAXO_GENUS_ODOCOILEUS;
        readonly 53: TaxonomyDisplayId.TAXO_GENUS_ONCORHYNCHUS;
        readonly 54: TaxonomyDisplayId.TAXO_GENUS_OPUNTIA;
        readonly 55: TaxonomyDisplayId.TAXO_GENUS_ORYCTOLAGUS;
        readonly 56: TaxonomyDisplayId.TAXO_GENUS_ORYZA;
        readonly 57: TaxonomyDisplayId.TAXO_GENUS_OVIS;
        readonly 58: TaxonomyDisplayId.TAXO_GENUS_PAN;
        readonly 59: TaxonomyDisplayId.TAXO_GENUS_PANTHERA;
        readonly 60: TaxonomyDisplayId.TAXO_GENUS_PHALARIS;
        readonly 61: TaxonomyDisplayId.TAXO_GENUS_PHASCOLARCTOS;
        readonly 62: TaxonomyDisplayId.TAXO_GENUS_PINUS;
        readonly 63: TaxonomyDisplayId.TAXO_GENUS_PONGO;
        readonly 64: TaxonomyDisplayId.TAXO_GENUS_PROCYON;
        readonly 65: TaxonomyDisplayId.TAXO_GENUS_PRUNUS;
        readonly 66: TaxonomyDisplayId.TAXO_GENUS_PYROCOCCUS;
        readonly 67: TaxonomyDisplayId.TAXO_GENUS_PYTHON;
        readonly 68: TaxonomyDisplayId.TAXO_GENUS_QUERCUS;
        readonly 69: TaxonomyDisplayId.TAXO_GENUS_RANA;
        readonly 70: TaxonomyDisplayId.TAXO_GENUS_RHIZOBIUM;
        readonly 71: TaxonomyDisplayId.TAXO_GENUS_ROSA;
        readonly 72: TaxonomyDisplayId.TAXO_GENUS_SCARABAEUS;
        readonly 73: TaxonomyDisplayId.TAXO_GENUS_SUS;
        readonly 74: TaxonomyDisplayId.TAXO_GENUS_TAMIAS;
        readonly 75: TaxonomyDisplayId.TAXO_GENUS_THALASSIOSIRA;
        readonly 76: TaxonomyDisplayId.TAXO_GENUS_THIOBACILLUS;
        readonly 77: TaxonomyDisplayId.TAXO_GENUS_TRIFOLIUM;
        readonly 78: TaxonomyDisplayId.TAXO_GENUS_TULIPA;
        readonly 79: TaxonomyDisplayId.TAXO_GENUS_URSUS;
        readonly 80: TaxonomyDisplayId.TAXO_GENUS_VITIS;
        readonly 81: TaxonomyDisplayId.TAXO_GENUS_VULPES;
        readonly 82: TaxonomyDisplayId.TAXO_GENUS_ZEA;
        readonly 83: TaxonomyDisplayId.TAXO_GENUS_ZOSTERA;
    };
    readonly species: {
        readonly 1: TaxonomyDisplayId.TAXO_SPECIES_AEGAGRUS;
        readonly 2: TaxonomyDisplayId.TAXO_SPECIES_AEOLICUS;
        readonly 3: TaxonomyDisplayId.TAXO_SPECIES_AFRICANA;
        readonly 4: TaxonomyDisplayId.TAXO_SPECIES_AMERICANUS;
        readonly 5: TaxonomyDisplayId.TAXO_SPECIES_AMPHIBIUS;
        readonly 6: TaxonomyDisplayId.TAXO_SPECIES_ANANASSA;
        readonly 7: TaxonomyDisplayId.TAXO_SPECIES_ANNUUS;
        readonly 8: TaxonomyDisplayId.TAXO_SPECIES_ARIZONENSIS;
        readonly 9: TaxonomyDisplayId.TAXO_SPECIES_ARUNDINACEA;
        readonly 10: TaxonomyDisplayId.TAXO_SPECIES_AURA;
        readonly 11: TaxonomyDisplayId.TAXO_SPECIES_AURATUS;
        readonly 12: TaxonomyDisplayId.TAXO_SPECIES_BERINGEI;
        readonly 13: TaxonomyDisplayId.TAXO_SPECIES_BISON;
        readonly 14: TaxonomyDisplayId.TAXO_SPECIES_BISPORUS;
        readonly 15: TaxonomyDisplayId.TAXO_SPECIES_BUBALIS;
        readonly 16: TaxonomyDisplayId.TAXO_SPECIES_CABALLUS;
        readonly 17: TaxonomyDisplayId.TAXO_SPECIES_CAMELOPARDALIS;
        readonly 18: TaxonomyDisplayId.TAXO_SPECIES_CANADENSIS;
        readonly 19: TaxonomyDisplayId.TAXO_SPECIES_CARCHARIAS;
        readonly 20: TaxonomyDisplayId.TAXO_SPECIES_CATUS;
        readonly 21: TaxonomyDisplayId.TAXO_SPECIES_CINEREUS;
        readonly 22: TaxonomyDisplayId.TAXO_SPECIES_CUNICULUS;
        readonly 23: TaxonomyDisplayId.TAXO_SPECIES_DENITRIFICANS;
        readonly 24: TaxonomyDisplayId.TAXO_SPECIES_DESERTI;
        readonly 25: TaxonomyDisplayId.TAXO_SPECIES_DIADEMATUS;
        readonly 26: TaxonomyDisplayId.TAXO_SPECIES_DOMESTICUS;
        readonly 27: TaxonomyDisplayId.TAXO_SPECIES_DROMEDARIUS;
        readonly 28: TaxonomyDisplayId.TAXO_SPECIES_EUROPAEA;
        readonly 29: TaxonomyDisplayId.TAXO_SPECIES_EUROPAEUS;
        readonly 30: TaxonomyDisplayId.TAXO_SPECIES_FERROOXIDANS;
        readonly 31: TaxonomyDisplayId.TAXO_SPECIES_FICUS_INDICA;
        readonly 32: TaxonomyDisplayId.TAXO_SPECIES_FINMARCHICUS;
        readonly 33: TaxonomyDisplayId.TAXO_SPECIES_FURIOSUS;
        readonly 34: TaxonomyDisplayId.TAXO_SPECIES_GALERICULATA;
        readonly 35: TaxonomyDisplayId.TAXO_SPECIES_GESNERIANA;
        readonly 36: TaxonomyDisplayId.TAXO_SPECIES_GLAMA;
        readonly 37: TaxonomyDisplayId.TAXO_SPECIES_INTRARADICES;
        readonly 38: TaxonomyDisplayId.TAXO_SPECIES_LATICOLLIS;
        readonly 39: TaxonomyDisplayId.TAXO_SPECIES_LEGUMINOSARUM;
        readonly 40: TaxonomyDisplayId.TAXO_SPECIES_LEO;
        readonly 41: TaxonomyDisplayId.TAXO_SPECIES_LOTOR;
        readonly 42: TaxonomyDisplayId.TAXO_SPECIES_LUPUS;
        readonly 43: TaxonomyDisplayId.TAXO_SPECIES_MARINA;
        readonly 44: TaxonomyDisplayId.TAXO_SPECIES_MAYS;
        readonly 45: TaxonomyDisplayId.TAXO_SPECIES_MELANOLEUCA;
        readonly 46: TaxonomyDisplayId.TAXO_SPECIES_MELLIFERA;
        readonly 47: TaxonomyDisplayId.TAXO_SPECIES_MUSCULUS;
        readonly 48: TaxonomyDisplayId.TAXO_SPECIES_MYDAS;
        readonly 49: TaxonomyDisplayId.TAXO_SPECIES_NERKA;
        readonly 50: TaxonomyDisplayId.TAXO_SPECIES_NUCIFERA;
        readonly 51: TaxonomyDisplayId.TAXO_SPECIES_PACIFICA;
        readonly 52: TaxonomyDisplayId.TAXO_SPECIES_PARDUS;
        readonly 53: TaxonomyDisplayId.TAXO_SPECIES_PERENNE;
        readonly 54: TaxonomyDisplayId.TAXO_SPECIES_PERENNIS;
        readonly 55: TaxonomyDisplayId.TAXO_SPECIES_PLEXIPPUS;
        readonly 56: TaxonomyDisplayId.TAXO_SPECIES_POMATIA;
        readonly 57: TaxonomyDisplayId.TAXO_SPECIES_PRIMIGENIUS;
        readonly 58: TaxonomyDisplayId.TAXO_SPECIES_PSEUDONANA;
        readonly 59: TaxonomyDisplayId.TAXO_SPECIES_PUMILA;
        readonly 60: TaxonomyDisplayId.TAXO_SPECIES_PYGMAEUS;
        readonly 61: TaxonomyDisplayId.TAXO_SPECIES_PYRIFERA;
        readonly 62: TaxonomyDisplayId.TAXO_SPECIES_QUAGGA;
        readonly 63: TaxonomyDisplayId.TAXO_SPECIES_REGIUS;
        readonly 64: TaxonomyDisplayId.TAXO_SPECIES_REPENS;
        readonly 65: TaxonomyDisplayId.TAXO_SPECIES_ROBUR;
        readonly 66: TaxonomyDisplayId.TAXO_SPECIES_ROSA_SINENSIS;
        readonly 67: TaxonomyDisplayId.TAXO_SPECIES_RUBIGINOSA;
        readonly 68: TaxonomyDisplayId.TAXO_SPECIES_RUFA;
        readonly 69: TaxonomyDisplayId.TAXO_SPECIES_SACER;
        readonly 70: TaxonomyDisplayId.TAXO_SPECIES_SATIVA;
        readonly 71: TaxonomyDisplayId.TAXO_SPECIES_SCAPULARIS;
        readonly 72: TaxonomyDisplayId.TAXO_SPECIES_SCROFA;
        readonly 73: TaxonomyDisplayId.TAXO_SPECIES_SERRULATA;
        readonly 74: TaxonomyDisplayId.TAXO_SPECIES_SIMUM;
        readonly 75: TaxonomyDisplayId.TAXO_SPECIES_SPICATA;
        readonly 76: TaxonomyDisplayId.TAXO_SPECIES_STRIATUS;
        readonly 77: TaxonomyDisplayId.TAXO_SPECIES_SUBTILIS;
        readonly 78: TaxonomyDisplayId.TAXO_SPECIES_SYLVESTRIS;
        readonly 79: TaxonomyDisplayId.TAXO_SPECIES_TAURUS;
        readonly 80: TaxonomyDisplayId.TAXO_SPECIES_TEMPORARIA;
        readonly 81: TaxonomyDisplayId.TAXO_SPECIES_TERRESTRIS;
        readonly 82: TaxonomyDisplayId.TAXO_SPECIES_TIGRIS;
        readonly 83: TaxonomyDisplayId.TAXO_SPECIES_TROGLODYTES;
        readonly 84: TaxonomyDisplayId.TAXO_SPECIES_VINIFERA;
        readonly 85: TaxonomyDisplayId.TAXO_SPECIES_VIRGINIANUS;
        readonly 86: TaxonomyDisplayId.TAXO_SPECIES_VULPES;
    };
};
/**
 * Utility functions for taxonomy mapping
 * These provide type-safe access to localization IDs from numeric enums
 */
export declare class TaxonomyMapper {
    static getDomainDisplayId(domain: TaxoDomain): TaxonomyDisplayId;
    static getKingdomDisplayId(kingdom: TaxoKingdom): TaxonomyDisplayId;
    static getPhylumDisplayId(phylum: TaxoPhylum): TaxonomyDisplayId;
    static getClassDisplayId(taxoClass: TaxoClass): TaxonomyDisplayId;
    static getOrderDisplayId(order: TaxoOrder): TaxonomyDisplayId;
    static getFamilyDisplayId(family: TaxoFamily): TaxonomyDisplayId;
    static getGenusDisplayId(genus: TaxoGenus): TaxonomyDisplayId;
    static getSpeciesDisplayId(species: TaxoSpecies): TaxonomyDisplayId;
}
//# sourceMappingURL=taxonomy-mapping.d.ts.map