"use strict";
/**
 * BioMasters TCG - Taxonomy Mapping Utilities
 *
 * Bridges between numeric taxonomy enums (for performance) and
 * string localization IDs (for display). This ensures type safety
 * while maintaining the hybrid approach benefits.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TaxonomyMapper = exports.TAXONOMY_LOCALIZATION_MAP = void 0;
const enums_1 = require("./enums");
const text_ids_1 = require("./text-ids");
/**
 * Maps numeric taxonomy enums to localization string IDs
 * This is the bridge between performance (numeric) and localization (string)
 */
exports.TAXONOMY_LOCALIZATION_MAP = {
    domain: {
        [enums_1.TaxoDomain.ARCHAEA]: text_ids_1.TaxonomyDisplayId.TAXO_DOMAIN_ARCHAEA,
        [enums_1.TaxoDomain.BACTERIA]: text_ids_1.TaxonomyDisplayId.TAXO_DOMAIN_BACTERIA,
        [enums_1.TaxoDomain.EUKARYOTA]: text_ids_1.TaxonomyDisplayId.TAXO_DOMAIN_EUKARYOTA,
    },
    kingdom: {
        [enums_1.TaxoKingdom.ANIMALIA]: text_ids_1.TaxonomyDisplayId.TAXO_KINGDOM_ANIMALIA,
        [enums_1.TaxoKingdom.ARCHAEA]: text_ids_1.TaxonomyDisplayId.TAXO_KINGDOM_ARCHAEA,
        [enums_1.TaxoKingdom.BACTERIA]: text_ids_1.TaxonomyDisplayId.TAXO_KINGDOM_BACTERIA,
        [enums_1.TaxoKingdom.CHROMISTA]: text_ids_1.TaxonomyDisplayId.TAXO_KINGDOM_CHROMISTA,
        [enums_1.TaxoKingdom.FUNGI]: text_ids_1.TaxonomyDisplayId.TAXO_KINGDOM_FUNGI,
        [enums_1.TaxoKingdom.PLANTAE]: text_ids_1.TaxonomyDisplayId.TAXO_KINGDOM_PLANTAE,
    },
    phylum: {
        [enums_1.TaxoPhylum.ANNELIDA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_ANNELIDA,
        [enums_1.TaxoPhylum.AQUIFICOTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_AQUIFICOTA,
        [enums_1.TaxoPhylum.ARTHROPODA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_ARTHROPODA,
        [enums_1.TaxoPhylum.BACILLOTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_BACILLOTA,
        [enums_1.TaxoPhylum.BASIDIOMYCOTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_BASIDIOMYCOTA,
        [enums_1.TaxoPhylum.CHORDATA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_CHORDATA,
        [enums_1.TaxoPhylum.GLOMEROMYCOTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_GLOMEROMYCOTA,
        [enums_1.TaxoPhylum.MOLLUSCA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_MOLLUSCA,
        [enums_1.TaxoPhylum.OCHROPHYTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_OCHROPHYTA,
        [enums_1.TaxoPhylum.PSEUDOMONADOTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_PSEUDOMONADOTA,
        [enums_1.TaxoPhylum.THERMOPROTEOTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_THERMOPROTEOTA,
        [enums_1.TaxoPhylum.TRACHEOPHYTA]: text_ids_1.TaxonomyDisplayId.TAXO_PHYLUM_TRACHEOPHYTA,
    },
    class: {
        [enums_1.TaxoClass.ACIDITHIOBACILLIA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_ACIDITHIOBACILLIA,
        [enums_1.TaxoClass.ACTINOPTERYGII]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_ACTINOPTERYGII,
        [enums_1.TaxoClass.AGARICOMYCETES]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_AGARICOMYCETES,
        [enums_1.TaxoClass.ALPHAPROTEOBACTERIA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_ALPHAPROTEOBACTERIA,
        [enums_1.TaxoClass.AMPHIBIA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_AMPHIBIA,
        [enums_1.TaxoClass.AQUIFICAE]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_AQUIFICAE,
        [enums_1.TaxoClass.ARACHNIDA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_ARACHNIDA,
        [enums_1.TaxoClass.AVES]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_AVES,
        [enums_1.TaxoClass.BACILLARIOPHYCEAE]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_BACILLARIOPHYCEAE,
        [enums_1.TaxoClass.BACILLI]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_BACILLI,
        [enums_1.TaxoClass.BETAPROTEOBACTERIA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_BETAPROTEOBACTERIA,
        [enums_1.TaxoClass.CHONDRICHTHYES]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_CHONDRICHTHYES,
        [enums_1.TaxoClass.CLITELLATA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_CLITELLATA,
        [enums_1.TaxoClass.COPEPODA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_COPEPODA,
        [enums_1.TaxoClass.GASTROPODA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_GASTROPODA,
        [enums_1.TaxoClass.GLOMEROMYCETES]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_GLOMEROMYCETES,
        [enums_1.TaxoClass.INSECTA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_INSECTA,
        [enums_1.TaxoClass.LILIOPSIDA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_LILIOPSIDA,
        [enums_1.TaxoClass.MAGNOLIOPSIDA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_MAGNOLIOPSIDA,
        [enums_1.TaxoClass.MALACOSTRACA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_MALACOSTRACA,
        [enums_1.TaxoClass.MAMMALIA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_MAMMALIA,
        [enums_1.TaxoClass.PHAEOPHYCEAE]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_PHAEOPHYCEAE,
        [enums_1.TaxoClass.PINOPSIDA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_PINOPSIDA,
        [enums_1.TaxoClass.REPTILIA]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_REPTILIA,
        [enums_1.TaxoClass.THERMOPROTEI]: text_ids_1.TaxonomyDisplayId.TAXO_CLASS_THERMOPROTEI,
    },
    order: {
        [enums_1.TaxoOrder.ACIDITHIOBACILLALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ACIDITHIOBACILLALES,
        [enums_1.TaxoOrder.AGARICALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_AGARICALES,
        [enums_1.TaxoOrder.ALISMATALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ALISMATALES,
        [enums_1.TaxoOrder.ANURA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ANURA,
        [enums_1.TaxoOrder.AQUIFICALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_AQUIFICALES,
        [enums_1.TaxoOrder.ARANEAE]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ARANEAE,
        [enums_1.TaxoOrder.ARECALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ARECALES,
        [enums_1.TaxoOrder.ARTIODACTYLA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ARTIODACTYLA,
        [enums_1.TaxoOrder.ASTERALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ASTERALES,
        [enums_1.TaxoOrder.BACILLALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_BACILLALES,
        [enums_1.TaxoOrder.BURKHOLDERIALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_BURKHOLDERIALES,
        [enums_1.TaxoOrder.CALANOIDA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_CALANOIDA,
        [enums_1.TaxoOrder.CARNIVORA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_CARNIVORA,
        [enums_1.TaxoOrder.CARYOPHYLLALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_CARYOPHYLLALES,
        [enums_1.TaxoOrder.CATHARTIFORMES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_CATHARTIFORMES,
        [enums_1.TaxoOrder.COLEOPTERA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_COLEOPTERA,
        [enums_1.TaxoOrder.CRASSICLITELLATA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_CRASSICLITELLATA,
        [enums_1.TaxoOrder.DIPROTODONTIA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_DIPROTODONTIA,
        [enums_1.TaxoOrder.ERINACEOMORPHA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ERINACEOMORPHA,
        [enums_1.TaxoOrder.EUPHAUSIACEA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_EUPHAUSIACEA,
        [enums_1.TaxoOrder.FABALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_FABALES,
        [enums_1.TaxoOrder.FAGALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_FAGALES,
        [enums_1.TaxoOrder.GLOMERALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_GLOMERALES,
        [enums_1.TaxoOrder.HYMENOPTERA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_HYMENOPTERA,
        [enums_1.TaxoOrder.HYPHOMICROBIALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_HYPHOMICROBIALES,
        [enums_1.TaxoOrder.IXODIDA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_IXODIDA,
        [enums_1.TaxoOrder.LAGOMORPHA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_LAGOMORPHA,
        [enums_1.TaxoOrder.LAMIALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_LAMIALES,
        [enums_1.TaxoOrder.LAMINARIALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_LAMINARIALES,
        [enums_1.TaxoOrder.LAMNIFORMES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_LAMNIFORMES,
        [enums_1.TaxoOrder.LEPIDOPTERA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_LEPIDOPTERA,
        [enums_1.TaxoOrder.LILIALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_LILIALES,
        [enums_1.TaxoOrder.MALVALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_MALVALES,
        [enums_1.TaxoOrder.NITROSOMONADALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_NITROSOMONADALES,
        [enums_1.TaxoOrder.ORTHOPTERA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ORTHOPTERA,
        [enums_1.TaxoOrder.PERISSODACTYLA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_PERISSODACTYLA,
        [enums_1.TaxoOrder.PINALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_PINALES,
        [enums_1.TaxoOrder.POALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_POALES,
        [enums_1.TaxoOrder.PRIMATES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_PRIMATES,
        [enums_1.TaxoOrder.PROBOSCIDEA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_PROBOSCIDEA,
        [enums_1.TaxoOrder.RODENTIA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_RODENTIA,
        [enums_1.TaxoOrder.ROSALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_ROSALES,
        [enums_1.TaxoOrder.SALMONIFORMES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_SALMONIFORMES,
        [enums_1.TaxoOrder.SCORPIONES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_SCORPIONES,
        [enums_1.TaxoOrder.SQUAMATA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_SQUAMATA,
        [enums_1.TaxoOrder.STYLOMMATOPHORA]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_STYLOMMATOPHORA,
        [enums_1.TaxoOrder.TESTUDINES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_TESTUDINES,
        [enums_1.TaxoOrder.THALASSIOSIRALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_THALASSIOSIRALES,
        [enums_1.TaxoOrder.THERMOPROTEALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_THERMOPROTEALES,
        [enums_1.TaxoOrder.VITALES]: text_ids_1.TaxonomyDisplayId.TAXO_ORDER_VITALES,
    },
    family: {
        [enums_1.TaxoFamily.ACIDITHIOBACILLACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ACIDITHIOBACILLACEAE,
        [enums_1.TaxoFamily.AGARICACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_AGARICACEAE,
        [enums_1.TaxoFamily.APIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_APIDAE,
        [enums_1.TaxoFamily.AQUIFICACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_AQUIFICACEAE,
        [enums_1.TaxoFamily.ARANEIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ARANEIDAE,
        [enums_1.TaxoFamily.ARECACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ARECACEAE,
        [enums_1.TaxoFamily.ASTERACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ASTERACEAE,
        [enums_1.TaxoFamily.BACILLACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_BACILLACEAE,
        [enums_1.TaxoFamily.BOVIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_BOVIDAE,
        [enums_1.TaxoFamily.CACTACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CACTACEAE,
        [enums_1.TaxoFamily.CALANIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CALANIDAE,
        [enums_1.TaxoFamily.CAMELIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CAMELIDAE,
        [enums_1.TaxoFamily.CANIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CANIDAE,
        [enums_1.TaxoFamily.CASTORIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CASTORIDAE,
        [enums_1.TaxoFamily.CATHARTIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CATHARTIDAE,
        [enums_1.TaxoFamily.CERVIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CERVIDAE,
        [enums_1.TaxoFamily.CHELONIIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CHELONIIDAE,
        [enums_1.TaxoFamily.COMAMONADACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_COMAMONADACEAE,
        [enums_1.TaxoFamily.CRICETIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_CRICETIDAE,
        [enums_1.TaxoFamily.ELEPHANTIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ELEPHANTIDAE,
        [enums_1.TaxoFamily.EQUIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_EQUIDAE,
        [enums_1.TaxoFamily.ERINACEIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ERINACEIDAE,
        [enums_1.TaxoFamily.EUPHAUSIIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_EUPHAUSIIDAE,
        [enums_1.TaxoFamily.FABACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_FABACEAE,
        [enums_1.TaxoFamily.FAGACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_FAGACEAE,
        [enums_1.TaxoFamily.FELIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_FELIDAE,
        [enums_1.TaxoFamily.FORMICIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_FORMICIDAE,
        [enums_1.TaxoFamily.GIRAFFIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_GIRAFFIDAE,
        [enums_1.TaxoFamily.GLOMERACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_GLOMERACEAE,
        [enums_1.TaxoFamily.GRYLLIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_GRYLLIDAE,
        [enums_1.TaxoFamily.HADRURIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_HADRURIDAE,
        [enums_1.TaxoFamily.HELICIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_HELICIDAE,
        [enums_1.TaxoFamily.HIPPOPOTAMIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_HIPPOPOTAMIDAE,
        [enums_1.TaxoFamily.HOMINIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_HOMINIDAE,
        [enums_1.TaxoFamily.IXODIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_IXODIDAE,
        [enums_1.TaxoFamily.LACERTIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_LACERTIDAE,
        [enums_1.TaxoFamily.LAMIACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_LAMIACEAE,
        [enums_1.TaxoFamily.LAMINARIACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_LAMINARIACEAE,
        [enums_1.TaxoFamily.LAMNIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_LAMNIDAE,
        [enums_1.TaxoFamily.LEPORIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_LEPORIDAE,
        [enums_1.TaxoFamily.LILIACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_LILIACEAE,
        [enums_1.TaxoFamily.LUMBRICIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_LUMBRICIDAE,
        [enums_1.TaxoFamily.MALVACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_MALVACEAE,
        [enums_1.TaxoFamily.MURIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_MURIDAE,
        [enums_1.TaxoFamily.MYCENACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_MYCENACEAE,
        [enums_1.TaxoFamily.NITROSOMONADACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_NITROSOMONADACEAE,
        [enums_1.TaxoFamily.NYMPHALIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_NYMPHALIDAE,
        [enums_1.TaxoFamily.PHASCOLARCTIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_PHASCOLARCTIDAE,
        [enums_1.TaxoFamily.PINACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_PINACEAE,
        [enums_1.TaxoFamily.POACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_POACEAE,
        [enums_1.TaxoFamily.PROCYONIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_PROCYONIDAE,
        [enums_1.TaxoFamily.PYTHONIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_PYTHONIDAE,
        [enums_1.TaxoFamily.RANIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_RANIDAE,
        [enums_1.TaxoFamily.RHINOCEROTIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_RHINOCEROTIDAE,
        [enums_1.TaxoFamily.RHIZOBIACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_RHIZOBIACEAE,
        [enums_1.TaxoFamily.ROSACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ROSACEAE,
        [enums_1.TaxoFamily.SALMONIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_SALMONIDAE,
        [enums_1.TaxoFamily.SCARABAEIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_SCARABAEIDAE,
        [enums_1.TaxoFamily.SCIURIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_SCIURIDAE,
        [enums_1.TaxoFamily.SUIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_SUIDAE,
        [enums_1.TaxoFamily.THALASSIOSIRACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_THALASSIOSIRACEAE,
        [enums_1.TaxoFamily.THERMOFILACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_THERMOFILACEAE,
        [enums_1.TaxoFamily.URSIDAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_URSIDAE,
        [enums_1.TaxoFamily.VITACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_VITACEAE,
        [enums_1.TaxoFamily.ZOSTERACEAE]: text_ids_1.TaxonomyDisplayId.TAXO_FAMILY_ZOSTERACEAE,
    },
    genus: {
        [enums_1.TaxoGenus.ACHETA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ACHETA,
        [enums_1.TaxoGenus.ACIDITHIOBACILLUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ACIDITHIOBACILLUS,
        [enums_1.TaxoGenus.AGARICUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_AGARICUS,
        [enums_1.TaxoGenus.AILUROPODA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_AILUROPODA,
        [enums_1.TaxoGenus.APIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_APIS,
        [enums_1.TaxoGenus.AQUIFEX]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_AQUIFEX,
        [enums_1.TaxoGenus.ARANEUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ARANEUS,
        [enums_1.TaxoGenus.BACILLUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_BACILLUS,
        [enums_1.TaxoGenus.BELLIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_BELLIS,
        [enums_1.TaxoGenus.BISON]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_BISON,
        [enums_1.TaxoGenus.BOS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_BOS,
        [enums_1.TaxoGenus.BUBALUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_BUBALUS,
        [enums_1.TaxoGenus.CALANUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CALANUS,
        [enums_1.TaxoGenus.CAMELUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CAMELUS,
        [enums_1.TaxoGenus.CANIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CANIS,
        [enums_1.TaxoGenus.CAPRA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CAPRA,
        [enums_1.TaxoGenus.CARCHARODON]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CARCHARODON,
        [enums_1.TaxoGenus.CASTOR]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CASTOR,
        [enums_1.TaxoGenus.CATHARTES]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CATHARTES,
        [enums_1.TaxoGenus.CERATOTHERIUM]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CERATOTHERIUM,
        [enums_1.TaxoGenus.CHELONIA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_CHELONIA,
        [enums_1.TaxoGenus.COCOS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_COCOS,
        [enums_1.TaxoGenus.DANAUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_DANAUS,
        [enums_1.TaxoGenus.EQUUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_EQUUS,
        [enums_1.TaxoGenus.ERINACEUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ERINACEUS,
        [enums_1.TaxoGenus.EUPHAUSIA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_EUPHAUSIA,
        [enums_1.TaxoGenus.FELIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_FELIS,
        [enums_1.TaxoGenus.FORMICA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_FORMICA,
        [enums_1.TaxoGenus.FRAGARIA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_FRAGARIA,
        [enums_1.TaxoGenus.GIRAFFA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_GIRAFFA,
        [enums_1.TaxoGenus.GLOMUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_GLOMUS,
        [enums_1.TaxoGenus.GORILLA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_GORILLA,
        [enums_1.TaxoGenus.HADRURUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_HADRURUS,
        [enums_1.TaxoGenus.HELIANTHUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_HELIANTHUS,
        [enums_1.TaxoGenus.HELIX]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_HELIX,
        [enums_1.TaxoGenus.HIBISCUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_HIBISCUS,
        [enums_1.TaxoGenus.HIPPOPOTAMUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_HIPPOPOTAMUS,
        [enums_1.TaxoGenus.IXODES]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_IXODES,
        [enums_1.TaxoGenus.LACERTA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_LACERTA,
        [enums_1.TaxoGenus.LAMA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_LAMA,
        [enums_1.TaxoGenus.LOLIUM]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_LOLIUM,
        [enums_1.TaxoGenus.LOXODONTA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_LOXODONTA,
        [enums_1.TaxoGenus.LUMBRICUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_LUMBRICUS,
        [enums_1.TaxoGenus.MACROCYSTIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_MACROCYSTIS,
        [enums_1.TaxoGenus.MALUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_MALUS,
        [enums_1.TaxoGenus.MAMMUTHUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_MAMMUTHUS,
        [enums_1.TaxoGenus.MENTHA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_MENTHA,
        [enums_1.TaxoGenus.MESOCRICETUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_MESOCRICETUS,
        [enums_1.TaxoGenus.MUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_MUS,
        [enums_1.TaxoGenus.MYCENA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_MYCENA,
        [enums_1.TaxoGenus.NITROSOMONAS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_NITROSOMONAS,
        [enums_1.TaxoGenus.ODOCOILEUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ODOCOILEUS,
        [enums_1.TaxoGenus.ONCORHYNCHUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ONCORHYNCHUS,
        [enums_1.TaxoGenus.OPUNTIA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_OPUNTIA,
        [enums_1.TaxoGenus.ORYCTOLAGUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ORYCTOLAGUS,
        [enums_1.TaxoGenus.ORYZA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ORYZA,
        [enums_1.TaxoGenus.OVIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_OVIS,
        [enums_1.TaxoGenus.PAN]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PAN,
        [enums_1.TaxoGenus.PANTHERA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PANTHERA,
        [enums_1.TaxoGenus.PHALARIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PHALARIS,
        [enums_1.TaxoGenus.PHASCOLARCTOS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PHASCOLARCTOS,
        [enums_1.TaxoGenus.PINUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PINUS,
        [enums_1.TaxoGenus.PONGO]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PONGO,
        [enums_1.TaxoGenus.PROCYON]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PROCYON,
        [enums_1.TaxoGenus.PRUNUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PRUNUS,
        [enums_1.TaxoGenus.PYROCOCCUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PYROCOCCUS,
        [enums_1.TaxoGenus.PYTHON]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_PYTHON,
        [enums_1.TaxoGenus.QUERCUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_QUERCUS,
        [enums_1.TaxoGenus.RANA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_RANA,
        [enums_1.TaxoGenus.RHIZOBIUM]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_RHIZOBIUM,
        [enums_1.TaxoGenus.ROSA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ROSA,
        [enums_1.TaxoGenus.SCARABAEUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_SCARABAEUS,
        [enums_1.TaxoGenus.SUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_SUS,
        [enums_1.TaxoGenus.TAMIAS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_TAMIAS,
        [enums_1.TaxoGenus.THALASSIOSIRA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_THALASSIOSIRA,
        [enums_1.TaxoGenus.THIOBACILLUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_THIOBACILLUS,
        [enums_1.TaxoGenus.TRIFOLIUM]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_TRIFOLIUM,
        [enums_1.TaxoGenus.TULIPA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_TULIPA,
        [enums_1.TaxoGenus.URSUS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_URSUS,
        [enums_1.TaxoGenus.VITIS]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_VITIS,
        [enums_1.TaxoGenus.VULPES]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_VULPES,
        [enums_1.TaxoGenus.ZEA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ZEA,
        [enums_1.TaxoGenus.ZOSTERA]: text_ids_1.TaxonomyDisplayId.TAXO_GENUS_ZOSTERA,
    },
    species: {
        [enums_1.TaxoSpecies.AEGAGRUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_AEGAGRUS,
        [enums_1.TaxoSpecies.AEOLICUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_AEOLICUS,
        [enums_1.TaxoSpecies.AFRICANA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_AFRICANA,
        [enums_1.TaxoSpecies.AMERICANUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_AMERICANUS,
        [enums_1.TaxoSpecies.AMPHIBIUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_AMPHIBIUS,
        [enums_1.TaxoSpecies.ANANASSA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_ANANASSA,
        [enums_1.TaxoSpecies.ANNUUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_ANNUUS,
        [enums_1.TaxoSpecies.ARIZONENSIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_ARIZONENSIS,
        [enums_1.TaxoSpecies.ARUNDINACEA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_ARUNDINACEA,
        [enums_1.TaxoSpecies.AURA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_AURA,
        [enums_1.TaxoSpecies.AURATUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_AURATUS,
        [enums_1.TaxoSpecies.BERINGEI]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_BERINGEI,
        [enums_1.TaxoSpecies.BISON]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_BISON,
        [enums_1.TaxoSpecies.BISPORUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_BISPORUS,
        [enums_1.TaxoSpecies.BUBALIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_BUBALIS,
        [enums_1.TaxoSpecies.CABALLUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_CABALLUS,
        [enums_1.TaxoSpecies.CAMELOPARDALIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_CAMELOPARDALIS,
        [enums_1.TaxoSpecies.CANADENSIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_CANADENSIS,
        [enums_1.TaxoSpecies.CARCHARIAS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_CARCHARIAS,
        [enums_1.TaxoSpecies.CATUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_CATUS,
        [enums_1.TaxoSpecies.CINEREUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_CINEREUS,
        [enums_1.TaxoSpecies.CUNICULUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_CUNICULUS,
        [enums_1.TaxoSpecies.DENITRIFICANS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_DENITRIFICANS,
        [enums_1.TaxoSpecies.DESERTI]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_DESERTI,
        [enums_1.TaxoSpecies.DIADEMATUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_DIADEMATUS,
        [enums_1.TaxoSpecies.DOMESTICUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_DOMESTICUS,
        [enums_1.TaxoSpecies.DROMEDARIUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_DROMEDARIUS,
        [enums_1.TaxoSpecies.EUROPAEA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_EUROPAEA,
        [enums_1.TaxoSpecies.EUROPAEUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_EUROPAEUS,
        [enums_1.TaxoSpecies.FERROOXIDANS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_FERROOXIDANS,
        [enums_1.TaxoSpecies.FICUS_INDICA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_FICUS_INDICA,
        [enums_1.TaxoSpecies.FINMARCHICUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_FINMARCHICUS,
        [enums_1.TaxoSpecies.FURIOSUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_FURIOSUS,
        [enums_1.TaxoSpecies.GALERICULATA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_GALERICULATA,
        [enums_1.TaxoSpecies.GESNERIANA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_GESNERIANA,
        [enums_1.TaxoSpecies.GLAMA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_GLAMA,
        [enums_1.TaxoSpecies.INTRARADICES]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_INTRARADICES,
        [enums_1.TaxoSpecies.LATICOLLIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_LATICOLLIS,
        [enums_1.TaxoSpecies.LEGUMINOSARUM]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_LEGUMINOSARUM,
        [enums_1.TaxoSpecies.LEO]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_LEO,
        [enums_1.TaxoSpecies.LOTOR]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_LOTOR,
        [enums_1.TaxoSpecies.LUPUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_LUPUS,
        [enums_1.TaxoSpecies.MARINA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_MARINA,
        [enums_1.TaxoSpecies.MAYS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_MAYS,
        [enums_1.TaxoSpecies.MELANOLEUCA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_MELANOLEUCA,
        [enums_1.TaxoSpecies.MELLIFERA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_MELLIFERA,
        [enums_1.TaxoSpecies.MUSCULUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_MUSCULUS,
        [enums_1.TaxoSpecies.MYDAS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_MYDAS,
        [enums_1.TaxoSpecies.NERKA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_NERKA,
        [enums_1.TaxoSpecies.NUCIFERA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_NUCIFERA,
        [enums_1.TaxoSpecies.PACIFICA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PACIFICA,
        [enums_1.TaxoSpecies.PARDUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PARDUS,
        [enums_1.TaxoSpecies.PERENNE]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PERENNE,
        [enums_1.TaxoSpecies.PERENNIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PERENNIS,
        [enums_1.TaxoSpecies.PLEXIPPUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PLEXIPPUS,
        [enums_1.TaxoSpecies.POMATIA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_POMATIA,
        [enums_1.TaxoSpecies.PRIMIGENIUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PRIMIGENIUS,
        [enums_1.TaxoSpecies.PSEUDONANA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PSEUDONANA,
        [enums_1.TaxoSpecies.PUMILA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PUMILA,
        [enums_1.TaxoSpecies.PYGMAEUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PYGMAEUS,
        [enums_1.TaxoSpecies.PYRIFERA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_PYRIFERA,
        [enums_1.TaxoSpecies.QUAGGA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_QUAGGA,
        [enums_1.TaxoSpecies.REGIUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_REGIUS,
        [enums_1.TaxoSpecies.REPENS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_REPENS,
        [enums_1.TaxoSpecies.ROBUR]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_ROBUR,
        [enums_1.TaxoSpecies.ROSA_SINENSIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_ROSA_SINENSIS,
        [enums_1.TaxoSpecies.RUBIGINOSA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_RUBIGINOSA,
        [enums_1.TaxoSpecies.RUFA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_RUFA,
        [enums_1.TaxoSpecies.SACER]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SACER,
        [enums_1.TaxoSpecies.SATIVA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SATIVA,
        [enums_1.TaxoSpecies.SCAPULARIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SCAPULARIS,
        [enums_1.TaxoSpecies.SCROFA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SCROFA,
        [enums_1.TaxoSpecies.SERRULATA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SERRULATA,
        [enums_1.TaxoSpecies.SIMUM]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SIMUM,
        [enums_1.TaxoSpecies.SPICATA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SPICATA,
        [enums_1.TaxoSpecies.STRIATUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_STRIATUS,
        [enums_1.TaxoSpecies.SUBTILIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SUBTILIS,
        [enums_1.TaxoSpecies.SYLVESTRIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_SYLVESTRIS,
        [enums_1.TaxoSpecies.TAURUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_TAURUS,
        [enums_1.TaxoSpecies.TEMPORARIA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_TEMPORARIA,
        [enums_1.TaxoSpecies.TERRESTRIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_TERRESTRIS,
        [enums_1.TaxoSpecies.TIGRIS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_TIGRIS,
        [enums_1.TaxoSpecies.TROGLODYTES]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_TROGLODYTES,
        [enums_1.TaxoSpecies.VINIFERA]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_VINIFERA,
        [enums_1.TaxoSpecies.VIRGINIANUS]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_VIRGINIANUS,
        [enums_1.TaxoSpecies.VULPES]: text_ids_1.TaxonomyDisplayId.TAXO_SPECIES_VULPES,
    }
};
/**
 * Utility functions for taxonomy mapping
 * These provide type-safe access to localization IDs from numeric enums
 */
class TaxonomyMapper {
    static getDomainDisplayId(domain) {
        return exports.TAXONOMY_LOCALIZATION_MAP.domain[domain] || `TAXO_DOMAIN_${domain}`;
    }
    static getKingdomDisplayId(kingdom) {
        return exports.TAXONOMY_LOCALIZATION_MAP.kingdom[kingdom] || `TAXO_KINGDOM_${kingdom}`;
    }
    static getPhylumDisplayId(phylum) {
        return exports.TAXONOMY_LOCALIZATION_MAP.phylum[phylum] || `TAXO_PHYLUM_${phylum}`;
    }
    static getClassDisplayId(taxoClass) {
        return exports.TAXONOMY_LOCALIZATION_MAP.class[taxoClass] || `TAXO_CLASS_${taxoClass}`;
    }
    static getOrderDisplayId(order) {
        return exports.TAXONOMY_LOCALIZATION_MAP.order[order] || `TAXO_ORDER_${order}`;
    }
    static getFamilyDisplayId(family) {
        return exports.TAXONOMY_LOCALIZATION_MAP.family[family] || `TAXO_FAMILY_${family}`;
    }
    static getGenusDisplayId(genus) {
        return exports.TAXONOMY_LOCALIZATION_MAP.genus[genus] || `TAXO_GENUS_${genus}`;
    }
    static getSpeciesDisplayId(species) {
        return exports.TAXONOMY_LOCALIZATION_MAP.species[species] || `TAXO_SPECIES_${species}`;
    }
}
exports.TaxonomyMapper = TaxonomyMapper;
//# sourceMappingURL=taxonomy-mapping.js.map