/**
 * BioMasters TCG - Text ID Enums
 *
 * This file contains all text identifiers used for localization.
 * These IDs are used to reference text content in localization files.
 *
 * IMPORTANT: These are the single source of truth for all localizable text.
 * When adding new content, add the ID here first, then add translations.
 */

// ============================================================================
// LANGUAGE AND LOCALIZATION ENUMS
// ============================================================================

/**
 * Supported languages for localization
 */
export enum SupportedLanguage {
  ENGLISH = 'en',
  SPANISH = 'es'
}

/**
 * Language display information
 */
export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

/**
 * Language configuration mapping
 */
export const LANGUAGE_CONFIG: Record<SupportedLanguage, LanguageInfo> = {
  [SupportedLanguage.ENGLISH]: {
    code: SupportedLanguage.ENGLISH,
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸'
  },
  [SupportedLanguage.SPANISH]: {
    code: SupportedLanguage.SPANISH,
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸'
  }
};

// ============================================================================
// CARD TEXT IDS
// ============================================================================

/**
 * Card Name IDs - Used for card display names
 */
export enum CardNameId {
  // Producers (Trophic Level 1)
  CARD_OAK_TREE = 'CARD_OAK_TREE',
  CARD_GIANT_KELP = 'CARD_GIANT_KELP',
  CARD_REED_CANARY_GRASS = 'CARD_REED_CANARY_GRASS',
  CARD_PHYTOPLANKTON = 'CARD_PHYTOPLANKTON',

  // Chemoautotrophs (Trophic Level 1)
  CARD_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA = 'CARD_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA',
  CARD_IRON_SPRING_BACTERIA = 'CARD_IRON_SPRING_BACTERIA',
  CARD_VOLCANIC_HYDROGEN_BACTERIA = 'CARD_VOLCANIC_HYDROGEN_BACTERIA',
  CARD_NITRIFYING_SOIL_BACTERIA = 'CARD_NITRIFYING_SOIL_BACTERIA',
  CARD_SEDIMENT_CHEMOSYNTHETIC_BACTERIA = 'CARD_SEDIMENT_CHEMOSYNTHETIC_BACTERIA',

  // Primary Consumers (Trophic Level 2)
  CARD_EUROPEAN_RABBIT = 'CARD_EUROPEAN_RABBIT',
  CARD_SOCKEYE_SALMON = 'CARD_SOCKEYE_SALMON',
  CARD_PACIFIC_KRILL = 'CARD_PACIFIC_KRILL',
  CARD_ZOOPLANKTON = 'CARD_ZOOPLANKTON',
  CARD_EUROPEAN_HONEY_BEE = 'CARD_EUROPEAN_HONEY_BEE',

  // Secondary/Tertiary Consumers (Trophic Level 3-4)
  CARD_AMERICAN_BLACK_BEAR = 'CARD_AMERICAN_BLACK_BEAR',
  CARD_GREAT_WHITE_SHARK = 'CARD_GREAT_WHITE_SHARK',

  // Decomposers (Trophic Level -1)
  CARD_MYCENA_MUSHROOM = 'CARD_MYCENA_MUSHROOM',
  CARD_TURKEY_VULTURE = 'CARD_TURKEY_VULTURE',
  CARD_SOIL_BACTERIA = 'CARD_SOIL_BACTERIA',
  CARD_DECOMPOSER_MUSHROOM = 'CARD_DECOMPOSER_MUSHROOM',

  // Detritivores (Trophic Level -2)
  CARD_COMMON_EARTHWORM = 'CARD_COMMON_EARTHWORM',
  CARD_DUNG_BEETLE = 'CARD_DUNG_BEETLE',

  // Parasites
  CARD_DEER_TICK = 'CARD_DEER_TICK',

  // Mutualists
  CARD_MYCORRHIZAL_FUNGI = 'CARD_MYCORRHIZAL_FUNGI',
  CARD_NITROGEN_FIXING_BACTERIA = 'CARD_NITROGEN_FIXING_BACTERIA'
}

/**
 * Scientific Name IDs - Used for scientific names (universal but may need alphabet conversion)
 */
export enum ScientificNameId {
  // Producers
  SCIENTIFIC_QUERCUS_ROBUR = 'SCIENTIFIC_QUERCUS_ROBUR',
  SCIENTIFIC_MACROCYSTIS_PYRIFERA = 'SCIENTIFIC_MACROCYSTIS_PYRIFERA',
  SCIENTIFIC_PHALARIS_ARUNDINACEA = 'SCIENTIFIC_PHALARIS_ARUNDINACEA',
  SCIENTIFIC_PHYTOPLANKTON_MIXED = 'SCIENTIFIC_PHYTOPLANKTON_MIXED',

  // Chemoautotrophs
  SCIENTIFIC_THERMOTOGA_MARITIMA = 'SCIENTIFIC_THERMOTOGA_MARITIMA',
  SCIENTIFIC_ACIDITHIOBACILLUS_FERROOXIDANS = 'SCIENTIFIC_ACIDITHIOBACILLUS_FERROOXIDANS',
  SCIENTIFIC_PYROCOCCUS_FURIOSUS = 'SCIENTIFIC_PYROCOCCUS_FURIOSUS',
  SCIENTIFIC_NITROSOMONAS_EUROPAEA = 'SCIENTIFIC_NITROSOMONAS_EUROPAEA',
  SCIENTIFIC_BEGGIATOA_ALBA = 'SCIENTIFIC_BEGGIATOA_ALBA',

  // Primary Consumers
  SCIENTIFIC_ORYCTOLAGUS_CUNICULUS = 'SCIENTIFIC_ORYCTOLAGUS_CUNICULUS',
  SCIENTIFIC_ONCORHYNCHUS_NERKA = 'SCIENTIFIC_ONCORHYNCHUS_NERKA',
  SCIENTIFIC_EUPHAUSIA_PACIFICA = 'SCIENTIFIC_EUPHAUSIA_PACIFICA',
  SCIENTIFIC_ZOOPLANKTON_MIXED = 'SCIENTIFIC_ZOOPLANKTON_MIXED',
  SCIENTIFIC_APIS_MELLIFERA = 'SCIENTIFIC_APIS_MELLIFERA',

  // Secondary/Tertiary Consumers
  SCIENTIFIC_URSUS_AMERICANUS = 'SCIENTIFIC_URSUS_AMERICANUS',
  SCIENTIFIC_CARCHARODON_CARCHARIAS = 'SCIENTIFIC_CARCHARODON_CARCHARIAS',

  // Decomposers
  SCIENTIFIC_MYCENA_GALERICULATA = 'SCIENTIFIC_MYCENA_GALERICULATA',
  SCIENTIFIC_CATHARTES_AURA = 'SCIENTIFIC_CATHARTES_AURA',
  SCIENTIFIC_BACILLUS_SUBTILIS = 'SCIENTIFIC_BACILLUS_SUBTILIS',
  SCIENTIFIC_AGARICUS_BISPORUS = 'SCIENTIFIC_AGARICUS_BISPORUS',

  // Detritivores
  SCIENTIFIC_LUMBRICUS_TERRESTRIS = 'SCIENTIFIC_LUMBRICUS_TERRESTRIS',
  SCIENTIFIC_SCARABAEUS_LATICOLLIS = 'SCIENTIFIC_SCARABAEUS_LATICOLLIS',

  // Parasites
  SCIENTIFIC_IXODES_SCAPULARIS = 'SCIENTIFIC_IXODES_SCAPULARIS',

  // Mutualists
  SCIENTIFIC_GLOMUS_INTRARADICES = 'SCIENTIFIC_GLOMUS_INTRARADICES',
  SCIENTIFIC_RHIZOBIUM_LEGUMINOSARUM = 'SCIENTIFIC_RHIZOBIUM_LEGUMINOSARUM'
}

/**
 * Card Description IDs - Used for card flavor text and descriptions
 */
export enum CardDescriptionId {
  // Producers
  DESC_OAK_TREE = 'DESC_OAK_TREE',
  DESC_GIANT_KELP = 'DESC_GIANT_KELP',
  DESC_REED_CANARY_GRASS = 'DESC_REED_CANARY_GRASS',
  DESC_PHYTOPLANKTON = 'DESC_PHYTOPLANKTON',

  // Chemoautotrophs
  DESC_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA = 'DESC_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA',
  DESC_IRON_SPRING_BACTERIA = 'DESC_IRON_SPRING_BACTERIA',
  DESC_VOLCANIC_HYDROGEN_BACTERIA = 'DESC_VOLCANIC_HYDROGEN_BACTERIA',
  DESC_NITRIFYING_SOIL_BACTERIA = 'DESC_NITRIFYING_SOIL_BACTERIA',
  DESC_SEDIMENT_CHEMOSYNTHETIC_BACTERIA = 'DESC_SEDIMENT_CHEMOSYNTHETIC_BACTERIA',

  // Primary Consumers
  DESC_EUROPEAN_RABBIT = 'DESC_EUROPEAN_RABBIT',
  DESC_SOCKEYE_SALMON = 'DESC_SOCKEYE_SALMON',
  DESC_PACIFIC_KRILL = 'DESC_PACIFIC_KRILL',
  DESC_ZOOPLANKTON = 'DESC_ZOOPLANKTON',
  DESC_EUROPEAN_HONEY_BEE = 'DESC_EUROPEAN_HONEY_BEE',

  // Secondary/Tertiary Consumers
  DESC_AMERICAN_BLACK_BEAR = 'DESC_AMERICAN_BLACK_BEAR',
  DESC_GREAT_WHITE_SHARK = 'DESC_GREAT_WHITE_SHARK',

  // Decomposers
  DESC_MYCENA_MUSHROOM = 'DESC_MYCENA_MUSHROOM',
  DESC_TURKEY_VULTURE = 'DESC_TURKEY_VULTURE',
  DESC_SOIL_BACTERIA = 'DESC_SOIL_BACTERIA',
  DESC_DECOMPOSER_MUSHROOM = 'DESC_DECOMPOSER_MUSHROOM',

  // Detritivores
  DESC_COMMON_EARTHWORM = 'DESC_COMMON_EARTHWORM',
  DESC_DUNG_BEETLE = 'DESC_DUNG_BEETLE',

  // Parasites
  DESC_DEER_TICK = 'DESC_DEER_TICK',

  // Mutualists
  DESC_MYCORRHIZAL_FUNGI = 'DESC_MYCORRHIZAL_FUNGI',
  DESC_NITROGEN_FIXING_BACTERIA = 'DESC_NITROGEN_FIXING_BACTERIA'
}

// ============================================================================
// ABILITY TEXT IDS
// ============================================================================

/**
 * Ability Name IDs - Used for ability names
 */
export enum AbilityNameId {
  ABILITY_WATERSHED_PREDATOR = 'ABILITY_WATERSHED_PREDATOR',
  ABILITY_APEX_PREDATOR = 'ABILITY_APEX_PREDATOR',
  ABILITY_SCAVENGE = 'ABILITY_SCAVENGE',
  ABILITY_PARASITIC_DRAIN = 'ABILITY_PARASITIC_DRAIN',
  ABILITY_RECYCLER = 'ABILITY_RECYCLER',
  ABILITY_PHOTOSYNTHESIS = 'ABILITY_PHOTOSYNTHESIS',
  ABILITY_PACK_HUNTER = 'ABILITY_PACK_HUNTER',
  ABILITY_FILTER_FEEDER = 'ABILITY_FILTER_FEEDER',
  ABILITY_METAMORPHOSIS = 'ABILITY_METAMORPHOSIS',
  ABILITY_DECOMPOSER = 'ABILITY_DECOMPOSER',
  ABILITY_VENOMOUS = 'ABILITY_VENOMOUS',
  ABILITY_FRUGIVORE = 'ABILITY_FRUGIVORE',
  ABILITY_INSECTIVORE = 'ABILITY_INSECTIVORE',
  ABILITY_HYPERCARNIVORE = 'ABILITY_HYPERCARNIVORE',
  ABILITY_MIGRATORY = 'ABILITY_MIGRATORY',
  ABILITY_CHEMICAL_OPPORTUNIST = 'ABILITY_CHEMICAL_OPPORTUNIST',
  ABILITY_DETRITAL_PROCESSOR = 'ABILITY_DETRITAL_PROCESSOR'
}

/**
 * Ability Description IDs - Used for ability descriptions and rules text
 */
export enum AbilityDescriptionId {
  DESC_WATERSHED_PREDATOR = 'DESC_WATERSHED_PREDATOR',
  DESC_APEX_PREDATOR = 'DESC_APEX_PREDATOR',
  DESC_SCAVENGE = 'DESC_SCAVENGE',
  DESC_PARASITIC_DRAIN = 'DESC_PARASITIC_DRAIN',
  DESC_RECYCLER = 'DESC_RECYCLER',
  DESC_PHOTOSYNTHESIS = 'DESC_PHOTOSYNTHESIS',
  DESC_PACK_HUNTER = 'DESC_PACK_HUNTER',
  DESC_FILTER_FEEDER = 'DESC_FILTER_FEEDER',
  DESC_METAMORPHOSIS = 'DESC_METAMORPHOSIS',
  DESC_DECOMPOSER = 'DESC_DECOMPOSER',
  DESC_VENOMOUS = 'DESC_VENOMOUS',
  DESC_FRUGIVORE = 'DESC_FRUGIVORE',
  DESC_INSECTIVORE = 'DESC_INSECTIVORE',
  DESC_HYPERCARNIVORE = 'DESC_HYPERCARNIVORE',
  DESC_MIGRATORY = 'DESC_MIGRATORY',
  DESC_CHEMICAL_OPPORTUNIST = 'DESC_CHEMICAL_OPPORTUNIST',
  DESC_DETRITAL_PROCESSOR = 'DESC_DETRITAL_PROCESSOR'
}

// ============================================================================
// KEYWORD TEXT IDS
// ============================================================================

/**
 * Keyword Name IDs - Used for keyword names
 */
export enum KeywordNameId {
  // Domain Keywords
  KEYWORD_TERRESTRIAL = 'KEYWORD_TERRESTRIAL',
  KEYWORD_AQUATIC = 'KEYWORD_AQUATIC',
  KEYWORD_AMPHIBIOUS = 'KEYWORD_AMPHIBIOUS',
  KEYWORD_FRESHWATER = 'KEYWORD_FRESHWATER',
  KEYWORD_MARINE = 'KEYWORD_MARINE',
  KEYWORD_EURYHALINE = 'KEYWORD_EURYHALINE',

  // Habitat Keywords
  KEYWORD_FOREST = 'KEYWORD_FOREST',
  KEYWORD_RIVER = 'KEYWORD_RIVER',
  KEYWORD_OCEAN = 'KEYWORD_OCEAN',
  KEYWORD_DESERT = 'KEYWORD_DESERT',
  KEYWORD_GRASSLAND = 'KEYWORD_GRASSLAND',
  KEYWORD_WETLAND = 'KEYWORD_WETLAND',
  KEYWORD_MOUNTAIN = 'KEYWORD_MOUNTAIN',
  KEYWORD_ARCTIC = 'KEYWORD_ARCTIC',
  KEYWORD_TROPICAL = 'KEYWORD_TROPICAL',
  KEYWORD_TEMPERATE = 'KEYWORD_TEMPERATE',

  // Taxonomic Keywords
  KEYWORD_FISH = 'KEYWORD_FISH',
  KEYWORD_MAMMAL = 'KEYWORD_MAMMAL',
  KEYWORD_BIRD = 'KEYWORD_BIRD',
  KEYWORD_REPTILE = 'KEYWORD_REPTILE',
  KEYWORD_AMPHIBIAN = 'KEYWORD_AMPHIBIAN',
  KEYWORD_INSECT = 'KEYWORD_INSECT',
  KEYWORD_ARACHNID = 'KEYWORD_ARACHNID',
  KEYWORD_CRUSTACEAN = 'KEYWORD_CRUSTACEAN',
  KEYWORD_MOLLUSK = 'KEYWORD_MOLLUSK',
  KEYWORD_PLANT = 'KEYWORD_PLANT',
  KEYWORD_FUNGI = 'KEYWORD_FUNGI',
  KEYWORD_BACTERIA = 'KEYWORD_BACTERIA',
  KEYWORD_PROTIST = 'KEYWORD_PROTIST',
  KEYWORD_ARTHROPOD = 'KEYWORD_ARTHROPOD',

  // Behavioral Keywords
  KEYWORD_PACK_HUNTER = 'KEYWORD_PACK_HUNTER',
  KEYWORD_SOLITARY = 'KEYWORD_SOLITARY',
  KEYWORD_SOCIAL = 'KEYWORD_SOCIAL',
  KEYWORD_MIGRATORY = 'KEYWORD_MIGRATORY',
  KEYWORD_TERRITORIAL = 'KEYWORD_TERRITORIAL',
  KEYWORD_NOCTURNAL = 'KEYWORD_NOCTURNAL',
  KEYWORD_DIURNAL = 'KEYWORD_DIURNAL',
  KEYWORD_CREPUSCULAR = 'KEYWORD_CREPUSCULAR',

  // Special Abilities
  KEYWORD_VENOMOUS = 'KEYWORD_VENOMOUS',
  KEYWORD_POISONOUS = 'KEYWORD_POISONOUS',
  KEYWORD_SCAVENGE = 'KEYWORD_SCAVENGE',
  KEYWORD_HYPERCARNIVORE = 'KEYWORD_HYPERCARNIVORE',
  KEYWORD_WATERSHED_PREDATOR = 'KEYWORD_WATERSHED_PREDATOR',
  KEYWORD_PARASITIC_DRAIN = 'KEYWORD_PARASITIC_DRAIN',
  KEYWORD_RECYCLER = 'KEYWORD_RECYCLER',
  KEYWORD_APEX_PREDATOR = 'KEYWORD_APEX_PREDATOR',

  // Size Categories
  KEYWORD_MICROSCOPIC = 'KEYWORD_MICROSCOPIC',
  KEYWORD_TINY = 'KEYWORD_TINY',
  KEYWORD_SMALL = 'KEYWORD_SMALL',
  KEYWORD_MEDIUM = 'KEYWORD_MEDIUM',
  KEYWORD_LARGE = 'KEYWORD_LARGE',
  KEYWORD_HUGE = 'KEYWORD_HUGE',
  KEYWORD_GIGANTIC = 'KEYWORD_GIGANTIC'
}

// ============================================================================
// UI TEXT IDS
// ============================================================================

/**
 * UI Text IDs - Used for user interface elements
 */
export enum UITextId {
  // Game Actions
  UI_PLACE_CARD = 'UI_PLACE_CARD',
  UI_ACTIVATE_ABILITY = 'UI_ACTIVATE_ABILITY',
  UI_PASS_TURN = 'UI_PASS_TURN',
  UI_END_TURN = 'UI_END_TURN',

  // Game Phases
  UI_READY_PHASE = 'UI_READY_PHASE',
  UI_DRAW_PHASE = 'UI_DRAW_PHASE',
  UI_ACTION_PHASE = 'UI_ACTION_PHASE',

  // Game States
  UI_GAME_OVER = 'UI_GAME_OVER',
  UI_YOU_WIN = 'UI_YOU_WIN',
  UI_YOU_LOSE = 'UI_YOU_LOSE',
  UI_DRAW_GAME = 'UI_DRAW_GAME',

  // Error Messages
  UI_INVALID_ACTION = 'UI_INVALID_ACTION',
  UI_NOT_ENOUGH_ENERGY = 'UI_NOT_ENOUGH_ENERGY',
  UI_INVALID_TARGET = 'UI_INVALID_TARGET',
  UI_CARD_EXHAUSTED = 'UI_CARD_EXHAUSTED',
  UI_NO_VALID_TARGETS = 'UI_NO_VALID_TARGETS',
  UI_POSITION_OCCUPIED = 'UI_POSITION_OCCUPIED',
  UI_INVALID_PLACEMENT = 'UI_INVALID_PLACEMENT',

  // Game Terms
  UI_READY = 'UI_READY',
  UI_EXHAUSTED = 'UI_EXHAUSTED',
  UI_DETRITUS_ZONE = 'UI_DETRITUS_ZONE',
  UI_SCORE_PILE = 'UI_SCORE_PILE',
  UI_HAND = 'UI_HAND',
  UI_DECK = 'UI_DECK',
  UI_TROPHIC_LEVEL = 'UI_TROPHIC_LEVEL',
  UI_VICTORY_POINTS = 'UI_VICTORY_POINTS',
  UI_ENERGY_COST = 'UI_ENERGY_COST',
  UI_HOME_CARD = 'UI_HOME_CARD',
  UI_PRODUCTION_LOOP = 'UI_PRODUCTION_LOOP',
  UI_DECOMPOSITION_LOOP = 'UI_DECOMPOSITION_LOOP'
}

// ============================================================================
// TAXONOMY TEXT IDS
// ============================================================================

/**
 * Taxonomy IDs - Used for taxonomic information
 */
export enum TaxonomyId {
  // Oak Tree
  TAXONOMY_OAK_TREE = 'TAXONOMY_OAK_TREE',

  // Giant Kelp
  TAXONOMY_GIANT_KELP = 'TAXONOMY_GIANT_KELP',

  // Reed Canary Grass
  TAXONOMY_REED_CANARY_GRASS = 'TAXONOMY_REED_CANARY_GRASS',

  // European Rabbit
  TAXONOMY_EUROPEAN_RABBIT = 'TAXONOMY_EUROPEAN_RABBIT',

  // Sockeye Salmon
  TAXONOMY_SOCKEYE_SALMON = 'TAXONOMY_SOCKEYE_SALMON',

  // American Black Bear
  TAXONOMY_AMERICAN_BLACK_BEAR = 'TAXONOMY_AMERICAN_BLACK_BEAR',

  // Great White Shark
  TAXONOMY_GREAT_WHITE_SHARK = 'TAXONOMY_GREAT_WHITE_SHARK',

  // Continue for all species...
  TAXONOMY_MYCENA_MUSHROOM = 'TAXONOMY_MYCENA_MUSHROOM',
  TAXONOMY_TURKEY_VULTURE = 'TAXONOMY_TURKEY_VULTURE',
  TAXONOMY_DEER_TICK = 'TAXONOMY_DEER_TICK',
  TAXONOMY_COMMON_EARTHWORM = 'TAXONOMY_COMMON_EARTHWORM',
  TAXONOMY_DUNG_BEETLE = 'TAXONOMY_DUNG_BEETLE',
  TAXONOMY_SOIL_BACTERIA = 'TAXONOMY_SOIL_BACTERIA',
  TAXONOMY_DECOMPOSER_MUSHROOM = 'TAXONOMY_DECOMPOSER_MUSHROOM',
  TAXONOMY_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA = 'TAXONOMY_DEEP_SEA_HYDROTHERMAL_VENT_BACTERIA',
  TAXONOMY_IRON_SPRING_BACTERIA = 'TAXONOMY_IRON_SPRING_BACTERIA',
  TAXONOMY_MYCORRHIZAL_FUNGI = 'TAXONOMY_MYCORRHIZAL_FUNGI',
  TAXONOMY_NITROGEN_FIXING_BACTERIA = 'TAXONOMY_NITROGEN_FIXING_BACTERIA',
  TAXONOMY_PACIFIC_KRILL = 'TAXONOMY_PACIFIC_KRILL',
  TAXONOMY_PHYTOPLANKTON = 'TAXONOMY_PHYTOPLANKTON',
  TAXONOMY_ZOOPLANKTON = 'TAXONOMY_ZOOPLANKTON',
  TAXONOMY_EUROPEAN_HONEY_BEE = 'TAXONOMY_EUROPEAN_HONEY_BEE',
  TAXONOMY_VOLCANIC_HYDROGEN_BACTERIA = 'TAXONOMY_VOLCANIC_HYDROGEN_BACTERIA',
  TAXONOMY_NITRIFYING_SOIL_BACTERIA = 'TAXONOMY_NITRIFYING_SOIL_BACTERIA',
  TAXONOMY_SEDIMENT_CHEMOSYNTHETIC_BACTERIA = 'TAXONOMY_SEDIMENT_CHEMOSYNTHETIC_BACTERIA'
}